#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use Benchmark;
use CGI;
use DBI;

$StartTime = new Benchmark;

require "ResponseElements.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";
require "FSUtilities.pm";
require "HTMLUtilities.pm";
require "Security.pm";
require "Scripts.pm";


$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetSecurityGroups;

%params = $query -> Vars;

$DocumentID    = $params{docid};
$Upload        = $params{upload};
$NumberUploads = $params{numfile};
#$Version done later

# Set defaults

if ($Upload ne "http" && $Upload ne "file") {$Upload        = "file";} 
unless ($NumberUploads)                     {$NumberUploads = 1;}
 

print $query->header;

@error_stack = ();

unless ($DocumentID) {
  push @error_stack,"You are must supply a document number.";
}  
  
&FetchDocument($DocumentID);

if ($params{version} eq "0") {
  $Version = 0;
} else {
  if ($params{version}) {
    $Version    = $params{version};
  } else {   
    $Version = $Documents{$DocumentID}{NVER};
  }
}


&BTeVHeader("File Addition");

unless (&CanAccess($DocumentID,$Version)) {
  push @error_stack,"You are not authorized to view this document.";
}  

my $DocRevID   = &FetchDocRevision($DocumentID,$Version);

unless ($DocRevID) {
  push @error_stack,"This document does not exist.";
}

if ((@error_stack)) {  # The user made one or more mistakes, warn and exit
  &EndPage(@error_stack);
}

print "<center><p>\n";  
print "<h4>You are adding files to a version of a document.<br>\n";
print "These should be files forgotten earlier or a new presentation format of
an existing document.<br>\n";
print "If these are files with updated information, <a href=\"somewhere\">create a new
version</a> instead.<br>\n";
print "If you aren't <font color=\"red\">absolutely sure</font> this is what you want to do, go back
and read the help.<p>\n";
print "The current document document information is reproduced below:</h4>\n";
print "<p></center>\n";  

&PrintRevisionInfo($DocRevID,1);

print $query -> start_multipart_form('POST',$AddFiles);

print $query -> hidden(-name => 'upload',  -default => 'file');
print $query -> hidden(-name => 'version', -default => $Version);
print $query -> hidden(-name => 'docid',   -default => $DocumentID);

print "<p><center><table cellpadding=10>\n";
print "<tr><td>\n";
print "<b>Files to add:</b>\n";
print "</td></tr>";
print "<tr><td>\n";

if ($Upload eq "file") {
  &SingleUploadBox;
} elsif ($Upload eq "http") {
  &SingleHTTPBox;
}  

print "</td></tr>";
print "<tr><td align=center>\n";
print $query -> submit (-value => "Add Files");
print "</td></tr>";

print "</table>\n";

print "</center><p>";
print $query -> end_multipart_form;

&DocDBNavBar;
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);

exit;
