#! /usr/bin/env perl

use lib ".";

#        Name: $RCSfile$
# Description: Group administrative actions into one page
#
#    Revision: $Revision$
#    Modified: $Author$ on $Date$
#
#        Name: AdministerHome
# Description: A "home page" for the various administration pages 
#
#      Author: Lynn Garren (garren@fnal.gov)
#    Modified: Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2013 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CGI qw(-nosticky);
use DBI;

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "SecuritySQL.pm";
require "Scripts.pm";
require "ResponseElements.pm";
require "FormElements.pm";
require "Messages.pm";
require "Security.pm";
require "SecuritySQL.pm";
require "SecurityHTML.pm";

$query = new CGI;  # Global for subroutines
$query -> autoEscape(0);
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

GetSecurityGroups();

print $query -> header( -charset => $HTTP_ENCODING );
DocDBHeader("Administrative Functions","",-scripts => ["PopUps"]);
@ErrorStack = ();

unless (CanAdminister()) {
  push @ErrorStack,"This page is for administrators only. You are not an administrator.";
}

my $PersonalAccountLink = PersonalAccountLink();

EndPage(@ErrorStack);

print "<div id=\"AdministerHomeBody\">\n";

print "<div id=\"Header3Col\">\n";
print "<h4>\n";
print "Administration Functions.\n";
print "</h4>\n";
print "</div>\n";  # Header3Col

print "<div id=\"LeftColumn3Col\">\n";
print "<p><strong><a href=\"$MainPage\">Main Menu</a></strong></p>\n";
print "<p><strong><a href=\"$ModifyHome\">Add Documents</a></strong></p>\n";
print "<p><strong><a href=\"$DocDBInstructions\">Instructions</a></strong></p>\n";
print "<p><strong><a href=\"$DocDBInstructions?set=admin\">Administrator Instructions</strong></p>\n";
if ($PersonalAccountLink) {
  print "<p><strong>$PersonalAccountLink</strong></p>\n";
}
foreach my $Text (@{ $ProjectMessages{Homepage}{LeftColumn} }) {
  print "<p><strong>$Text</strong></p>\n";
}
print "<p><strong><a href=\"$DocDBHome\">About DocDB</a></strong></p>\n";
print "</div>\n";  # LeftColumn3Col

print "<div id=\"MainColumn3Col\">\n";
print "<strong>Document management:</strong>";

### New upload short form

if (CanAdminister()) { # Delete Form
  print "<ul>\n";
  print "<li>";
  print "\n",$query -> start_form('POST',$DeleteConfirm),"<div>\n";
  print $query -> submit (-class => "Action", -value => "Delete");
  print " document # ";
  print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
  print " -v";
  print $query -> textfield(-name => "version", -size => 4, -maxlength => 4);
  print "\n</div>\n",$query -> end_form,"\n\n";
  print "</li>";
  print "</ul>\n";
}

print "<p><strong>Database maintenance:</strong></p>\n";
print "<ul>\n";
print "<li>Add an <a href=\"$AuthorAddForm\">author</a></li>\n";
print "</ul>\n";

if (CanAdminister()) {
  print "<p><b>Administrator only functions:</b></p>\n";
  print "<ul>\n";
  print "<li>Administer <a href=\"$GroupAdministerForm\">groups</a> of users</li>\n";
  print "<li>Administer <a href=\"$TopicAdminister\">topics</a></li>\n";
  print "<li>Administer <a href=\"$EventAdministerForm\">events</a></li>\n";
  print "<li>Administer <a href=\"$EmailAdministerForm\">personal accounts</a>";
  if ($UserValidation eq "certificate") {
    print " or <a href=\"$BulkCertificateInsert\">create new accounts</a>";
  }
  print "</li>\n";
  print "<li>Administer <a href=\"$KeywordAdministerForm\">keywords and keyword groups</a></li>\n";
  print "<li>Administer <a href=\"$AdministerForm\">authors, institutions, types, and journals</a></li>\n";
  print "<li>Administer <a href=\"$ExternalDocDBAdministerForm\">external DocDB</a> information</li>\n";
  print "</ul>\n";
}

print "<hr/>\n";


print "</div>\n";  # MainColumn3Col

print "<div id=\"Footer3Col\">\n"; # Must have to keep NavBar on true bottom
print "</div>\n";  # Footer3Col
print "</div>\n";  # ModifyHomeBody

DocDBNavBar();
DocDBFooter($DBWebMasterEmail,$DBWebMasterName);

