#! /usr/bin/env perl
#
#        Name: AdministerForm
# Description: This single form provides a number of interfaces to admin 
#              tools, each run by a different script. 
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

# Copyright 2001-2004 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "AdministerElements.pm";
require "FormElements.pm";

require "AuthorHTML.pm";
require "JournalHTML.pm";
require "DocTypeHTML.pm";
require "TopicHTML.pm";
require "MeetingHTML.pm";

require "Scripts.pm";
require "Security.pm";

require "SecuritySQL.pm";
require "AuthorSQL.pm";
require "TopicSQL.pm";
require "MiscSQL.pm";
require "ResponseElements.pm";

require "HTMLUtilities.pm";
require "Sorts.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI -> connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetSecurityGroups;
&SpecialMajorTopics;
&GetInstitutions;
&GetDocTypes;
&GetAuthors;
&GetTopics;
&GetJournals;

print $query->header;
&DocDBHeader("Administer $Project DocDB"); # DocDBHeader

&HelpPopupScript;

@ErrorStack = ();
@WarnStack  = ();

unless (&CanAdminister()) {
  push @ErrorStack,"You are not allowed to access administrative functions.";
}

if (@ErrorStack) {  # The user made one or more mistakes, warn and exit
  &EndPage(@ErrorStack);
}

print "<b>This form allows you to administer the lists of things within
the database.</b><p>\n"; 

print "Begin by selecting an action for what you want to administer. If you
       select <b>New</b>, the selection from the first list will be
       ignored, but you must fill in things like Institution and the two names
       for adding authors. If you select <b>Modify</b> you have to make a
       selection from the first list and any attributes you select on the
       right will be changed. If you leave something blank, it will not be
       changed. If you select <b>Delete</b> any selections other than from 
       the first list will be ignored.<p>\n";

print "Note that deleting and then re-entering with the same information is
       not the same as modifying. Everything in the DB is tied together with
       invisible ID numbers.<p>\n";

print "In all cases, you must supply the <i>database</i> username and password for the
       administrator account to make any changes.<p>\n";

print "<center> <b>Modify:</b> ";
print "[&nbsp;<a href=\"\#author\">Authors</a> ] ";
print "[&nbsp;<a href=\"\#institution\">Institutions</a>&nbsp;] ";
print "[&nbsp;<a href=\"\#mintopic\">Minor&nbsp;Topics</a>&nbsp;] ";
print "[&nbsp;<a href=\"\#majtopic\">Major&nbsp;Topics</a>&nbsp;] ";
print "[&nbsp;<a href=\"\#doctype\">Document&nbsp;Types</a>&nbsp;] ";
print "[&nbsp;<a href=\"\#journal\">Journals</a>&nbsp;] ";
print "[&nbsp;<a href=\"\#conference\">Meetings&nbsp;and&nbsp;Conferences</a>&nbsp;] ";
print "</center><p>";
print "<hr><p>\n";

### Author Modification

print "<a name=\"author\"><center><h4>Administer Authors</h4></center>\n";
print "<center>(Changing both the first and last names will erase middle
       initials)</center>\n";

print $query -> start_multipart_form('POST',"$AuthorAdminister");
print "<table cellpadding=10>\n";
print "<tr valign=top>\n";
print "<td colspan=2>\n"; &AdministerActions;      print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td>\n"; &AuthorScroll(-helplink => "author"); print "</td>\n";  
print "<td>\n"; &InstitutionSelect; print "</td>\n";
print "<td>\n"; &NameEntryBox;      print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td colspan=3>\n";
&AdministratorPassword;
print "&nbsp;";
print $query -> submit (-value => "Change Author Info");
print "</td>\n";
print "</tr>\n";

print "</table>\n";
print $query -> end_multipart_form;

print "<p><hr>\n";

### Institution Administration

print "<a name=\"institution\"><center><h4>Administer Institutions</h4></center>\n";

print $query -> start_multipart_form('POST',"$InstitutionAdminister");
print "<table cellpadding=10>\n";
print "<tr valign=top>\n";
print "<td colspan=2>\n"; &AdministerActions;      print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td>\n"; &InstitutionSelect("full"); print "</td>\n";
print "<td>\n"; &InstitutionEntryBox; print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td colspan=3>\n";
&AdministratorPassword;
print "&nbsp;";
print $query -> submit (-value => "Change Institution Info");
print "</td>\n";
print "</tr>\n";

print "</table>\n";
print $query -> end_multipart_form;

print "<p><hr>\n";

### Topic Administration

print "<a name=\"mintopic\"><center><h4>Administer Minor Topics</h4></center>\n";

my %Matrix = ();

$Matrix{topics}{Delete}     = 1;
$Matrix{majortopic}{New}    = 1;
$Matrix{majortopic}{Modify} = 1;
$Matrix{topics}{Modify}     = 1;
$Matrix{shortdesc}{New}     = 1;
$Matrix{shortdesc}{Modify}  = 1;
$Matrix{longdesc}{New}      = 1;
$Matrix{longdesc}{Modify}   = 1;
  
print $query -> start_multipart_form('POST',"$TopicAdminister",
                                    "id=\"minortopic\" name=\"minortopic\"");
print "<table cellpadding=10>\n";
print "<tr valign=top>\n";
print "<td colspan=2>\n"; &AdministerActions(-form => "minortopic", -matrix => \%Matrix);      print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td colspan=2>\n"; 
 &TopicScroll(-helptext  => "Minor Topics", -helplink => "topics", 
              -extratext => " (Long descriptions in brackets)", 
              -multiple  => "true", -format => "long", -disabled => "true"); 
print "</td>\n"; 
print "</tr>\n";

print "<tr valign=top>\n";
print "<td rowspan=2>\n"; &MajorTopicSelect(-disabled => "true"); print "</td>\n";
print "<td>\n"; &ShortDescriptionBox(-name => "shortdesc", -disabled => "true");     print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td>\n"; &LongDescriptionBox(-name => "longdesc", -disabled => "true");     print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td colspan=3>\n";
&AdministratorPassword;
print "&nbsp;";
print $query -> submit (-value => "Change Topic Info");
print "</td>\n";
print "</tr>\n";

print "</table>\n";
print $query -> end_multipart_form;

print "<p><hr>\n";

### Major Topic Administration

print "<a name=\"majtopic\"><center><h4>Administer Major Topics</h4></center>\n";

print $query -> start_multipart_form('POST',"$MajorTopicAdminister");
print "<table cellpadding=10>\n";
print "<tr valign=top>\n";
print "<td colspan=2>\n"; &AdministerActions;      print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td rowspan=2>\n"; &MajorTopicSelect(-format => "full"); print "</td>\n";
print "<td>\n"; &ShortDescriptionBox;     print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td>\n"; &LongDescriptionBox;     print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td colspan=3>\n";
&AdministratorPassword;
print "&nbsp;";
print $query -> submit (-value => "Change Topic Info");
print "</td>\n";
print "</tr>\n";

print "</table>\n";
print $query -> end_multipart_form;

print "<p><hr>\n";

### Document Types

print "<a name=\"doctype\"><center><h4>Administer Document Types</h4></center>\n";

print $query -> start_multipart_form('POST',"$DocTypeAdminister");
print "<table cellpadding=10>\n";
print "<tr valign=top>\n";
print "<td colspan=2>\n"; &AdministerActions;      print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td>\n"; &DocTypeSelect;   print "</td>\n";
print "<td>\n"; &DocTypeEntryBox; print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td colspan=3>\n";
&AdministratorPassword;
print "&nbsp;";
print $query -> submit (-value => "Change Document Type Info");
print "</td>\n";
print "</tr>\n";

print "</table>\n";
print $query -> end_multipart_form;

print "<p><hr>\n";

### Journal Administration

print "<a name=\"journal\"><center><h4>Administer Journals</h4></center>\n";

print $query -> start_multipart_form('POST',"$JournalAdminister");
print "<table cellpadding=10>\n";
print "<tr valign=top>\n";
print "<td colspan=2>\n"; &AdministerActions;      print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td>\n"; &JournalSelect("full"); print "</td>\n";
print "<td>\n"; &JournalEntryBox;     print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td colspan=3>\n";
&AdministratorPassword;
print "&nbsp;";
print $query -> submit (-value => "Change Journal Info");
print "</td>\n";
print "</tr>\n";

print "</table>\n";
print $query -> end_multipart_form;

print "<p>\n";
&JournalTable;

print "<p><hr>\n";

### Conference and Meeting Administration

print "<a name=\"conference\"><center><h4>Administer Conferences and Meetings</h4>
       </center>\n";

print $query -> start_multipart_form('POST',"$ConferenceAdminister");
print "<table cellpadding=10>\n";
print "<tr valign=top>\n";
print "<td colspan=2>\n"; &AdministerActions;      print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td>\n"; &MajorGatheringSelect; print "</td>\n";
print "<td>\n"; &ConferenceSelect;     print "</td>\n";
print "<td>\n";
 print "<table>\n";
 print "<tr valign=top>\n";
 print "<td>\n"; &ShortDescriptionBox;     print "</td>\n";
 print "<td>\n"; &LongDescriptionBox;      print "</td>\n";
 print "</tr>\n";

 print "<tr valign=top>\n";
 print "<td>\n"; &LocationBox;          print "</td>\n";
 print "<td>\n"; &ConferenceURLBox;     print "</td>\n";
 print "</tr>\n";

 print "<tr valign=top>\n";
 print "<td>\n"; &StartDatePullDown;     print "</td>\n";
 print "<td>\n"; &EndDatePullDown;       print "</td>\n";
 print "</tr>\n";
 print "<tr valign=top>\n";
 print "<td colspan=2>(Dates set to the current date will not be changed)</td>\n";
 print "</tr>\n";

 print "</table>\n";
print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td colspan=3>\n";
&AdministratorPassword;
print "&nbsp;";
print $query -> submit (-value => "Change Meeting/Conference Info");
print "</td>\n";
print "</tr>\n";

print "</table>\n";
print $query -> end_multipart_form;

print "<center><h4>Existing Meetings and Conferences</h4></center>\n";

&GatheringTable;

print "<p><hr>\n";

print "<p>\n";

&DocDBNavBar();
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
