#! /usr/bin/env perl
#
# Description: A simple for to allow new author addition (no changes possible)
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

# Copyright 2001-2005 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


use CGI qw(-nosticky);                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "FormElements.pm";
require "Scripts.pm";
require "AuthorSQL.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";
require "Sorts.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI -> connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

GetInstitutions();
GetAuthors();

print $query->header;
DocDBHeader("Add Authors","",-scripts => ["PopUps"]);

print $query -> start_multipart_form('POST',"$AuthorAdd");

print "<table class=\"CenteredTable HighPaddedTable\">\n";

print "<tr>\n";
print "<td colspan=\"3\">\n";
print "<strong>You are about to add an author to the $Project document database.</strong>
Anyone is allowed to add authors. <strong>Please be careful</strong>
and make sure to put the authors first name, last name, and middle initials
(with periods) in the right place. If you make a mistake, <b><span class=\"Warning\">DO
NOT</span></b> enter the author again. Contact an  <a
href=\"mailto:$DBWebMasterEmail\">adminstrator</a> and explain the
problem. Required fields are denoted by $RequiredMark.<br/>\n";

print "<strong>Click on any of the headings for help.</strong>\n"; print "</td>\n";
print "</tr><tr>\n";
print "<td>\n"; InstitutionSelect(-required => $TRUE); print "</td>\n";
print "<td>\n"; NameEntryBox();      print "</td>\n";
print "</tr>\n";
print "</table><p>\n";
print $query -> submit (-value => "Add Author");
print "</p>\n";
print $query -> end_multipart_form;

print "<h3>Existing Authors:</h3>\n";

AuthorsTable();

DocDBNavBar();
DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
