#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;
use DBI;

require "ResponseElements.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";
require "Security.pm";
require "HTMLUtilities.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);

%params = $query -> Vars;

print $query->header;
&BTeVStyle("Author Addition Results");

print "<p><h3>Here are the results of your attempt to add an author
                to the BTeV document database:</h3><p>\n";

my $author_insert = $dbh->prepare(
   "insert into Author ".
          "(AuthorID, FirstName, MiddleInitials, LastName, InstitutionID,Active) ". 
   "values (0,        ?,         ?,              ?,        ?,            1)");
            

@error_stack = ();

$InstitutionID     = $params{inst};
$FirstName = $params{first};
$MiddleInitials  = $params{middle};
$LastName = $params{lastname};
  
if (@error_stack) {
  &EndPage(@error_stack);
}

$author_insert -> execute($FirstName,$MiddleInitials,$LastName,$InstitutionID);
my $AuthorID = $author_insert -> {mysql_insertid}; # Works with MySQL only
                           
print "You were successful. The author you added is number <b>$AuthorID</b><br>\n"; 

print "Add another <a href=AuthorAddForm>author</a>.<br>\n";
print "Return to the <a href=DocumentDatabase>main page</a>.<br>\n";

&DocDBNavBar;
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);

