#! /usr/bin/perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
use DBI;

require "FormElements.pm";
require "Scripts.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetInstitutions;

# %params = $query -> Vars;

# Removed updatedb mode, see note in ProcessDocumentAdd

print $query->header;
&BTeVStyle("Add Authors");

&HelpPopupScript;

print $query -> start_multipart_form('POST',"AuthorAdd");

print "<center><table cellpadding=10>\n";

print "<tr>\n";
print "<td colspan=3>\n";
print "<h4>You are about to add a topic to the BTeV document database. This
function is restricted to administrators only.<br>
If you are not an administrator,
please stop now and ask an administrator to do this for you.<br>\n";

print "Click on any of the headings for help.</h4>\n"; print "</td>\n";
print "</tr><tr valign=top>\n";
print "<td>\n"; &InstitutionSelect;     print "</td>\n";
print "<td>\n"; &NameEntryBox;     print "</td>\n";
print "</tr>\n";
print "</table><p>\n";

print $query -> submit (-value => "Add Author");
print "</center><p>\n";
print $query -> end_multipart_form;

print "<p>\n";

foreach $key (keys %FullTopics) {
  print "$FullTopics{$key} ";
}

&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
