#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2004 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use Benchmark;
use CGI;
use DBI;

$StartTime = new Benchmark;

require "DocDBGlobals.pm";
require "Messages.pm";
require "HTMLUtilities.pm";
require "ResponseElements.pm";
require "Scripts.pm";
require "Security.pm";

require "CertificateUtilities.pm";

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

### Start HTML

print $query->header;
&HelpPopupScript;

&DocDBHeader("Certificate Status and Application");

&EndPage(@ErrorStack);

### Output Information
my $CertificateStatus = &CertificateStatus();
my $CertEmail = $ENV{SSL_CLIENT_S_DN_Email};
my $CertCN    = $ENV{SSL_CLIENT_S_DN_CN};

if ($CertificateStatus eq "verified") {
  print "<b>Your certificate has been verified and you have access to documents from these groups:</b>";
  my @GroupIDs = &FindUsersGroups();
  print "<ul>\n";
  if (@GroupIDs) {
    foreach my $GroupID (@GroupIDs) {
      &FetchSecurityGroup($GroupID);
      print "<li>",$SecurityGroups{$GroupID}{NAME},"</li>\n";
    }
  } else {
    print "<li><b>None.</b> Contact an adminstrator if this is incorrect</li>\n";
  }       
  print "</ul>\n";
} elsif ($CertificateStatus eq "unverified") {  
  print "<b>Your certificate is valid and you have applied for access to documents. 
         If you believe your request has been misplaced or neglected, contact an administator.</b><p/>";
  print "The following information may be helpful:<br>\n";
  print "<b>Certificate Common Name (CN):</b> $CertCN<br>\n";
  print "<b>Certificate E-mail Address:</b> $CertEmail<br>\n";
} elsif ($CertificateStatus eq "mismatch") {  
  print "<b>Your certificate is valid but a similar certificate already exists
         for  either your e-mail address or your name (CN). Only one
         certificate is allowed per person. Contact an administrator if you
         don't know what to do.</b><p/>";
  print "The following information may be helpful:<br>\n";
  print "<b>Certificate Common Name (CN):</b> $CertCN<br>\n";
  print "<b>Certificate E-mail Address:</b> $CertEmail<br>\n";
} elsif ($CertificateStatus eq "nocert") {  
  print "<b>You didn't present a certificate. Not sure if this can happen.</b><p/>";
} elsif ($CertificateStatus eq "noapp") {
  require "SecurityHTML.pm";
  require "FormElements.pm";
  print "<b>Your certificate is valid but you have never applied for access to
         documents.<br/>Fill out the form below to apply for access.</b><p/>";
  print "<center>\n";
  print $query -> start_multipart_form('POST',$UserAccessApply);
  print "<table cellpadding=5>\n";
  print "<tr>\n";
  print "<td valign=top><b>Your name (Certificate CN):</b><br>&nbsp;&nbsp;$CertCN<p/>\n";
  if ($Preferences{Security}{Certificates}{UseCNOnly}) {
    &TextField(-name => "email", -helplink => "email", -helptext => "Your E-mail",
               -size => 20, -maxlength => 64);
  } else {
    print "<b>Your e-mail:</b><br>&nbsp;&nbsp;$CertEmail\n";
  }  
  print "</td>\n";
  print "<td>\n";
  &SecurityScroll(-helplink => "reqgroups", -helptext => "Requested<br/>Groups",
                  -name     => "reqgroups", -multiple => TRUE);
  print "</td></tr>\n";
  print "<tr>\n";
  print "</td></tr>\n";
  print "<tr><td colspan=2>\n";
  &TextArea(-helplink  => "certnote", -helptext => "Notes", 
            -extratext => "(Identify yourself or other notes if needed.)",
            -name      => "certnote");    
  print "</td></tr>";
  print "<tr><td colspan=2 align=center>\n";
  print $query -> submit (-value => "Apply for access");
  print "</td></tr>";
  print "</table>\n";       
  print "</center>\n";
}

&DocDBNavBar();
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
