#! /usr/bin/env perl
#
#        Name: ConferenceAddForm 
# Description: This provides a web form for people to add conferences, a special
#              kind of topic.  
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

# Copyright 2001-2005 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "FormElements.pm";
require "TopicHTML.pm";
require "MeetingHTML.pm";
require "Scripts.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";
require "MiscSQL.pm";
require "TopicSQL.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetTopics;

# %params = $query -> Vars;

# Removed updatedb mode, see note in ProcessDocumentAdd

print $query -> header;
&DocDBHeader("Add a Conference");

&HelpPopupScript;

print $query -> start_multipart_form('POST',"$ConferenceAdd");

print "<center><table cellpadding=10>\n";

print "<tr><td colspan=2>\n";
print "<h4>You are about to add a conference and its associated topic to the
           $Project document database.<br> 
           Check the list below to make sure the conference you want to add
           hasn't been added by someone else.<br>
           If you aren't sure what you are doing, please stop now and ask an 
           administrator to do this for you.<br>\n";

print "Click on any of the headings for help.</h4>\n"; 
print "</td></tr>\n";

print "<tr valign=top>\n";
print "<td>\n"; &ShortDescriptionBox;     print "</td>\n";
print "<td>\n"; &LongDescriptionBox;      print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td>\n"; &LocationBox;          print "</td>\n";
print "<td>\n"; &ConferenceURLBox;     print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td>\n"; &StartDatePullDown;     print "</td>\n";
print "<td>\n"; &EndDatePullDown;       print "</td>\n";
print "</tr>\n";

print "<tr><td colspan=2 align=center>\n";
print $query -> submit (-value => "Add the Conference");
print "</tr>\n";

print "</table><p>\n";

print "</center><p>\n";
print $query -> end_multipart_form;

print "<p>\n";

print "<h3>Existing Conferences:</h3>\n";

&ConferencesList;

&DocDBNavBar();
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
