#! /usr/bin/env perl
#
#        Name: ConferenceAdminister 
# Description: This script is called by EmailAdministerForm and does 
#              administration on conferences. Since conferences are special
#              types of topics, some things can be changed with TopicAdminister
#              but some can only be changed here. Best to just use 
#              ConferenceAdminister.
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

use CGI;
use DBI;

require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "Security.pm";
require "HTMLUtilities.pm";
require "SecuritySQL.pm";
require "Messages.pm";

$query = new CGI;  # Global for subroutines

print $query->header;
&DocDBHeader("Modified E-mail Users");

%params = $query -> Vars;

@ErrorStack = ();
@WarnStack  = ();

# Parameters to script 

my $Password      = $params{password};
my $Username      = $Administrator;
my $Action        = $params{admaction};

#my $EmailUserID   = $params{emailuserid};
#my $NewPassword   = $params{resetpw};

unless (&CanAdminister) {
  push @ErrorStack,$Msg_AdminNoLogin;
}  
&EndPage(@ErrorStack);

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$Username,$Password);

unless ($dbh) {
  push @ErrorStack,$Msg_AdminNoConnect;
}         
&EndPage(@ErrorStack);

&GetSecurityGroups;

if      ($Action eq "Delete") { # Delete user
#  if (!$EmailUserID) {
#    push @ErrorStack,$Msg_ModEUserEmpty;
#  } else {
#    my $UserDelete = $dbh -> prepare("delete from EmailUser where EmailUserID=?");
#       $UserDelete -> execute($EmailUserID);
#
#    my @NotifyTimes = ("Immediate","Daily","Weekly");
#    my @NotifyTypes = ("Author","Keyword","Topic");
#  }
#  print "<b>The User was deleted.</b><p>\n";
} elsif ($Action eq "Modify") { 
#  unless ($EmailUserID) { # Deal with password changes 
#    push @ErrorStack,$Msg_ModEUserEmpty;
#  }
#  &EndPage(@ErrorStack);

#  if ($NewPassword) { 
#    srand (time ^ $$ ^ unpack "%32L*", `ps axww`);
#    my $UserUpdate = $dbh -> prepare("update EmailUser set Password=? where EmailUserID=?");
#       $UserUpdate -> execute($EncryptedPassword,$EmailUserID);
#    print "<b>The User's password was changed. $EmailUserID $EncryptedPassword They should change it again ASAP.</b><p>\n";
#  }
} elsif ($Action eq "New") { 
#  push @ErrorStack,"You can't create new users here. Do it the normal way.";
} else {
  push @ErrorStack,"No valid action was specified.";
}  

print "<p>\n";

&WarnPage(@WarnStack);
&EndPage(@ErrorStack);

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
 
exit;
