#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;
use DBI;

require "DocDBGlobals.pm";
require "Messages.pm";

require "ResponseElements.pm";
require "SecuritySQL.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";
require "TalkSQL.pm";
require "MeetingSQL.pm";

require "FSUtilities.pm";
require "HTMLUtilities.pm";
require "Security.pm";
require "SQLChecks.pm";

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

@ErrorStack = ();
@warn_stack  = ();

$DocumentID    = $params{documentid};
$SessionTalkID = $params{sessiontalkid};

$DocumentID    =~ s/^\s+//; # Remove leading and trailing spaces
$DocumentID    =~ s/\s+$//;
$SessionTalkID =~ s/^\s+//;
$SessionTalkID =~ s/\s+$//;

unless ($DocumentID) {
  push @ErrorStack,"You are must supply a document number!";
}  

unless ($SessionTalkID) {
  push @ErrorStack,"You are must supply a Session Number!";
}  

print $query->header;
print $query->start_html(-title => "Confirming document match");

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);
unless ($dbh) {
  push @ErrorStack,$Msg_NoConnect;
}      
&EndPage(@ErrorStack);

&FetchDocument($DocumentID);
$Version  = $Documents{$DocumentID}{NVersions};
$DocRevID = &FetchRevisionByDocumentAndVersion($DocumentID,$Version);
unless (&CanModify($DocumentID,$Version)) {
  push @ErrorStack,$Msg_DocNoAccess;
}

unless ($DocRevID) { # Probably never executed since CanAccess fails.
  push @ErrorStack,"This document does not exist.";
}

&FetchSessionTalkByID($SessionTalkID);
my $SessionID =  $SessionTalks{$SessionTalkID}{SessionID};
&FetchSessionByID($SessionID);
my $ConferenceID = $Sessions{$SessionID}{ConferenceID};
unless (&CanModifyMeeting($ConferenceID)) {
  push @ErrorStack,$Msg_MeetNoModify;
}

&EndPage(@ErrorStack);

my $SessionTalkUpdate = $dbh -> prepare(
 "update SessionTalk set DocumentID=?, Confirmed=1 where SessionTalkID=?");
$SessionTalkUpdate -> execute($DocumentID,$SessionTalkID);


print "<b>The match has been confirmed.<br>Press the button below to reload the
original page.</b><p>\n";

print "<center><form>\n";
print " <input type=\"button\" value=\"Close Window and Reload\" onClick=\"opener.location.reload(1); window.close()\">\n";
print "</form></center>";

print $query->end_html;     # End page
