#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
use DBI;

require "FormElements.pm";
require "Scripts.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";
require "MiscSQL.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&SpecialMajorTopics;
&GetTopics;
&GetConferences;

# %params = $query -> Vars;

# Removed updatedb mode, see note in ProcessDocumentAdd

print $query->header;
&DocDBHeader("Add a Conference");

&HelpPopupScript;

print $query -> start_multipart_form('POST',"$ConferenceAdd");

print "<center><table cellpadding=10>\n";

print "<tr><td colspan=2>\n";
print "<h4>You are about to add a conference and its associated topic to the
           $Project document database.<br> 
           Check the list below to make sure the conference you want to add
           hasn't been added by someone else.<br>
           If you aren't sure what you are doing, please stop now and ask an 
           administrator to do this for you.<br>\n";

print "Click on any of the headings for help.</h4>\n"; 
print "</td></tr>\n";

print "<tr valign=top>\n";
print "<td>\n"; &ShortDescriptionBox;     print "</td>\n";
print "<td>\n"; &LongDescriptionBox;      print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td>\n"; &LocationBox;          print "</td>\n";
print "<td>\n"; &ConferenceURLBox;     print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td>\n"; &StartDatePullDown;     print "</td>\n";
print "<td>\n"; &EndDatePullDown;       print "</td>\n";
print "</tr>\n";

print "<tr><td colspan=2 align=center>\n";
print $query -> submit (-value => "Add the Conference");
print "</tr>\n";

print "</table><p>\n";

print "</center><p>\n";
print $query -> end_multipart_form;

print "<p>\n";


print "<h3>Existing Conferences:</h3>\n";

&ConferencesTable;

&DocDBNavBar();
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
