#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;
use DBI;

require "ResponseElements.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";
require "Security.pm";
require "HTMLUtilities.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);

%params = $query -> Vars;

print $query->header;
&BTeVStyle("BTeV Conference Addition Results");

print "<p><h3>Here are the results of your attempt to add a conference
                to the BTeV document database:</h3><p>\n";

my $topic_insert = $dbh->prepare(
   "insert into MinorTopic ".
          "(MinorTopicID, MajorTopicID, ShortDescription, LongDescription) ". 
   "values (0,            ?,            ?,                ?)");

my $conference_insert = $dbh->prepare(
   "insert into Conference ".
          "(ConferenceID, MinorTopicID, Location, URL, StartDate, EndDate) ". 
   "values (0,            ?,            ?,        ?,   ?,         ?)");

@error_stack = ();

my $MajorTopicID     = &LookupMajorTopic("Conferences"); 
my $ShortDescription = $params{short};
my $LongDescription  = $params{long};
my $Location         = $params{location};
my $URL              = $params{url};

my $Startday   = $params{startday};
my $Startmonth = $params{startmonth};
my $Startyear  = $params{startyear};

my $Endday     = $params{endday};
my $Endmonth   = $params{endmonth};
my $Endyear    = $params{endyear};

my $StartDate = "$Startyear-$ReverseAbrvMonth{$Startmonth}-$Startday";
my $EndDate   = "$Endyear-$ReverseAbrvMonth{$Endmonth}-$Endday";

if (@error_stack) {
  &EndPage(@error_stack);
}

$topic_insert -> execute($MajorTopicID,$ShortDescription,$LongDescription);
my $MinorTopicID = $topic_insert -> {mysql_insertid}; # Works with MySQL only
if ($MinorTopicID) {
  $conference_insert -> execute($MinorTopicID,$Location,$URL,
                                $StartDate,$EndDate); 
}                   
if ($MinorTopicID) {
  print "You were successful. The topic you added is number <b>$MinorTopicID</b><br>\n"; 
} else {
  print "Something went wrong. Make sure you did everything right. If the
         problem still exists, contact an administrator.\n"; 
}

&DocDBNavBar("Add&nbsp;Topic",$TopicAddForm);
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);

