#! /usr/bin/env perl
#
# Description: Called by ConferenceAddForm, adds conference info into the DB
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

# Copyright 2001-2005 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use CGI;
use DBI;
use Time::Local;

require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "TopicSQL.pm";
require "Security.pm";
require "HTMLUtilities.pm";
require "WebUtilities.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);
  
&SpecialMajorTopics;

%params = $query -> Vars;

print $query->header;
&DocDBHeader("$Project Conference Addition Results");

print "<p><h3>Here are the results of your attempt to add a conference
                to the $Project document database:</h3><p>\n";

my $topic_insert = $dbh->prepare(
   "insert into MinorTopic ".
          "(MinorTopicID, MajorTopicID, ShortDescription, LongDescription) ". 
   "values (0,            ?,            ?,                ?)");

my $conference_insert = $dbh->prepare(
   "insert into Conference ".
          "(ConferenceID, MinorTopicID, Location, URL, StartDate, EndDate) ". 
   "values (0,            ?,            ?,        ?,   ?,         ?)");

@ErrorStack = ();
@WarnStack = ();

my ($MajorTopicID)   = @ConferenceMajorIDs; 
my $ShortDescription = $params{short};
my $LongDescription  = $params{long};
my $Location         = $params{location};
my $URL              = $params{url};

my $Startday   = $params{startday};
my $Startmonth = $params{startmonth};
my $Startyear  = $params{startyear};

my $Endday     = $params{endday};
my $Endmonth   = $params{endmonth};
my $Endyear    = $params{endyear};

my $StartDate = "$Startyear-$ReverseAbrvMonth{$Startmonth}-$Startday";
my $EndDate   = "$Endyear-$ReverseAbrvMonth{$Endmonth}-$Endday";

my $StartTime = timelocal(0,0,0,$Startday,$ReverseAbrvMonth{$Startmonth}-1,$Startyear);
my $EndTime   = timelocal(0,0,0,$Endday,$ReverseAbrvMonth{$Endmonth}-1,$Endyear);

# Check inputs

unless ($ShortDescription && $LongDescription && $Location) {
  push @ErrorStack,"You must fill in all the fields.";
}

if ($URL) {
  unless (&ValidURL($URL)) {
    push @ErrorStack,"The URL $URL is not valid.";
  }
} else {
  push @WarnStack,"No URL was supplied for this conference. If this was a
  mistake, do not re-enter the conference. Contact an adminstrator.";
}  

unless ($EndTime && &ValidDate($Endday,$ReverseAbrvMonth{$Endmonth},$Endyear)) {
  push @ErrorStack,"The ending date is not valid.";
}
  
unless ($StartTime && &ValidDate($Startday,$ReverseAbrvMonth{$Startmonth},$Startyear)) {
  push @ErrorStack,"The starting date is not valid.";
}

if ($StartTime > $EndTime) {
  push @ErrorStack,"The starting date is after the ending date.";
}
  
if (@ErrorStack) {
  &EndPage(@ErrorStack);
}
if (@WarnStack) {
  &WarnPage(@WarnStack);
}

$topic_insert -> execute($MajorTopicID,$ShortDescription,$LongDescription);
my $MinorTopicID = $topic_insert -> {mysql_insertid}; # Works with MySQL only
if ($MinorTopicID) {
  $conference_insert -> execute($MinorTopicID,$Location,$URL,
                                $StartDate,$EndDate); 
}                   
if ($MinorTopicID) {
  print "You were successful. The topic you added is number <b>$MinorTopicID</b><br>\n"; 
} else {
  print "Something went wrong. Make sure you did everything right. If the
         problem still exists, contact an administrator.\n"; 
}

&DocDBNavBar("Add&nbsp;Conference",$ConferenceAddForm);
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);

