#! /usr/bin/env perl
#
#        Name: CustomListForm
# Description: Allow users, admins, and meeting organizers to change how various
#              lists of documents and agendas are displayed in DocDB 
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

# Copyright 2001-2005 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


use CGI qw(-nosticky);
use DBI;

require "DocDBGlobals.pm";
require "AdministerElements.pm";
require "ResponseElements.pm";
require "FormElements.pm";
require "Scripts.pm";
require "Security.pm";
require "Messages.pm";
require "Sorts.pm";
require "Fields.pm";

require "DBUtilities.pm";
require "HTMLUtilities.pm";

require "MeetingSQL.pm";
require "SecuritySQL.pm";
require "ConfigSQL.pm";

require "DocumentHTML.pm";
require "TopicHTML.pm"; 
require "MeetingHTML.pm"; 

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

my $EventGroupID     = int($params{eventgroupid}); # Make arrays
my $EventID          = int($params{eventid});      # Make arrays
my $Default          = int($params{defaultlists}); # Make arrays
$Default = 1; # FIXME

my $MaxFields = 15;

$query -> delete_all();

CreateConnection(-type => "rw");

EndPage(-startpage => $TRUE);

GetConferences();
GetAllEventGroups();
GetSecurityGroups();

# Setup disabled correctly

my $AllowEvents = 0;
if (CanCreate()) {
  $AllowEvents = 1;
}  

my %FieldList = ();
foreach my $FieldCount (1..$MaxFields) {
  my $Field = $params{"field$FieldCount"};
  push @DebugStack,"$FieldCount $Field";
  if ($Field && $Field ne "xxxx") {
    push @DebugStack,"Field $Field added to the display for ";
    push @ActionStack,"Field $Field added to the display for ";
    $FieldList{$Field}{Row}     = $params{"row$FieldCount"};
    $FieldList{$Field}{Column}  = $params{"col$FieldCount"};
    $FieldList{$Field}{RowSpan} = $params{"rowspan$FieldCount"};
    $FieldList{$Field}{ColSpan} = $params{"colspan$FieldCount"};
  }
}

InsertCustomFieldList(-default => 1,-fieldlist => \%FieldList); 

print $query->header;
DocDBHeader("Customize Document Lists","",-scripts => ["PopUps","CustomListDisable"]); 
EndPage();
print $query -> start_multipart_form('POST',$CustomListForm);

print q{<table class="MedPaddedTable">
        <tr>
        <td colspan="2">
        <strong>
        This page allows you to change what information about documents is 
        displayed in various parts of DocDB. You can choose to change the information
        just for yourself (you must allow cookies in your browser) or for everyone if 
        your access level is high enough. As a normal user, you may only change the 
        display of events you may modify. For other changes that affect all users, 
        please contact an administrator.   
        </strong>
        </td>
        </tr>
        <tr>
        <td colspan="2">
       };

# Scope limiter which is hooked to JS

my %Scope = ();
$Scope{All}  = "For Everyone";
$Scope{User} = "Only for me";
print FormElementTitle(-helplink => "fieldscope", -helptext => "Scope of Changes");
print $query -> radio_group(-name    => "scope",  -values   => \%Scope, 
                            -default => "User",   -onclick  => "disabler_customlist($AllowEvents);");

print "</td></tr><tr><td>";

# Predefined lists

my @FieldLists = keys %DefaultFieldLists;
print FormElementTitle(-helptext => "Predefined Lists", -helplink => "definedfieldlists");
print $query -> scrolling_list(-name     => "defaultlists", -values => \@FieldLists, 
                               -size     => 10, -multiple => $Multiple);  

print "</td><td>\n";

# Topics (which might be left off for the moment)

TopicScroll(-helptext => "Minor Topics", -helplink => "topics"); 
print "</td></tr>\n";
print "<tr><td>";

# Event groups and events. Put default here if they've followed the right link.

EventGroupSelect();
print "</td><td>\n";
EventSelect();
print "</td></tr>\n";

print q{</table>};

print q{<table class="MedPaddedTable">};

foreach my $Partition (1..$MaxFields) {
  FieldListChooser(-partition => $Partition);
}

print q{<tr><td colspan="5" class="SubmitCell">};
 print $query -> submit (-value => "Change Display of Fields");
print "</td></tr>\n";

print q{</table>};
print $query -> end_multipart_form;

DocDBNavBar();
DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
