#! /usr/bin/env perl
#
# Description: Displays the document to be deleted and requests the 
#              admin password. Calls DeleteDocument to delete the doc. 
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

use CGI;
use DBI;

require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "Security.pm";
require "SecuritySQL.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";

require "HTMLUtilities.pm";
require "Security.pm";


$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

$DocumentID = $params{docid};
$DocumentID =~ s/^\s+//; # Remove leading and trailing spaces
$DocumentID =~ s/\s+$//;

@error_stack = ();

unless ($DocumentID) {
  push @error_stack,"You are must supply a document number to delete.";
}  
unless (&CanAdminister) {
  push @error_stack,"You must be logged in as the adminstrator to delete
  documents";
}  
  
if (@error_stack) {
  &EndPage(@error_stack);
}

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);
&GetSecurityGroups;
&FetchDocument($DocumentID);

$Version = $Documents{$DocumentID}{NVER}; # Show latest version

print $query->header;
&DocDBHeader("Confirm Deletion of Document $DocumentID");

my $DocRevID   = &FetchRevisionByDocumentAndVersion($DocumentID,$Version);

unless ($DocRevID) {
  push @error_stack,"This document does not exist.";
}

if (@error_stack) {
  &EndPage(@error_stack);
}

print "<p><center><b>To delete this document, you must supply the adminstrator 
          password:</b>";

print $query -> startform('POST',$DeleteDocument);
print "<b> Administrator password: </b>"; 
print $query -> password_field(-name => "password", -size => 12, -maxlength => 12);
print $query -> hidden(-name => 'docid',    -default => $DocumentID);
print "<b> </b>"; 
print $query -> submit (-value => "Delete Document");
print $query -> endform;

print "</center><p>";

&PrintRevisionInfo($DocRevID,1);

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
