#! /usr/bin/env perl
#
# Description: Displays the document to be deleted and requests the 
#              admin password. Calls DeleteDocument to delete the doc. 
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

# Copyright 2001-2006 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CGI;
use DBI;

require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "Security.pm";
require "SecuritySQL.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";

require "HTMLUtilities.pm";
require "AdministerElements.pm";
require "Security.pm";

require "RevisionHTML.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetSecurityGroups;

%params = $query -> Vars;

$DocumentID = $params{docid};
$DocumentID =~ s/^\s+//; # Remove leading and trailing spaces
$DocumentID =~ s/\s+$//;

@ErrorStack = ();

unless ($DocumentID) {
  push @ErrorStack,"You are must supply a document number to delete.";
}  
unless (&CanAdminister) {
  push @ErrorStack,"You must be logged in as the adminstrator to delete
  documents";
}  
  
EndPage(@ErrorStack);

&GetSecurityGroups;
&FetchDocument($DocumentID);

$Version = $Documents{$DocumentID}{NVersions}; # Show latest version

print $query->header;
&DocDBHeader("Confirm Deletion of Document $DocumentID");

my $DocRevID   = &FetchRevisionByDocumentAndVersion($DocumentID,$Version);

unless ($DocRevID) {
  push @ErrorStack,"This document does not exist.";
}

EndPage(@ErrorStack);

print "<p><center><b>To delete this document, you must supply the adminstrator 
          username and password:</b>";

print $query -> startform('POST',$DeleteDocument);
&AdministratorPassword;
print $query -> hidden(-name => 'docid',    -default => $DocumentID);
print "<b> </b>"; 
print $query -> submit (-value => "Delete Document");
print $query -> endform;

print "</center><p>";

&PrintRevisionInfo($DocRevID,1);

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
