#! /usr/bin/env perl
#
#        Name: DocDBHelp
# Description: Usually called as a pop-up, this looks up in docdb.hlp
#              the information on a specific topic.
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified:

# Copyright 2001-2018 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CGI;
use CGI::Untaint;
use XML::Simple;

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "UntaintInput.pm";

if (-e "ProjectHelp.xml") {
  $ProjectHelp = 1;
}

# Start page

$query = new CGI;
$query -> autoEscape(0);
my $Untaint = CGI::Untaint -> new($query -> Vars);
print $query -> header( -charset => $HTTP_ENCODING );
&DocDBHeader("$Project DocDB Help","",-nobody => $TRUE);

$helpterm = $Untaint -> extract(-as_safehtml => "term") || "";

push @DebugStack, "Looking for help on $helpterm";

my ($DefaultText, $DefaultTitle, $ProjectText, $ProjectTitle, $Action);

# Parse XML into hashes, pull out desired text

my $HelpXML = XMLin("DocDBHelp.xml");

$DefaultText = $HelpXML->{entry}{$helpterm}->{text};
$DefaultTitle = $HelpXML->{entry}{$helpterm}->{title};

if ($ProjectHelp) {
  my $ProjectXML = XMLin("ProjectHelp.xml");

  $ProjectText = $ProjectXML->{entry}{$helpterm}->{text};
  $ProjectTitle = $ProjectXML->{entry}{$helpterm}->{title};
  $Action = $ProjectXML->{entry}{$helpterm}->{action};
}

# Remove line breaks and XML element tags

$DefaultText =~ s/&#10;/ /g;
$ProjectText =~ s/&#10;/ /g;
$DefaultText =~ s/<text>//g;
$ProjectText =~ s/<text>//g;
$DefaultText =~ s/<\/text>//g;
$ProjectText =~ s/<\/text>//g;

# Print out help for user

if ($DefaultText || $ProjectText) {
  if ($Action eq "append" || !$Action) {
    print "<b><big>$DefaultTitle:</big></b><p>\n";
    print $DefaultText;
    print $ProjectText;
    print "\n";
  } elsif ($Action eq "prepend") {
    print "<b><big>$ProjectTitle:</big></b><p>\n";
    print $ProjectText;
    print $DefaultText;
    print "\n";
  } elsif ($Action eq "replace") {
    print "<b><big>$ProjectTitle:</big></b><p>\n";
    print $ProjectText;
    print "\n";
  }
} else {
  print "<b><big>No help available on this topic.</big></b><p>\n";
}

DocDBFooter($DBWebMasterEmail,$DBWebMasterName,-nobody => $TRUE);
