#! /usr/bin/env perl
#
# Description: The instructions for DocDB. This is mostly HTML, but making 
#              it a script allows us to eliminate parts of it that we don't want
#              and get it following everyone's style, and allows groups to add
#              to it with ProjectMessages.
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 

# Copyright 2001-2005 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use CGI;                                                      
use DBI;                                                      

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "ProjectMessages.pm";
require "SecuritySQL.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetSecurityGroups;

%params = $query -> Vars; 
$InstructionSet = $params{set} || "general";

# Title

my $PageTitle = "";
my $HTMLTitle = "";
if ($InstructionSet eq "general") {
  $PageTitle = "DocDB Instructions";
  $HTMLTitle = "$Project DocDB Instructions";
} elsif ($InstructionSet eq "event") {
  $PageTitle = "Event Manager";
  $HTMLTitle = "Event Manager and Calendar Instructions";
}
print $query->header(-charset => "utf-8");
&DocDBHeader($HTMLTitle,$PageTitle);

print "<div id=\"DocDBHomeBody\">\n";

### Header info

print "<div id=\"Header3Col\">\n";
print "</div>\n";  # Header3Col

### Left Column

print "<div id=\"LeftColumn3Col\">\n";
if ($InstructionSet eq "general") {
  require "GeneralInstructions.pm";
  &GeneralInstructionsSidebar;
} elsif ($InstructionSet eq "event") {
  require "EventInstructions.pm";
  &EventInstructionsSidebar;
}
print "</div>\n";  # LeftColumn3Col

### Main Column

print "<div id=\"MainColumn3Col\">\n";
if ($InstructionSet eq "general") {
  require "GeneralInstructions.pm";
  &GeneralInstructionsBody;
} elsif ($InstructionSet eq "event") {
  require "EventInstructions.pm";
  &EventInstructionsBody;
}

### Right column (wrapped around by middle column)

#print "<div id=\"RightColumn3Col\">\n";
#print "</div>\n";  # RightColumn3Col

print "</div>\n";  # MainColumn3Col

print "<div id=\"Footer3Col\">\n"; # Must have to keep NavBar on true bottom
print "</div>\n";  # Footer3Col
print "</div>\n";  # DocDBHomeBody

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
