#! /usr/bin/env perl
#
# Description: Usually called as a pop-up, this looks up in docdb.hlp
#              the information on a specific topic. 
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#       FIXME: Think about XML and project/global help files

use CGI;                                                                                      
require "DocDBGlobals.pm";

# Start page

$query = new CGI;  
print $query->header;
print $query->start_html(-title=>"$Project Document Database Help");

open HELPFILE,"$help_file"; # Read in .hlp file

while (<HELPFILE>) {
  $key  = $_;
  $name = <HELPFILE>;
  chomp $key;
  chomp $name;
  $help{NAME}{$key} = $name;
  while (<HELPFILE>) {
    if ($_ eq "#\n") {last;}
    $help{TEXT}{$key} .= $_;
  }
}

close HELPFILE;     

%params = $query -> Vars;
$helpterm = $params{term};   # Extract term user wants help for

# Write content
if ($help{NAME}{$helpterm}) {
  print "<b><big>$help{NAME}{$helpterm}:</big></b><p>\n";
  print "$help{TEXT}{$helpterm}\n";
} else {
  print "<b><big>No help available on this topic.</big></b><p>\n";
}  
print $query->end_html;     # End page

