#! /usr/bin/env perl
#
# Description: The Document Database homepage. Give the user various ways to  
#              view documents, a link to ways to change documents, and a list 
#              of the most recently updated documents.
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 

# Copyright 2001-2005 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use CGI;                                                      
use DBI;                                                      

require "DocDBGlobals.pm";
require "ProjectMessages.pm";

#$query = new CGI;  # Global for subroutines
#$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);
#&GetSecurityGroups;

# %params = $query -> Vars;  # No parameters (yet?) 

print $query->header;
&DocDBHeader("$Project DocDB Instructions","DocDB Instructions");

print "<div id=\"DocDBHomeBody\">\n";

### Header info

print "<div id=\"Header3Col\">\n";

print "</div>\n";  # Header3Col

### Left Column

print "<div id=\"LeftColumn3Col\">\n";


print "</div>\n";  # LeftColumn3Col

### Main Column

print "<div id=\"MainColumn3Col\">\n";

 
### Right column (wrapped around by middle column)

#print "<div id=\"RightColumn3Col\">\n";
#print "</div>\n";  # RightColumn3Col

print "</div>\n";  # MainColumn3Col

print "<div id=\"Footer3Col\">\n"; # Must have to keep NavBar on true bottom
print "</div>\n";  # Footer3Col
print "</div>\n";  # DocDBHomeBody


&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
