#! /usr/bin/perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
use DBI;

require "FormElements.pm";
require "Scripts.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";
require "ResponseElements.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);

&GetAuthors;
&GetTopics;
&GetSecurities;

%params = $query -> Vars;
$mode   = $params{mode};
if ($mode ne "add" && $mode ne "reserve" && $mode ne "update") {
  $mode = "reserve";
}  
$upload = $params{upload};
if ($upload ne "http" && $upload ne "file") {
  $upload = "file";
}  

print $query->header;
if      ($mode eq "add") {
  print $query->start_html(-title=>"BTeV Document Addition");
} elsif ($mode eq "reserve") {
  print $query->start_html(-title=>"BTeV Document Reservation");
} elsif ($mode eq "update") {
  print $query->start_html(-title=>"BTeV Document Update");
}
my $DocumentID;
if ($mode eq "update") { # Need to read in last version values and update
#  $documentID = $params{docid};
  $DocumentID = 78;
  &FetchDocument($DocumentID);
  my $DocRevID = &FetchDocRevision($DocumentID,$Documents{$DocumentID}{NVER});
  
  @SecurityDefaults = $DocRevisions{$DocRevID}{SECURITY};
  $TitleDefault = $DocRevisions{$DocRevID}{TITLE};
  $PubInfoDefault = $DocRevisions{$DocRevID}{PUBINFO};
  $AbstractDefault = $DocRevisions{$DocRevID}{ABSTRACT};
  $RequesterDefault = $DocRevisions{$DocRevID}{SUBMITTER};
  @AuthorDefaults   = &GetRevisionAuthors($DocRevID);
  @TopicDefaults   = &GetRevisionTopics($DocRevID);
}

&HelpPopupScript;

print $query -> start_multipart_form('POST',$ProcessDocumentAdd);
print $query -> hidden(-name => 'mode',   -default => 'reserve');
print $query -> hidden(-name => 'upload', -default => 'file');

print "<center><table cellpadding=10>\n";

print "<tr>\n";
print "<td colspan=3>\n";
if      ($mode eq "add") {
  print "<h4>You have chosen to add a new document to the database.<br> 
             Make sure you know all the required information and
             the file is ready for uploading.<br>\n";
} elsif ($mode eq "reserve") {
  print "<h4>You have chosen to reserve a new document document number in 
             the database. <br>
             You CANNOT upload the document using this form.<br>
             Make sure you know all the required information.<br>\n";
} elsif ($mode eq "update") {
  $documentName = &FullDocumentID($DocumentID);
  print "<h4>You have chosen to update $documentName.
             Make sure you know all the required information.<br>\n";
}

print "Click on any of the headings for help.</h4>\n"; print "</td>\n";
print "</tr><tr>\n";
print "<td colspan=3>\n"; &TitleBox;    print "</td>\n";
print "</tr><tr>\n";
print "<td colspan=3>\n"; &PubInfoBox;  print "</td>\n";
print "</tr><tr>\n";
print "<td colspan=3>\n"; &AbstractBox; print "</td>\n";
print "</tr>\n";

if ($mode eq "add" || $mode eq "update") {
  print "<tr><td colspan=3>\n";
  if ($upload eq "file") {
    &SingleUploadBox;
  } elsif ($upload eq "http") {
    &SingleHTTPBox;
  }  
  print "</td></tr>";
}

print "<tr>\n";
print "<td>\n"; &RequesterSelect; print "</td>\n";
print "<td>\n"; &AuthorSelect;    print "</td>\n";
print "<td>\n"; &TopicSelect;     print "</td>\n";
print "</tr><tr>\n";
print "<td colspan=1 valign=top>\n"; &SecurityList; print "</td>\n";

if ($mode eq "add" || $mode eq "reserve") {
  print "<td colspan=2 valign=top>\n";
  &DocTypeButtons;
  print "</td>\n";
}

print "</tr>\n";
print "</table><p>\n";

if      ($mode eq "add") {
  print $query -> submit (-value => "Submit document");
} elsif ($mode eq "reserve") {
  print $query -> submit (-value => "Request document ID");
} elsif ($mode eq "update") {
  print $query -> submit (-value => "Update document");
}
print "</center><p>";
print $query -> end_multipart_form;

print $query->end_html; 
