#! /usr/bin/perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
use DBI;

require "FormElements.pm";
require "Scripts.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);

&GetAuthors;
&GetTopics;
&GetSecurities;

%params = $query -> Vars;
$mode = $params{mode};
if ($mode ne "add" && $mode ne "reserve") {
  $mode = "reserve";
}  

print $query->header;
if      ($mode eq "add") {
  print $query->start_html(-title=>"BTeV Document Addition");
} elsif ($mode eq "reserve") {
  print $query->start_html(-title=>"BTeV Document Reservation");
}

&HelpPopupScript;

print $query -> start_multipart_form('POST','ProcessDocumentAdd');
print $query -> hidden(-name => 'mode', -default => 'reserve');

print "<center><table cellpadding=10>\n";

print "<tr>\n";
print "<td colspan=3>\n";
if      ($mode eq "add") {
  print "<h4>You have chosen to add a new document to the database.<br> 
             Make sure you know all the required information and
             the file is ready for uploading.<br>\n";
} elsif ($mode eq "reserve") {
  print "<h4>You have chosen to reserve a new document document number in 
             the database. <br>
             You CANNOT upload the document using this form.<br>
             Make sure you know all the required information.<br>\n";
}
print "Click on any of the headings for help.</h4>\n";
print "</td></tr>\n";
print "<tr>\n";
print "<td colspan=3>\n";
&TitleBox;
print "</td></tr>\n";
print "<tr>\n";
print "<td colspan=3>\n";
&PubInfoBox;
print "</td></tr>\n";
print "<tr>\n";
print "<td colspan=3>\n";
&AbstractBox;
print "</td></tr>\n";
if ($mode eq "add") {
  print "<td colspan=3>\n";
  &SingleUploadBox;
  print "</td></tr>";
  print "<tr><th colspan=3>or</th></tr>\n";
  print "<td colspan=3>\n";
  &SingleHTTPBox;
  print "</td></tr>";
}
print "<tr>\n";
print "<td>\n";
&RequestorSelect;
print "</td>\n";
print "<td>\n";
&AuthorSelect;
print "</td>\n";
print "<td>\n";
&TopicSelect;
print "</td></tr>";
print "<tr>\n";
print "<td colspan=1 valign=top>\n";
&SecurityList;
print "<td colspan=2 valign=top>\n";
&DocTypeButtons;
print "</td>";
print "</td></tr>";
print "</table><p>";


if      ($mode eq "add") {
  print $query -> submit (-value => "Submit document");
} elsif ($mode eq "reserve") {
  print $query -> submit (-value => "Request document ID");
}
print "</center><p>";
print $query -> end_multipart_form;

print $query->end_html; 
