#! /usr/bin/perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
require "DocDBGlobals.pm";
require "HTMLUtilities.pm";

$query = new CGI;  # Global for subroutines
print $query->header;
&BTeVHeader("BTeV Document Database","Document Database");

# %params = $query -> Vars;  # No parameters (yet) 

print "Welcome to the homepage for the BTeV Document Database. From here you
       have several options:\n";
print "<ul>\n";
print "<li><a href=\"$DocumentAddForm\">Reserve</a> a document number\n"; 
print "(used if you don't yet have a first draft of your document).\n";
print "<li><a href=\"$DocumentAddForm?mode=add\">Upload</a> a document you have on your local filesystem\n"; 
print "(no need to reserve the document).\n";
print "<li><a href=\"$DocumentAddForm?mode=add&upload=http\">Submit a URL</a>
for a document you have on the web \n"; 
print "(no need to reserve the document).\n";
print "<li><a href=ListDocuments>List</a> all documents\n"; 
print $query -> start_multipart_form('POST',$ShowDocument);
print "<li>Show document # "; 
print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
print " "; 
print $query -> submit (-value => "Execute");
print $query -> endform;
print "</ul>\n";
print "<p>\n";

print "If the above choices don't satisfy your needs, use this form to generate
       a customized document creation or update form:<p>\n";

$modes{reserve}  = "Reserve document number";
$modes{add}      = "New document";
$modes{update}   = "Update existing document";
$modes{updatedb} = "Update DB information";  # See note in ProcessDocumentAdd

$uploads{http}   = "HTTP submission";
$uploads{file}   = "Local file upload";

$archives{multi}   = "Single file";
$archives{singe}   = "Archive (multi-file) upload";

$topicmodes{multi}  = "Multiple Topic Boxes";
$topicmodes{single} = "Single Topic List";


print $query -> start_multipart_form('POST',$DocumentAddForm);

print "<b>Type of modification: </b>\n";
print $query -> radio_group(-name => "mode", -values => \%modes);
print "<p>\n";
print "<b>Document to update (if applicable): </b>\n";
print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
print "<p>\n";
print "<b>Upload method: </b>\n";
print $query -> radio_group(-name => "upload", -values => \%uploads);
print "<p>\n";
print "<b>Topic Selection: </b>\n";
print $query -> radio_group(-name => "topicmode", -values => \%topicmodes);
print "<p>\n";
print "<b>Upload type (not implemented): </b>\n";
print $query -> radio_group(-name => "archive", -values => \%archives);
print "<p>\n";
print "<b>Number of upload fields (not implemented): </b>\n";
print $query -> textfield(-name => "numfile", -size => 2, -maxlength => 2);
print "<p>\n";
print "<b>Override submit date (not implemented): </b>\n";
print $query -> checkbox(-name => "overdate", -label => 'Check for yes');
print "<p>\n";

print $query -> submit (-value => "Give me the form");
print $query -> endform;

print "<p>Administration functions:<ul>\n";
print "<li>Add a <a href=\"TopicAddForm\">topic</a>\n";
print "<li>Add an <a href=\"AuthorAddForm\">author</a>\n";
print "<li>Eric's <a href=\"http://www.hep.vanderbilt.edu/~vondo/btev-private/DocDB-ToDo.html\">To do list</a> for the database \n";
print "</ul>\n";

&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);

