#! /usr/bin/env perl
#
# Description: The Document Database homepage. Give the user various ways to  
#              view documents, a link to ways to change documents, and a list 
#              of the most recently updated documents.
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 

# Copyright 2001-2004 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use Benchmark;
use CGI;                                                      
use DBI;                                                      

$StartTime = new Benchmark;

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "SecuritySQL.pm";
require "Security.pm";
require "Scripts.pm";
require "ResponseElements.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";
require "Sorts.pm";

require "ProjectMessages.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);
&GetSecurityGroups;

# %params = $query -> Vars;  # No parameters (yet?) 

print $query->header;
&DocDBHeader("$Project Document Database","Document Database");

&HelpPopupScript;

if ($UserValidation eq "certificate") {
  require "CertificateUtilities.pm";
  my $CertificateStatus = &CertificateStatus();
  unless ($CertificateStats eq "verified") {
    
  print "<p><center><h4><font color=\"red\">\n";
  print "You have presented a valid certificate, but are not yet authorized to access the DocDB.\n";
  print "</font>\n";
  print "<a href=\"$CertificateApplyForm\">Apply for access or get more information.</a></h4></center>\n";
}  

if ($WelcomeMessage) {
  print "<p><center><h4>\n";
  print "$WelcomeMessage\n";
  print "</h4></center>\n";
}

print "<p><h4>Database options:</h4>\n";

# Fill arrays with stuff that goes in main, bold table

my @MainFirstColumn  = ();
my @MainOtherColumns = ();

unless ($Public || !&CanCreate()) {
  push @MainFirstColumn,"<b><a href=\"$ModifyHome\">Create or change</a> documents or metadata</b>";
}
push @MainFirstColumn,"<b><a href=\"$SearchForm\">Search</a> documents</b>"; 

my $ShowForm  = $query -> startform('POST',$ShowDocument);
   $ShowForm .= "&bull;&nbsp;";
   $ShowForm .= $query -> submit (-value => "Show");
   $ShowForm .= " <b>$ShortProject-doc-#</b> "; 
   $ShowForm .= $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
   $ShowForm .= " <b>-v</b> "; 
   $ShowForm .= $query -> textfield(-name => "version", -size => 3, -maxlength => 3);
   $ShowForm .= $query -> endform;

push @MainFirstColumn,$ShowForm; 
push @MainFirstColumn,"<b>List documents:</b>";

unless ($Public) {
  push @MainOtherColumns,"<b><a href=\"$HelpFile\">Get instructions</a></b>";
  push @MainOtherColumns,"<b><a href=\"$SelectPrefs\">Set preferences</a></b>";
  push @MainOtherColumns,"<b><a href=\"$EmailLogin\">Setup/manage a personal account</a></b>";
  push @MainOtherColumns,"<b><a href=\"$Statistics\">Get statistics</a></b>";
}
push @MainOtherColumns,@MainPageAddendum;

my $Rows = scalar(@MainFirstColumn);
my $Cols = int((scalar(@MainOtherColumns) - 1)/scalar(@MainFirstColumn) + 1);

# Display main table

print "<table cellspacing=15 width=90%>\n";

for (my $Index = 0; $Index < $Rows; ++$Index) {
  print "<tr>\n";
  print "<td>";
  unless (grep /\&bull/,$MainFirstColumn[$Index]) {
    print "&bull;&nbsp;";
  }  
  print $MainFirstColumn[$Index],"</td>\n";
  for (my $ColIndex = 0; $ColIndex < $Cols; ++$ColIndex) {
    unless ($Index+$ColIndex*$Rows >= scalar(@MainOtherColumns)) {
      print "<td>&bull;&nbsp;",$MainOtherColumns[$Index+$ColIndex*$Rows],"</td>\n";
    }  
  }  
  print "</tr>\n";
}    

++$Cols;

print "<tr><td colspan=$Cols>\n"; # List of lists spans whole bottom of main table

# Fill arrays that print lists of documents

my @FirstColumn  = ();
my @OtherColumns = ();
my @Spanners     = ();

push @FirstColumn,"by <a href=\"$ListAuthors\">author</a>";
push @FirstColumn,"by <a href=\"$ListTopics\">topic</a>";
push @FirstColumn,"by <a href=\"$ListKeywords\">keyword</a>";
push @FirstColumn,"modified in the <a href=\"$LastModified?days=$LastDays\">last $LastDays days</a>";

unless ($Public) {
  push @OtherColumns,"from <a href=\"$ListMeetings\">collaboration meetings</a>";
}
push @OtherColumns,"from <a href=\"$ListByTopic?major=Conferences&mode=conference\">conferences</a>";
unless ($Public && !$PublicAccess{MeetingList}) {
  push @OtherColumns,"from <a href=\"$ListAllMeetings\">all meetings</a>";
}  
if ($UseSignoffs && (!$Public || $PublicAccess{MeetingList})) {
  push @OtherColumns,"all <a href=\"$ListManagedDocuments\">managed documents</a>";
}
  
push @OtherColumns,"<a href=\"$web_root/Static/Lists/$remote_user/FullList.html\">all documents</a>";

push @Spanners,@MultiColumnDocumentLists;

my $Rows = scalar(@FirstColumn);
my $Cols = int((scalar(@OtherColumns) - 1)/scalar(@FirstColumn) + 1);

# Print table for lists of documents

print "<table cellpadding=5>\n";

for (my $Index = 0; $Index < $Rows; ++$Index) {
  print "<tr>\n";
  print "<td>&nbsp;&loz;&nbsp;",$FirstColumn[$Index],"</td>\n";
  for (my $ColIndex = 0; $ColIndex < $Cols; ++$ColIndex) {
    unless ($Index+$ColIndex*$Rows >= scalar(@OtherColumns)) {
      print "<td>&nbsp;&loz;&nbsp;",$OtherColumns[$Index+$ColIndex*$Rows],"</td>\n";
    }  
  }  
  print "</tr>\n";
}    

++$Cols;

foreach my $Spanner (@Spanners) {
  print "<tr>\n";
  print "<td colspan=$Cols>&nbsp;&loz;&nbsp;",$Spanner,"</td>\n";
  print "</tr>\n";
}    

print "</table><p>\n";
 
print "</td>\n";
print "</tr></table>\n";

# Modified in last few days

$Days = $HomeLastDays;

my $document_list = $dbh -> prepare(
   "select DISTINCT(DocumentID) from DocumentRevision where TO_DAYS(NOW()) - TO_DAYS(TimeStamp) <= ?"); 
$document_list -> execute($Days);
$document_list -> bind_columns(undef, \($DocumentID));

my @AllDocumentIDs = ();
while ($document_list -> fetch) {
  push @AllDocumentIDs,$DocumentID;
}

### Get list of documents and read in the information we need from database

my @DocumentIDs = ();
foreach my $DocumentID (@AllDocumentIDs) { # For shorter lists
  &FetchDocument($DocumentID);
  unless (&LastAccess($DocumentID) == -1) {;
    push @DocumentIDs,$DocumentID;
    &FetchRevisionByDocumentAndVersion($DocumentID,$Documents{$DocumentID}{NVersions});
  }
}

### Sort

@DocumentIDs = reverse sort DocumentByRevisionDate @DocumentIDs;  

### Print summary information

if ($#DocumentIDs >= $HomeMaxDocs) {
  $#DocumentIDs = $HomeMaxDocs - 1; #Truncate array
  print "<hr><center><h4>Last $HomeMaxDocs documents modified
         </h4></center>\n";
} else {  
  print "<hr><center><h4>Documents modified in the last $HomeLastDays
  days</h4></center>\n";
}

print "<center><table cellpadding=3>\n";

&DocumentSummary(0,$Mode); # Force table headers
my $NumDoc = 0;

foreach $DocumentID (@DocumentIDs) {
  unless ($DocumentID) {next;}
  $Version = &LastAccess($DocumentID);
  if ($Version == -1) {next;}
  &DocumentSummary($DocumentID,$Mode,$Version);
  ++$NumDoc;
}

print "</table></center>\n";
print "<p>\n";

{
  require "FormElements.pm";

  print $query -> startform('POST',$LastModified);
  print "<center>";
  print $query -> submit (-value => "Show Documents");
  print " modified in the last ";
  &DaysPulldown;
  print " days.</center>";
  print $query -> endform;
  print "<p>&nbsp;<p>";
}

$EndTime  = new Benchmark;

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
