#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;    
                                                  
require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "ResponseElements.pm";
require "EmailSecurity.pm";

$query = new CGI;  # Global for subroutines

print $query->header;
&BTeVHeader("E-mail Notification Login");

&LoginEmailUserForm;
print "<p>\n";

&NewEmailUserForm;
print "<p>\n";

&DocDBNavBar;
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);

