#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;    
use DBI;    
                                                  
require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "ResponseElements.pm";
require "EmailSecurity.pm";

$query = new CGI;  # Global for subroutines

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

print $query->header;
&DocDBHeader("E-mail Notification Login");

&LoginEmailUserForm;
print "<p>\n";

&NewEmailUserForm;
print "<p>\n";

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);

