#! /usr/bin/env perl

use lib ".";

#
# Description: This script is called by KeywordAdministerForm and does administration
#              on Keyword Groups in the DB. This script adds, modifies and deletes
#              these groups. It will not delete groups if there are associated
#              keywords.
#
#      Author: Lynn Garren (garren@fnal.gov)
#    Modified:

# Copyright 2001-2013 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CGI;
use CGI::Untaint;
use DBI;

require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "Security.pm";
require "HTMLUtilities.pm";
require "UntaintInput.pm";
require "KeywordSQL.pm";
require "KeywordHTML.pm";
require "Messages.pm";

$query = new CGI;  # Global for subroutines
$query -> autoEscape(0);
my $Untaint = CGI::Untaint -> new($query -> Vars);

@ErrorStack = ();
@WarnStack  = ();

# Parameters to script

my $Password = $Untaint -> extract(-as_printable => "password") || "";
my $Username = $Untaint -> extract(-as_printable => "admuser") || "";
my $Action = $Untaint -> extract(-as_printable => "admaction") || "";

my $KeywordGroupID = $Untaint -> extract(-as_integer => "keywordgroup") || 0;
my $LongName = $Untaint -> extract(-as_safehtml => "longdesc") || "";
my $ShortName = $Untaint -> extract(-as_safehtml => "shortdesc") || "";

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$Username,$Password);

unless ($dbh) {
  push @ErrorStack,$Msg_AdminNoConnect;
}

print $query -> header( -charset => $HTTP_ENCODING );
&DocDBHeader("Modified List of Keyword Groups");

&EndPage(@ErrorStack);

unless (&CanAdminister) {
  push @ErrorStack,$Msg_AdminNoLogin;
}
&EndPage(@ErrorStack);

&GetKeywords;

if      ($Action eq "Delete") { # Delete keyword groups
  @KeywordListIDs = &GetKeywordsByKeywordGroupID($KeywordGroupID);
  if (!$KeywordGroupID) {
    push @ErrorStack,$Msg_ModKeyGrEmpty;
  } elsif (@KeywordListIDs) { # Not sure we want this anymore
    print "<b>This keyword group has keywords that must be deleted first:</b><br>\n";
    &KeywordsbyKeywordGroup($KeywordGroupID);
    push @ErrorStack,$Msg_DelKeyGrWKey;
  } else {
    my $KeywordGroupDelete = $dbh -> prepare("delete from KeywordGroup where KeywordGroupID=?");
    $KeywordGroupDelete -> execute($KeywordGroupID);
    print "<b>$KeywordGroups{$KeywordGroupID}{Long} has been deleted.</b><br>\n";
  }
} elsif ($Action eq "Modify") { # Modify keyword groups
  unless ($KeywordGroupID) {
    push @ErrorStack,$Msg_ModKeyGrEmpty;
  }
  &EndPage(@ErrorStack);

# Deal with name changes

  if ($ShortName) {
    print "<b>Updating short description.</b><br>\n";
    my $KeywordGroupUpdate = $dbh->prepare(
       "update KeywordGroup set ShortDescription=? where KeywordGroupID=?");
    $KeywordGroupUpdate -> execute($ShortName,$KeywordGroupID);
  }
  if ($LongName) {
    print "<b>Updating long description.</b><br>\n";
    my $KeywordGroupUpdate = $dbh->prepare(
       "update KeywordGroup set LongDescription=? where KeywordGroupID=?");
    $KeywordGroupUpdate -> execute($LongName,$KeywordGroupID);
  }

} elsif ($Action eq "New") { # Create new keyword groups
  print "<b>Adding a new keyword group.</b><br>\n";
  my $KeywordGroupInsert = $dbh->prepare(
   "insert into KeywordGroup (KeywordGroupID,ShortDescription,LongDescription) values (0,?,?)");#

  $KeywordGroupInsert -> execute($ShortName,$LongName);
  $KeywordGroupID = $KeywordGroupInsert -> {mysql_insertid}; # Works with MySQL only
} else {
  push @ErrorStack,"No valid action was specified.";
}

# For modify or new fetch information and display.

if ($Action eq "Modify" || $Action eq "New") {
  &GetKeywords;
  print "<p><b>Here are the results of your modification:<br>\n";
  print "Short description: $KeywordGroups{$KeywordGroupID}{Short}<br>\n";
  print "Long description:  $KeywordGroups{$KeywordGroupID}{Long}<br>\n";
  print "</b><p>\n";
}

print "<p>\n";
$keyadminform = "<a href=\"$KeywordAdministerForm\">Administer Keywords</a>";
$keylist = "<a href=\"$ListKeywords\">List Keywords</a>";
print "<center>\n";
print "$keyadminform $keylist\n";
print "</center>\n";
print "<p>\n";

&WarnPage(@WarnStack);
&EndPage(@ErrorStack);

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);

exit;
