#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2004 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use Benchmark;
use CGI;
use DBI;

$StartTime = new Benchmark;

require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "FormElements.pm";

require "TopicSQL.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";
require "SecuritySQL.pm";

require "HTMLUtilities.pm";
require "Security.pm";
require "Sorts.pm";

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

my $Days = $params{days};
my $Mode = $params{mode};

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetSecurityGroups;

### Set defaults

unless ($Mode eq "date" or $Mode eq "meeting") {$Mode = "date";}  
unless ($Days)                                 {$Days = $LastDays;}  

### Start HTML

print $query->header;
&DocDBHeader("Document List");

print "<center><h4>These documents have been modified in the last 
       <span class=\"Highlight\">$Days days</span>.</h4></center><p>\n";

my $revision_list = $dbh -> prepare(
   "select DocRevID from DocumentRevision 
    where TO_DAYS(NOW())-TO_DAYS(TimeStamp)<=?"); 

my $document_list = $dbh -> prepare(
   "select DocumentID from DocumentRevision where DocRevID=?"); 

my ($DocumentID,$DocRevID);

### Form

print $query -> startform('POST',$LastModified);
print "<center>";
print $query -> submit (-value => "Show Documents");
print " modified in the last ";
&DaysPulldown;
print " days.</center>";
print $query -> endform;
print "<p>";

### Get all revisions modified since $Days days ago

my %DocumentIDs = ();
$revision_list -> execute($Days);
$revision_list -> bind_columns(undef, \($DocRevID));

while ($revision_list -> fetch) {
  $document_list -> execute($DocRevID);
  ($DocumentID) = $document_list -> fetchrow_array;
  $DocumentIDs{$DocumentID} = 1; # Hash removes duplicates
}

### Get list of documents and read in the information we need from database

my @DocumentIDs = keys %DocumentIDs;

foreach my $DocumentID (@DocumentIDs) { # For shorter lists
  &FetchDocument($DocumentID);
  &FetchRevisionByDocumentAndVersion($DocumentID,$Documents{$DocumentID}{NVersions});
}

### Sort

if ($Mode eq "meeting") {
  @DocumentIDs = sort DocumentByRequester @DocumentIDs;  
} else {
  @DocumentIDs = reverse sort DocumentByRevisionDate @DocumentIDs;  
}

### Print summary information

print "<center><table cellpadding=3>\n";

&DocumentSummary(0,$Mode); # Force table headers
my $NumDoc = 0;

foreach $DocumentID (@DocumentIDs) {
  unless ($DocumentID) {next;}
  $Version = &LastAccess($DocumentID);
  if ($Version == -1) {next;}
  &DocumentSummary($DocumentID,$Mode,$Version);
  ++$NumDoc;
}

print "</table></center>\n";
print "<p>\n";

### Statistics

print "<p><b>Number of documents found: $NumDoc</b><p>\n";

$EndTime  = new Benchmark;

&DocDBNavBar();
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
