#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use Benchmark;
use CGI;
use DBI;

$StartTime = new Benchmark;

require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "FormElements.pm";

require "TopicSQL.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";
require "SecuritySQL.pm";

require "HTMLUtilities.pm";
require "Security.pm";
require "Sorts.pm";

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

my $Days = $params{days};
my $Mode = $params{mode};

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetSecurityGroups;

### Set defaults

unless ($Mode eq "date" or $Mode eq "meeting") {$Mode = "date";}  
unless ($Days)                                 {$Days = $LastDays;}  

### Start HTML

print $query->header;
&BTeVHeader("Document List");

print "<center><h4>These documents have been modified in the last 
       <font color=\"blue\">$Days days</font>.</h4></center><p>\n";

my $revision_list = $dbh -> prepare(
   "select DocRevID from DocumentRevision where NOW()-Timestamp<?"); 

my $document_list = $dbh -> prepare(
   "select DocumentID from DocumentRevision where DocRevID=?"); 

my $DocumentID,$DocRevID;

### Form

print $query -> startform('POST',$LastModified);
print "<center>";
print $query -> submit (-value => "Show Documents");
print " modified in the last ";
&DaysPulldown;
print " days.</center>";
print $query -> endform;
print "<p>";

### Get all revisions with this topic

my %DocumentIDs = ();
$revision_list -> execute($Days*1000000);
$revision_list -> bind_columns(undef, \($DocRevID));

while ($revision_list -> fetch) {
  $document_list -> execute($DocRevID);
  ($DocumentID) = $document_list -> fetchrow_array;
  $DocumentIDs{$DocumentID} = 1; # Hash removes duplicates
}

### Get list of documents and read in the information we need from database

my @DocumentIDs = keys %DocumentIDs;

foreach my $DocumentID (@DocumentIDs) { # For shorter lists
  &FetchDocument($DocumentID);
  &FetchDocRevision($DocumentID,$Documents{$DocumentID}{NVER});
}

### Sort

if ($Mode eq "meeting") {
  @DocumentIDs = sort DocumentByRequester @DocumentIDs;  
} else {
  @DocumentIDs = reverse sort DocumentByRevisionDate @DocumentIDs;  
}

### Print summary information

print "<center><table cellpadding=3>\n";

&DocumentSummary(0,$Mode); # Force table headers

foreach $DocumentID (@DocumentIDs) {
  unless ($DocumentID) {next;}
  unless (&CanAccess($DocumentID,$Documents{$DocumentID}{NVER})) {next;}
  # FIXME: Need to put latest document accessible if last version isn't
  &DocumentSummary($DocumentID,$Mode);
}

print "</table></center>\n";
print "<p>\n";

### Finish off page

$EndTime  = new Benchmark;
$TimeDiff = timediff($EndTime,$StartTime);
print "<p><b>Execution time: </b>",timestr($TimeDiff),"<p>\n";

&DocDBNavBar();
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
