#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "MeetingSQL.pm";
require "MeetingHTML.pm";
require "HTMLUtilities.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

%params = $query -> Vars;

my $Mode = $params{mode};

&GetConferences;

print $query->header;

my $PageTitle;
if ($Mode eq "modify") {
  $PageTitle = "Modify Events";
} else {
  $PageTitle = "List of Events";
}
     
&DocDBHeader($PageTitle);
if ($Mode eq "modify") {
  print "<h3>Select an event to change:</h3>\n";
  &AllMeetingsTable("modify");
} else {  
  &AllMeetingsTable("display");
}

&DocDBNavBar();
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
