#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#
# Inputs: 
#  Three ways of getting information 
#    1) topicid=? gives all documents with that MinorTopicID
#    2) majorid=? gives all documents with that MajorTopicID
#    3) major=?   gives all documents with the MajorTopicID 
#                 with that ShortDescription
#
#  Three modes of presenting information:
#    1) mode=date (default, sorted by reverse date, modification date given)
#    2) mode=meeting (sorted by author, files are listed)
#    3) mode=conference (sorted by reverse date, conference fields shown)

use Benchmark;
use CGI;
use DBI;

$StartTime = new Benchmark;

require "DocDBGlobals.pm";
require "ResponseElements.pm";

require "TopicSQL.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";
require "SecuritySQL.pm";

require "HTMLUtilities.pm";
require "WebUtilities.pm";
require "Security.pm";
require "Sorts.pm";

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

my $TopicID = $params{topicid};
my $MajorID = $params{majorid};
my $Major   = $params{major};
my $Mode    = $params{mode};

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetSecurityGroups;
&SpecialMajorTopics;

if ($Major || $MajorID) {
  &GetTopics;
  if ($Major) {
    $MajorID = &LookupMajorTopic($Major);
  }  
} else {  
  &FetchMinorTopic($TopicID);
  
### Default modes for certain topic types
  
  if ($MinorTopics{$TopicID}{MAJOR} == $ConferenceMajorID) {
    unless ($Mode) {$Mode = "conference";}
  }    
  if ($MinorTopics{$TopicID}{MAJOR} == $CollabMeetMajorID) {
    unless ($Mode) {$Mode = "meeting";}
  }    
}

### Set defaults

unless ($Mode eq "date" or $Mode eq "meeting" or $Mode eq "conference") {
  $Mode = "date";
}  

### Start HTML

print $query->header;

if ($Mode eq "conference") {
  require "MiscSQL.pm";
  
  &DocDBHeader("Conference Documents");
  &GetConferences;
  print "<center><h4>\n";
  if ($TopicID) { # This is just one conference, so we can print more info
    require "MiscSQL.pm";
    &FetchConferenceByTopicID($TopicID);
    print "These documents from \n";
    print "<font color=\"blue\">$MinorTopics{$TopicID}{LONG}</font>,<br>";
    print " held from ",&EuroDate($Conferences{$TopicID}{STARTDATE});
    print " to ",&EuroDate($Conferences{$TopicID}{ENDDATE});
    print " in $Conferences{$TopicID}{LOCATION}\n";
    print " are available.<br>\n";
    if ($Conferences{$TopicID}{URL}) {
      print "(<a href=\"$Conferences{$TopicID}{URL}\">Conference homepage</a>)\n";
    } else {
      print "(Conference homepage not available)\n";
    }
    print "</center>\n";
  }
} else {
  &DocDBHeader("Document List by Topic");
  print "<center><h4>\n";
  if ($MajorID || &FetchMinorTopic($TopicID)) {
    print "These documents on <font color=\"blue\">\n";
    if ($MajorID) {
      print $MajorTopics{$MajorID}{SHORT},"\n";
    } else {
      print $MinorTopics{$TopicID}{FULL},"\n";
    }
    print "</font> are available:\n";
  } else {
    print "The requested topic does not exist.\n";
  }  
}
print "</h4></center><p>\n";

my $revision_list = $dbh -> prepare(
   "select DocRevID from RevisionTopic where MinorTopicID=?"); 
my $revtopic_list = $dbh -> prepare(
   "select DocRevID,MinorTopicID from RevisionTopic"); 
my $document_list = $dbh -> prepare(
   "select DocumentID from DocumentRevision where DocRevID=? and Obsolete=0"); 

my $DocumentID,$DocRevID;

### Get all revisions with this sub topic

my %DocumentIDs = ();

if ($TopicID) {
  $revision_list -> execute($TopicID);
  $revision_list -> bind_columns(undef, \($DocRevID));

  while ($revision_list -> fetch) {
    &FetchDocRevisionByID($DocRevID);
    if ($DocRevisions{$DocRevID}{OBSOLETE}) {next;}
    $document_list -> execute($DocRevID);
    ($DocumentID) = $document_list -> fetchrow_array;
    $DocumentIDs{$DocumentID} = 1; # Hash removes duplicates
  }
}

### Get all revisions with this major topic
if ($MajorID) {
  $revtopic_list -> execute;
  $revtopic_list -> bind_columns(undef, \($DocRevID,$MinorTopicID));

  while ($revtopic_list -> fetch) {
    if ($MinorTopics{$MinorTopicID}{MAJOR} == $MajorID) {
      &FetchDocRevisionByID($DocRevID);
      if ($DocRevisions{$DocRevID}{OBSOLETE}) {next;}
      $document_list -> execute($DocRevID);
      ($DocumentID) = $document_list -> fetchrow_array;
      $DocumentIDs{$DocumentID} = 1; # Hash removes duplicates
    }
  }
}

### Get list of documents and read in the information we need from database

my @DocumentIDs = keys %DocumentIDs;

foreach my $DocumentID (@DocumentIDs) { # For shorter lists
  &FetchDocument($DocumentID);
  &FetchRevisionByDocumentAndVersion($DocumentID,$Documents{$DocumentID}{NVER});
}

### Sort

if      ($Mode eq "meeting") {
  @DocumentIDs  =        sort DocumentByRequester      @DocumentIDs;
  @IgnoreTopics = ($TopicID);  
} elsif ($Mode eq "conference") {
  &SpecialMajorTopics;
  @DocumentIDs = reverse sort DocumentByConferenceDate @DocumentIDs;
} else {
  @DocumentIDs = reverse sort DocumentByRevisionDate   @DocumentIDs;  
}

### Print summary information

if ($Mode eq "meeting" && !$Public) {

  my $AgendaURL = &FindAgendaURL($TopicID);
  if ($AgendaURL) {
    print "<p><center><a href=\"$AgendaURL\"><b>Agenda for this meeting</b></a></center><p>\n";
  }
  %DocFiles = ();  # Stupid caching problem
  %Files    = ();  # FIXME, please
}

print "<center><table cellpadding=3>\n";

&DocumentSummary(0,$Mode); # Force table headers
my $NumDoc = 0;

foreach $DocumentID (@DocumentIDs) {
  unless ($DocumentID) {next;}
  $Version = &LastAccess($DocumentID);
  if ($Version == -1) {next;}
  &DocumentSummary($DocumentID,$Mode,$Version);
  ++$NumDoc;
}

print "</table></center>\n";
print "<p>\n";

### Statistics

print "<p><b>Number of documents found: $NumDoc</b><p>\n";

$EndTime  = new Benchmark;
$TimeDiff = timediff($EndTime,$StartTime);
print "<p><b>Execution time: </b>",timestr($TimeDiff),"<p>\n";

### Special stuff if this is the current meeting

if (&NearByMeeting == $TopicID && $Mode eq "meeting" && !$Public) {

  print "<hr>\n";

  print "<h3>Useful links:</h3>\n";
  print "<ul>\n";
  print "<li><a href=\"$DocumentAddForm?special=meeting\">Submit a talk</a> for
         this meeting.\n";
  print "<li>
         <a href=$HelpFile#meeting>Instructions</a> for submitting talks,
         <a href=\"http://www-btev.fnal.gov/internal_documents/mtg/submitting_24may01.html\">
         pointers</a> on document formats, and
         <a href=\"http://www-btev.fnal.gov/internal_documents/mtg/transp_instructions.html#scanning\">instructions 
         on using the WH9W scanner</a>.\n";
  print "</ul>\n";

#  print "<hr>\n";
#  &PrintAgenda($TopicID);
}

if ($Mode eq "meeting" && !$Public) {
  &DocDBNavBar("List&nbsp;Meetings",$ListMeetings);
} else {
  &DocDBNavBar();
}

&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);

exit;
