#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use Benchmark;
use CGI;
use DBI;

$StartTime = new Benchmark;

require "DocDBGlobals.pm";
require "ResponseElements.pm";

require "MiscSQL.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";
require "SecuritySQL.pm";

require "HTMLUtilities.pm";
require "Security.pm";
require "Sorts.pm";

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

my $TypeID = $params{typeid};

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetSecurityGroups;
&FetchDocType($TypeID);

### Start HTML

print $query->header;
&BTeVHeader("Document List by Type");


print "<center><h4>These documents of type <font color=\"blue\">
$DocumentTypes{$TypeID}{SHORT}</font> are
available:</h4></center><p>\n";

my $document_list = $dbh -> prepare(
   "select DocumentID from Document where DocumentType=?"); 

my $DocumentID;

### Get all documents with this type

my %DocumentIDs = ();
$document_list -> execute($TypeID);
$document_list -> bind_columns(undef, \($DocumentID));

while ($document_list -> fetch) {
  $DocumentIDs{$DocumentID} = 1; # Hash removes duplicates
}

### Get list of documents and read in the information we need from database

my @DocumentIDs = keys %DocumentIDs;

foreach my $DocumentID (@DocumentIDs) { # For shorter lists
  &FetchDocument($DocumentID);
  &FetchDocRevision($DocumentID,$Documents{$DocumentID}{NVER});
}

### Sort

@DocumentIDs = reverse sort DocumentByRevisionDate @DocumentIDs;  

### Print summary information

print "<center><table cellpadding=3>\n";

&DocumentSummary(0); # Force table headers

foreach $DocumentID (@DocumentIDs) {
  unless ($DocumentID) {next;}
  unless (&CanAccess($DocumentID,$Documents{$DocumentID}{NVER})) {next;}
  # FIXME: Need to put latest document accessible if last version isn't
  &DocumentSummary($DocumentID);
}

print "</table></center>\n";
print "<p>\n";

### Statistics

my $NumDoc = $#DocumentIDs + 1;
print "<p><b>Number of documents found: $NumDoc</b><p>\n";

$EndTime  = new Benchmark;
$TimeDiff = timediff($EndTime,$StartTime);
print "<p><b>Execution time: </b>",timestr($TimeDiff),"<p>\n";

&DocDBNavBar();
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
