#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
use DBI;

require "MySQLAccess.pm";
require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetDocTypes;

print $query->header;
&BTeVHeader("List of Document Types");

print "<h3>Types of Documents:</h3>\n";

&TypesTable;

&DocDBNavBar();
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
