#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#
# Right now this is pretty primative, but what do you expect when we have one
# publication in the DB.

# First thing to fix is to display reasonable fields. 

# Later on, we should provide stuff more like hep-ex, with links to 
# publisher's sites, select by publication or year, BibTex, etc.

use Benchmark;
use CGI;
use DBI;

$StartTime = new Benchmark;

require "DocDBGlobals.pm";
require "ResponseElements.pm";

require "MiscSQL.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";
require "SecuritySQL.pm";

require "HTMLUtilities.pm";
require "Security.pm";
require "Sorts.pm";

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

my $TypeID = $params{typeid};

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetSecurityGroups;

### Start HTML

print $query->header;
&DocDBHeader("BTeV Publications");


print "<center><h4>These refereed publications by BTeV are
available:</h4></center><p>\n";

my $document_list = $dbh -> prepare(
   "select DocumentID from DocumentRevision where JournalID>0"); 

my $DocumentID;

### Get all documents with this type

my %DocumentIDs = ();
$document_list -> execute();
$document_list -> bind_columns(undef, \($DocumentID));

while ($document_list -> fetch) {
  $DocumentIDs{$DocumentID} = 1; # Hash removes duplicates
}

### Get list of documents and read in the information we need from database

my @DocumentIDs = keys %DocumentIDs;

foreach my $DocumentID (@DocumentIDs) { # For shorter lists
  &FetchDocument($DocumentID);
  &FetchRevisionByDocumentAndVersion($DocumentID,$Documents{$DocumentID}{NVER});
}

### Sort

### FIXME: More generic way of selecting fields to sort on

@DocumentIDs = reverse sort DocumentByRevisionDate @DocumentIDs;  

### Print summary information

print "<center><table cellpadding=3>\n";

### FIXME: More generic way of selecting fields to display

&DocumentSummary(0); # Force table headers
my $NumDoc = 0;

foreach $DocumentID (@DocumentIDs) {
  unless ($DocumentID) {next;}
  $Version = &LastAccess($DocumentID);
  if ($Version == -1) {next;}
  &DocumentSummary($DocumentID,$Mode,$Version);
  ++$NumDoc;
}

print "</table></center>\n";
print "<p>\n";

### Statistics

print "<p><b>Number of documents found: $NumDoc</b><p>\n";

$EndTime  = new Benchmark;
$TimeDiff = timediff($EndTime,$StartTime);
print "<p><b>Execution time: </b>",timestr($TimeDiff),"<p>\n";

&DocDBNavBar();
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
