#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use Benchmark;
use CGI;
use DBI;

$StartTime = new Benchmark;

require "DocDBGlobals.pm";

require "AuthorSQL.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";
require "SecuritySQL.pm";

require "ResponseElements.pm";
require "AuthorHTML.pm";

require "HTMLUtilities.pm";
require "Sorts.pm";
require "Messages.pm";

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

my $AuthorID = $params{authorid};

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetSecurityGroups;
&GetInstitutions;

### Start HTML

print $query->header;
&DocDBHeader("Document List by Author");

&FetchAuthor($AuthorID);

unless ($Authors{$AuthorID}{LASTNAME}) {
  push @ErrorStack,$Msg_AuthorInvalid;
}

&EndPage(@ErrorStack);

### Output Information

print "<center><h4><font color=\"blue\">\n";
&PrintAuthorInfo($AuthorID);
print "</font><br>is listed as an author on the following documents:</h4></center><p>\n";

### Get list of documents and read in the information we need from database

my @DocumentIDs = &GetAuthorDocuments($AuthorID);  

foreach my $DocumentID (@DocumentIDs) { # For shorter lists
  &FetchDocument($DocumentID);
  &FetchRevisionByDocumentAndVersion($DocumentID,$Documents{$DocumentID}{NVersions});
}

### Sort

@DocumentIDs = reverse sort DocumentByRevisionDate @DocumentIDs;  

### Print summary information

print "<center><table cellpadding=3>\n";

&DocumentSummary(0); # Force table headers
my $NumDoc = 0;

foreach $DocumentID (@DocumentIDs) {
  unless ($DocumentID) {next;}
  $Version = &LastAccess($DocumentID);
  if ($Version == -1) {next;}
  &DocumentSummary($DocumentID,$Mode,$Version);
  ++$NumDoc;
}

print "</table></center>\n";
print "<p>\n";

### Statistics

print "<p><b>Number of documents found: $NumDoc</b><p>\n";

$EndTime  = new Benchmark;

&DocDBNavBar();
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
