#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "MeetingSQL.pm";
require "MeetingHTML.pm";
require "HTMLUtilities.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetConferences;

print $query->header;
&DocDBHeader("List of Meetings");

print "<h3>Meetings in Document Database</h3>\n";

&MeetingsTable;

&DocDBNavBar();
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
