#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use Benchmark;
use CGI;
use DBI;

$StartTime = new Benchmark;

require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "Security.pm";
require "MySQLAccess.pm";
require "HTMLUtilities.pm";
require "Sorts.pm";

$query = new CGI;  # Global for subroutines

### Start HTML

print $query->header;
&BTeVHeader("BTeV Document List","Document List");

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

%params = $query -> Vars;

&GetAuthors;
&GetSecurityGroups;

### Get all revisions and documents

&GetAllDocuments;  # For very 
&GetAllRevisions;  # long lists

### Sort

my @SortedDocuments = reverse sort DocumentByRevisionDate @DocumentIDs;

### Print summary information

print "<center><table cellpadding=3>\n";

&DocumentSummary(0); # Force table headers
my $NumDoc = 0;

foreach $DocumentID (@SortedDocuments) {
  unless ($DocumentID) {next;}
  $Version = &LastAccess($DocumentID);
  if ($Version == -1) {next;}
  &DocumentSummary($DocumentID,$Mode,$Version);
  ++$NumDoc;
}

print "</table></center>\n";
print "<p>\n";

### Statistics

print "<p><b>Number of documents found: $NumDoc</b><p>\n";

$EndTime  = new Benchmark;
$TimeDiff = timediff($EndTime,$StartTime);
print "<p><b>Execution time: </b>",timestr($TimeDiff),"<p>\n";

&DocDBNavBar();
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
