#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "TopicSQL.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetTopics;

print $query->header;
&DocDBHeader("List of Topics");

print "<h3>Existing Topics:</h3>\n";

&TopicsTable;

&DocDBNavBar();
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
