#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
use DBI;

require "MySQLAccess.pm";
require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";
require "Sorts.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetTopics;

print $query->header;
&BTeVHeader("Collaboration Meetings");

print "<h3>Useful links:</h3>\n";
print "<ul>\n";
print "<li><a href=\"http://www-btev.fnal.gov/calendar.html\">Upcoming Meetings</a>\n";
print "<li><a href=\"$DocumentAddForm?special=meeting\">Submit a talk</a> for
       the upcoming or just-past  meeting\n";
print "<li>
       <a href=\"$HelpFile#meeting\">Instructions</a> for submitting talks and
       <a href=\"$HelpFile#formats\">pointers</a> on document formats\n";
print "<li> <a href=\"http://www-btev.fnal.gov/atwork/general/userinfo/meet.shtml\">Visiting Fermilab</a> for a Collaboration Meeting\n";
print "<li><a href=\"http://www-btev.fnal.gov/internal_documents/meetings.html\">Collaboration meeting listings</a> 
       pre-dating the Document Database\n";
print "</ul>\n";

print "<h3>Meetings in the document database:</h3>\n";

&MeetingsTable;

print "<h3>Meetings not yet in database:</h3>\n";

print "These links will be removed as meetings are replicated in the document database.\n";

print <<OLDMEETINGS; # Following is straight from Rob/Lory page with subs

<ul>
<li> Saturday January 27, 2001, BTeV Collaboration Meeting
     <a href = http://www-btev.fnal.gov/internal_documents/mtg/jan_27_01.html> links to agenda and
     transparencies.</a>
<li> Sunday April 30, 2000, BTeV Collaboration Meeting
     <a href = http://www-btev.fnal.gov/internal_documents/mtg/apr_30_00.html>agenda with links to
     transparencies.</a>
<li> Saturday April 1, 2000, BTeV Collaboration Meeting
     <a href = http://www-btev.fnal.gov/internal_documents/mtg/apr_01_00.html>agenda with links to
     transparencies.</a>
<li> Sunday Mar. 5, 2000, BTeV Collaboration Meeting
     <a href = http://www-btev.fnal.gov/internal_documents/mtg/mar_05_00.html>agenda with links to
     transparencies.</a>
<li> Saturday Jan. 29, 2000, BTeV Collaboration Meeting
     <a href = http://www-btev.fnal.gov/internal_documents/mtg/jan_29_00.html>agenda with links to
     transparencies.</a>
<li> Saturday Dec. 18, 1999, BTeV Collaboration Meeting
     <a href = http://www-btev.fnal.gov/internal_documents/mtg/dec_18_99.html>agenda with links to
     transparencies.</a>
<li> Saturday Oct. 9, 1999, BTeV Collaboration Meeting
     <a href = http://www-btev.fnal.gov/internal_documents/mtg/oct_09_99.html>agenda with links to
     transparencies.</a>
<li> Friday April 23, 1999, BTeV Collaboration Meeting
     <a href = http://www-btev.fnal.gov/internal_documents/mtg/apr_23_99.html>agenda with links to
     transparencies.</a>
<li> Sunday March 28, 1999, BTeV Collaboration Meeting
     <a href = http://www-btev.fnal.gov/internal_documents/mtg/mar_28_99.html>agenda with links to
     transparencies.</a>
<li> Saturday Feb. 20, 1999, BTeV Collaboration Meeting
     <a href = http://www-btev.fnal.gov/internal_documents/mtg/feb_20_99/agenda.html>agenda with links to
     transparencies.</a>
<li> Saturday Sept. 12, 1998, BTeV Collaboration Meeting
     <a href = http://www-btev.fnal.gov/internal_documents/mtg/09_12_98/agenda.html>agenda with links to
     transparencies.</a>
<li> Sunday March 8, 1998, BTeV Collaboration Meeting
     <a href = http://www-btev.fnal.gov/internal_documents/mtg/mar_08_98.html>agenda with links to
     transparencies.</a>

</ul>

OLDMEETINGS

&DocDBNavBar("Add Talk","$DocumentAddForm?special=meeting");
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
