#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "AuthorSQL.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetInstitutions;
&GetAuthors;

print $query->header;
&BTeVHeader("List of Authors");

print "<h3>All Existing Authors: </h3>\n";

&AuthorsTable;

&DocDBNavBar();
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
