#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use Benchmark;
use CGI;
use DBI;

$StartTime = new Benchmark;

require "ResponseElements.pm";
require "DocDBGlobals.pm";
require "MiscSQL.pm";
require "SecuritySQL.pm";
require "HTMLUtilities.pm";
require "Security.pm";
require "Sorts.pm";

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

my $TypeID = $params{typeid};

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetSecurityGroups;

print $query->header;
&BTeVHeader("Document List by Type");

&FetchDocType($TypeID);

print "<center><h4>These documents of type <font color=\"blue\">
$DocumentTypes{$TypeID}{SHORT}</font> are
available:</h4></center><p>\n";

my $document_list = $dbh -> prepare(
   "select DocumentID from Document where DocumentType=?"); 

my $DocumentID;

$document_list -> execute($TypeID);
$document_list -> bind_columns(undef, \($DocumentID));

while ($document_list -> fetch) {
  $DocumentIDs{$DocumentID} = 1; # Hash removes duplicates
}

my @DocumentIDs = reverse sort DocumentByRevisionDate keys %DocumentIDs;  

print "<center><table cellpadding=3>\n";

&DocumentSummary(0); # Force table headers

foreach $DocumentID (@DocumentIDs) {
  unless ($DocumentID) {next;}
  unless (&CanAccess($DocumentID,$Documents{$DocumentID}{NVER})) {next;}
  # FIXME: Need to put latest document accessible if last version isn't
  &DocumentSummary($DocumentID);
}

print "</table></center>\n";
print "<p>\n";

print "Return to the <a href=$MainPage>main page</a>.\n";
print "<p>\n";

$EndTime  = new Benchmark;
$TimeDiff = timediff($EndTime,$StartTime);
print "<p><b>Execution time: </b>",timestr($TimeDiff),"<p>\n";

&DocDBNavBar;
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
