#! /usr/bin/env perl
#
# Description: Intended as a homepage for collaboration meetings. The  
#              list of meetings is presented, along with some special links
#              for adding talks to meetings via an abbreviated form and other
#              collaboration specific information.
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "TopicSQL.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";
require "Sorts.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetTopics;

print $query->header;
&DocDBHeader("Collaboration Meetings");

print "<h3 class=\"SectionHeading\">Useful links:</h3>\n";
print "<ul>\n";
print "<li><a href=\"$DocumentAddForm?special=meeting\">Submit a talk</a> for
       the upcoming or just-past  meeting\n";
print "</ul>\n";

print "<h3 class=\"SectionHeading\">Meetings in the document database:</h3>\n";

&MeetingsTable;

&DocDBNavBar("Add Talk","$DocumentAddForm?special=meeting");
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
