#! /usr/bin/env perl

use lib ".";

#
# Author Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2013 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CGI;
use DBI;

require "DocDBGlobals.pm";
require "SecuritySQL.pm";
require "SecurityHTML.pm";
require "HTMLUtilities.pm";
require "DBUtilities.pm";

$query = new CGI;  # Global for subroutines
$query -> autoEscape(0);
CreateConnection(-type => "ro");

GetSecurityGroups();

print $query -> header( -charset => $HTTP_ENCODING );
DocDBHeader("List of Groups");

print '<table class="CenteredTable MedPaddedTable">';
print "<tr><th>Group</th><th>Description</th></tr>\n";

foreach my $GroupID (keys %SecurityGroups) {
  print "<tr>\n";
  print "<td>",SecurityLink( {-groupid => $GroupID} ),"</td>\n";
  print "<td>",SmartHTML({-text=>$SecurityGroups{$GroupID}{Description}}),"</td>\n";
  print "</tr>\n";
}

print "</table>\n";


DocDBNavBar();
DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
