#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2006 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "MeetingSQL.pm";
require "MeetingHTML.pm";
require "HTMLUtilities.pm";
require "SecuritySQL.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

%params = $query -> Vars;

my $Mode         = $params{mode} || "display";
my $EventGroupID = $params{eventgroupid};
my $EventGroup   = $params{eventgroup};

GetConferences();
GetSecurityGroups(); 

print $query -> header( -charset => $HTTP_ENCODING );

my $PageTitle;
if ($Mode eq "modify") {
  $PageTitle = "Modify Events";
} else {
  $PageTitle = "List of Events";
}
     
DocDBHeader($PageTitle);

if ($EventGroup || $EventGroupID) {
  unless ($EventGroupID) {
    $EventGroupID = LookupEventGroup($EventGroup);
  }  
  EventsByGroup( {-groupid => $EventGroupID, -mode => $Mode, -singlegroup => $TRUE} );
} else {
  if ($Mode eq "modify") {
    print "<h3>Select an event to change:</h3>\n";
    EventsTable( {-mode => "modify"} );
  } else {  
    EventsTable( {-mode => "display"} );
  }
}

DocDBNavBar();
DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
