#! /usr/bin/env perl
#
# Description: This script is called by AdministerForm and does administration
#              on Major Topics in the DB. This script adds, modifies and deletes
#              these topics. It will not delete major topics if there are associated
#              minor or sub-topics. 
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

use CGI;
use DBI;

require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "Security.pm";
require "HTMLUtilities.pm";
require "TopicSQL.pm";
require "TopicHTML.pm";
require "Messages.pm";

$query = new CGI;  # Global for subroutines

print $query -> header;
&DocDBHeader("Modified List of Major Topics");

%params = $query -> Vars;

@ErrorStack = ();
@WarnStack  = ();

# Parameters to script 

$Password      = $params{password};
$Username      = $Administrator;
$Action        = $params{admaction};

$MajorTopicID  = $params{majortopic};
$LongName      = $params{long};
$ShortName     = $params{short};

unless (&CanAdminister) {
  push @ErrorStack,$Msg_AdminNoLogin;
}  
&EndPage(@ErrorStack);

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$Username,$Password);

unless ($dbh) {
  push @ErrorStack,$Msg_AdminNoConnect;
}         
&EndPage(@ErrorStack);

&GetTopics;

if      ($Action eq "Delete") { # Delete major topics
  @TopicIDs = &GetSubTopics($MajorTopicID); 
  if (!$MajorTopicID) {
    push @ErrorStack,$Msg_ModMajEmpty;
  } elsif (@TopicIDs) {
    print "<b>This topic has subtopics that must be deleted first:</b><br>\n";
    &TopicsByMajorTopic($MajorTopicID);
    push @ErrorStack,$Msg_DelMajWTopics;
  } else {
    my $MajorTopicDelete = $dbh -> prepare("delete from MajorTopic where MajorTopicID=?");
    $MajorTopicDelete -> execute($MajorTopicID);
    print "<b>$MajorTopics{$MajorTopicID}{LONG} has been deleted.</b><br>\n";
  }
} elsif ($Action eq "Modify") { # Modify major topics
  unless ($MajorTopicID) {
    push @ErrorStack,$Msg_ModMajEmpty;
  }
  &EndPage(@ErrorStack);

# Deal with name changes     

  if ($ShortName) { 
    print "<b>Updating short description.</b><br>\n";
    my $MajorTopicUpdate = $dbh->prepare(
       "update MajorTopic set ShortDescription=? where MajorTopicID=?");
    $MajorTopicUpdate -> execute($ShortName,$MajorTopicID);
  }
  if ($LongName) { 
    print "<b>Updating long description.</b><br>\n";
    my $MajorTopicUpdate = $dbh->prepare(
       "update MajorTopic set LongDescription=? where MajorTopicID=?");
    $MajorTopicUpdate -> execute($LongName,$MajorTopicID);
  }

} elsif ($Action eq "New") { # Create new major topics
  print "<b>Adding a new major topic.</b><br>\n";
  my $MajorTopicInsert = $dbh->prepare(
   "insert into MajorTopic (MajorTopicID,ShortDescription,LongDescription) values (0,?,?)");#

  $MajorTopicInsert -> execute($ShortName,$LongName);
  $MajorTopicID = $MajorTopicInsert -> {mysql_insertid}; # Works with MySQL only
} else {
  push @ErrorStack,"No valid action was specified.";
}  

# For modify or new fetch information and display.

if ($Action eq "Modify" || $Action eq "New") {
  &GetTopics;
  print "<p><b>Here are the results of your modification:<br>\n";
  print "Short description: $MajorTopics{$MajorTopicID}{SHORT}<br>\n";
  print "Long description:  $MajorTopics{$MajorTopicID}{LONG}<br>\n";
  print "</b><p>\n";
}  

print "<p>\n";

&WarnPage(@WarnStack);
&EndPage(@ErrorStack);

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
 
exit;
