#! /usr/bin/env perl
#
#        Name: MeetingCreate
# Description: Create the shell of a meeting. Calls MeetingModify
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

use CGI;
use DBI;

require "DocDBGlobals.pm";
require "Scripts.pm";

require "HTMLUtilities.pm";
require "TopicHTML.pm";
require "MeetingHTML.pm";
require "TopicSQL.pm";

require "FormElements.pm";

$query = new CGI;  # Global for subroutines

print $query->header;
&DocDBHeader("Create a Meeting");
&HelpPopupScript;

# %params = $query -> Vars;

# @ErrorStack = ();
# @WarnStack  = ();

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

#unless ($dbh) {
#  push @ErrorStack,$Msg_AdminNoConnect;
#}         
#&EndPage(@ErrorStack);

&GetTopics;

print $query -> start_multipart_form('POST',"$MeetingModify");
print $query -> hidden(-name => 'mode',   -default => 'create');
print "<table cellpadding=10>\n";


print "<tr valign=top>\n";
print "<td>\n"; &MajorGatheringSelect; print "</td>\n";
print "<td>\n";
 print "<table>\n";
 print "<tr valign=top>\n";
 print "<td width=10>Only select a Major Topic and fill in the descriptions if
 you want to make a new topic.\n";
 print "<a ";
 &HelpLink("meetingtopic");
 print "Click for an explanation.</a>\n";
 print "</td>\n";
 print "</tr>\n";
 print "<tr valign=top>\n";
 print "<td>\n"; &ShortDescriptionBox;     print "</td>\n";
 print "</tr>\n";
 print "<tr valign=top>\n";
 print "<td>\n"; &LongDescriptionBox;      print "</td>\n";
 print "</tr>\n";
 print "<tr valign=top>\n";
 print "<td>\n"; &ConferenceShowAllTalks;      print "</td>\n";
 print "</tr>\n";
 print "</table>\n";
print "</td>\n";
print "<td>\n";
 print "<table>\n";

 print "<tr valign=top>\n";
 print "<td>\n"; &LocationBox;       print "</td>\n";
 print "</tr>\n";

 print "<tr valign=top>\n";
 print "<td>\n"; &ConferenceURLBox;  print "</td>\n";
 print "</tr>\n";

 print "<tr valign=top>\n";
 print "<td>\n"; &StartDatePullDown; print "</td>\n";
 print "</tr>\n";

 print "<tr valign=top>\n";
 print "<td>\n"; &EndDatePullDown;   print "</td>\n";
 print "</tr>\n";

 print "</table>\n";
print "</td>\n";
print "</tr>\n";
print "</table>\n";

print "<table cellpadding=10>\n";
print "<tr valign=top>\n";
print "<td>\n"; &ConferencePreambleBox; print "</td>\n";
print "<td>\n"; &ConferenceEpilogueBox; print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td colspan=2>\n"; &SessionEntryForm;   print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
print "<td colspan=2>\n";
print $query -> submit (-value => "Create New Meeting");
print "</td>\n";
print "</tr>\n";

print "</table>\n";
print $query -> end_multipart_form;

print "<center><h4>Existing Meetings and Conferences</h4></center>\n";

&GatheringTable;

print "<p><hr>\n";

print "<p>\n";

#&WarnPage(@WarnStack);
#&EndPage(@ErrorStack);

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
 
exit;
