#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use DBI;

require "ResponseElements.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";
require "FSUtilities.pm";
require "WebUtilities.pm";
require "HTMLUtilities.pm";
require "Security.pm";

print "This program was designed to be used only once. Don't run it. Provided
       for illustration only!\n";
       
exit;       

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);

&ObsGetSecurities; 

### Templates

my $rev_security_insert =  $dbh->prepare(
   "insert into RevisionSecurity ".
   "       (RevSecurityID, DocRevID, GroupID) ".
   "values (0,             ?,        ?)");
                                 

my $doc_rev_fetch = $dbh -> prepare("select DocRevID from DocumentRevision");
my $DocRevID;

$doc_rev_fetch -> execute;
$doc_rev_fetch -> bind_columns(undef, \($DocRevID));
  
while ($doc_rev_fetch -> fetch) {
  &FetchDocRevisionByID($DocRevID);
  @SecurityList = @{$DocRevisions{$DocRevID}{SECURITY}};
  foreach $security (@SecurityList) {
    if ($security eq "BTeV") {
      $rev_security_insert -> execute($DocRevID,1);
    } elsif ($security eq "Executive") {
      $rev_security_insert -> execute($DocRevID,2);
    } elsif ($security eq "RTES") {
      $rev_security_insert -> execute($DocRevID,3);
    } 
  }  
}

