#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "SecuritySQL.pm";
require "Scripts.pm";
require "ResponseElements.pm";
require "Cookies.pm";
require "Security.pm";
require "SecuritySQL.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetSecurityGroups;

print $query->header;
&DocDBHeader("Document Modifications");
@error_stack = ();

if ($Public || !&CanCreate()) {
  push @error_stack,"You are not allowed to modify or create documents.";
}

&HelpPopupScript;

if (@error_stack) {  # The user made one or more mistakes, warn and exit
  &EndPage(@error_stack);
}

print "<p><center><h4>\n";
 print "Click any <font color=red>red link</font> for quick help, or <a
 href=\"$MainPage\">view documents</a> in the database.\n";
 print "(<a href=\"$HelpFile\">Database instructions</a>) \n";
print "</h4></center>\n";

print "<p><b>Short cuts for putting information into the database: ";
print "(<a "; &HelpLink("modifytypes"); 
print "Which option do I choose?</a>)</b>\n";
print "<ul>\n";

### New upload short form

print "<li>"; 
print $query -> startform('POST',$DocumentAddForm);
print $query -> submit (-value => "Create a new");
print " document from "; 
print $query -> textfield(-name => "numfile", -size => 2, -maxlength => 2);
print " file(s) on your <b><a "; 
&HelpLink("uploadmethod"); 
print "local computer</a></b> \n"; 
#print "(no need to reserve the document).\n";
print $query -> hidden(-name => 'mode',    -default => 'add');
print $query -> hidden(-name => 'upload',    -default => 'file');
print $query -> endform;

### New http short form

print "<li>"; 
print $query -> startform('POST',$DocumentAddForm);
print $query -> submit (-value => "Create a new");
print " document from "; 
print $query -> textfield(-name => "numfile", -size => 2, -maxlength => 2);
print " file(s) on the <b><a "; 
&HelpLink("uploadmethod"); 
print "web</a></b> \n"; 
#print "(no need to reserve the document).\n";
print $query -> hidden(-name => 'mode',    -default => 'add');
print $query -> hidden(-name => 'upload',    -default => 'http');
print $query -> endform;

### Reserve form (button)

print "<li>"; 
print $query -> startform('POST',$DocumentAddForm);
print $query -> submit (-value => "Reserve");
print " a document number\n"; 
print "(if you don't yet have a draft of your document).\n";
print $query -> hidden(-name => 'mode',    -default => 'reserve');
print $query -> endform;

### Update short form

print "<li>"; 
print $query -> startform('POST',$DocumentAddForm);
print $query -> submit (-value => "Update");
print " document # "; 
print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
print $query -> hidden(-name => 'mode',    -default => 'update');
print $query -> endform;

### Update DB short form

print "<li>"; 
print $query -> startform('POST',$DocumentAddForm);
print $query -> submit (-value => "Update DB Info");
print " for document # "; 
print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
print $query -> hidden(-name => 'mode',    -default => 'updatedb');
print $query -> endform;

### File Add short form

print "<li>"; 
print $query -> startform('POST',$AddFilesForm);
print $query -> submit (-value => "Add");
print " "; 
print $query -> textfield(-name => "numfile", -size => 3, -maxlength => 2);
print " file(s) to document # "; 
print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
#print $query -> hidden(-name => 'mode',    -default => 'updatedb');
print $query -> endform;

if (&CanAdminister()) {
  print "<li>"; 
  print $query -> startform('POST',$DeleteConfirm);
  print $query -> submit (-value => "Delete");
  print " document # "; 
  print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
  print $query -> endform;
}
print "<li>See below if these options aren't flexible enough.\n";

print "</ul>\n";

print "<p><b>Database maintenance:</b><ul>\n";
print "<li>Add an <a href=\"$AuthorAddForm\">author</a>\n";
print "<li>Add a  <a href=\"$ConferenceAddForm\">conference</a>\n";
print "<li>Organize a <a href=\"$MeetingModify\">new</a> or an 
           <a href=\"$ListAllMeetings?mode=modify\">existing</a> meeting 
           (with talks)\n";
           
if (&CanAdminister()) {
  print "<li>Add a <a href=\"$TopicAddForm\">topic</a>\n";
  print "<li>Add, delete, or modify <a href=\"$GroupAdministerForm\">groups</a>\n";
  print "<li>Administer <a href=\"$KeywordForm\">keywords and keyword groups</a>\n";
  print "<li>View/modify <a href=\"$EmailAdministerForm\">E-mail notifications</a>\n";
  print "<li>Perform other <a href=\"$AdministerForm\">administration tasks</a>\n";
}
print "</ul>\n";

print "<p><hr><p>\n";
  
### Customized Add/Update form creation form   
  
print $query -> start_multipart_form('POST',$DocumentAddForm);

$modes{reserve}  = "Reserve document #";
$modes{add}      = "New document";
$modes{update}   = "Update existing document";
$modes{updatedb} = "Update DB information";  # See note in ProcessDocumentAdd

@modes = ("add","reserve","update","updatedb");

$uploads{http}   = "HTTP submission";
$uploads{file}   = "Local file upload";
@uploads = ("file","http");

$archives{archive}    = "Archive (.tar/.zip) upload";
$archives{single}   = "Single file";
$archives{multi}   = "Multiple files";
@archives = ("single","multi","archive");

$topicmodes{multi}  = "Multiple Topic Boxes";
$topicmodes{single} = "Single Topic List";
@topicmodes = ("multi","single");

$authormodes{field}  = "Text field";
$authormodes{list} = "Selectable list";
@authormodes = ("list","field");

&GetPrefsCookie;

print "<table cellpadding=5 border=5 align=center>\n";
print "<tr><td colspan=2 align=center><big>Customized Insert/Modify</big><br>
       Use this form to produce a
       customized document creation or update form.<br> Make a selection from each
       group.</th></tr>\n";
print "<tr><td align=right>\n";
print "<a "; &HelpLink("modifytypes"); 
print "<b>Type of modification:</b></a>\n";

print "<td>\n";
 print "<table cellpadding=3><tr><td>\n";
 print $query -> radio_group(-name => "mode", -labels => \%modes, -values => \@modes, -columns => 2);
 print "<tr><td align=right valign=bottom>\n";
 print "<b>Update Doc #:</b>\n";
 print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
 print "&nbsp;&nbsp;&nbsp;\n";
 print "</table>\n";

print "<tr><td align=right>\n";
print "<a "; &HelpLink("uploadtype"); 
print "<b>Upload type:</b></a>\n";
print "<td>\n";
print "<table cellpadding=3><tr><td>\n";
print $query -> radio_group(-name => "archive", -values => \@archives, -default => $UploadTypePref, -labels
                            => \%archives, -columns => 1);
print "</td><td>\n";
print $query -> textfield(-name => "numfile", -default => $NumFilesPref, -size => 2, -maxlength => 2);
print "<b># of files</b>\n";
print "</td></tr></table>\n";

print "<tr><td align=right>\n";
print "<a "; &HelpLink("uploadmethod"); 
print "<b>Upload method:</b></a>\n";
print "<td>\n";
print $query -> radio_group(-name => "upload", -values => \@uploads, -default => $UploadMethodPref, -labels => \%uploads);

print "<tr><td align=right>\n";
print "<a "; &HelpLink("topicoption"); 
print "<b>Topic Selection:</b></a>\n";
print "<td>\n";
print $query -> radio_group(-name => "topicmode", -values => \@topicmodes, -default => $TopicModePref, -labels => \%topicmodes);
print "<tr><td align=right>\n";
print "<a "; &HelpLink("authoroption"); 
print "<b>Author Selection:</b></a>\n";
print "<td>\n";
print $query -> radio_group(-name => "authormode", -values => \@authormodes, -default => $AuthorModePref, -labels => \%authormodes);
print "<tr><td align=right>\n";
print "<a "; &HelpLink("dateoverride"); 
print "<b>Override submit date:</b></a>\n";
print "<td>\n";
print $query -> radio_group(-name => "overdate", -values => ['No','Yes'],
                            -default => $DateOverridePref);
print "<tr><td align=center colspan=2>\n";
print $query -> submit (-value => "Give me my customized form");
print "</table>\n";
print $query -> endform;

print "<p>&nbsp;<p>\n";
### File addition form

$addarchives{single}   = "Single file";
$addarchives{multi}   = "Multiple files";
@addarchives = ("single","multi");

print $query -> start_multipart_form('POST',$AddFilesForm);
print "<a name=\"addform\">\n";

print "<table cellpadding=5 border=5 align=center>\n";

print "<tr><td colspan=2 align=center><big>Customized Add/Replace
Files</big><br>Use this form to produce a customized file addition form.<br>Make a
       selection from each group.</th></tr>\n";
print "<tr><td align=right>\n";
print "<a "; &HelpLink("docnumber"); 
print "<b>Update Doc #:</b></a>\n";

print "<td>\n";
 print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);

print "<tr><td align=right>\n";
print "<a "; &HelpLink("uploadtype"); 
print "<b>Upload type:</b></a>\n";
print "<td>\n";
print "<table cellpadding=3><tr><td>\n";
print $query -> radio_group(-name => "archive", -values => \@addarchives, -labels
                            => \%addarchives, -columns => 1);
print "</td><td valign=bottom>\n";
print $query -> textfield(-name => "numfile", -size => 2, -maxlength => 2);
print "<b># of files</b>\n";
print "</td></tr></table>\n";

print "<tr><td align=right>\n";
print "<a "; &HelpLink("uploadmethod"); 
print "<b>Upload method:</b></a>\n";
print "<td>\n";
print $query -> radio_group(-name => "upload", -values => \@uploads, -labels => \%uploads);

print "<tr><td align=center colspan=2>\n";
print $query -> submit (-value => "Give me my customized form");
print "</table>\n";
print $query -> endform;

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);

