#! /usr/bin/env perl

use lib ".";

#
#        Name: ModifyHome
# Description: The second "homepage" for adding documents and other metadata
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2018 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CGI qw(-nosticky);
use DBI;

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "SecuritySQL.pm";
require "Scripts.pm";
require "ResponseElements.pm";
require "FormElements.pm";
require "Messages.pm";
require "Cookies.pm";
require "Security.pm";
require "SecuritySQL.pm";
require "SecurityHTML.pm";
require "MeetingSecurityUtilities.pm";

$query = new CGI;  # Global for subroutines
$query -> autoEscape(0);
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

GetSecurityGroups();

print $query -> header( -charset => $HTTP_ENCODING );
DocDBHeader("Document Modifications","",-scripts => ["PopUps"]);
@ErrorStack = ();

if ($Public || !&CanCreate()) {
  push @ErrorStack,"You are not allowed to modify or create documents.";
}

my $PersonalAccountLink = PersonalAccountLink();

print "<div id=\"ModifyHomeBody\">\n";

EndPage(@ErrorStack);

print "<div id=\"Header3Col\">\n";
print "<h4>\n";
print "Click any <span class=\"Help\">highlighted link</span> for quick help.\n";
print "</h4>\n";
print "</div>\n";  # Header3Col

print "<div id=\"LeftColumn3Col\">\n";
print "<p><strong><a href=\"$MainPage\">Main Menu</a></strong></p>\n";
print "<p><strong><a href=\"$DocDBInstructions\">Instructions</a></strong></p>\n";
if ($PersonalAccountLink) {
  print "<p><strong>$PersonalAccountLink</strong></p>\n";
}
print "<p><strong><a href=\"#customcreate\">Customized<br/>Create/Modify</a></strong></p>\n";
print "<p><strong><a href=\"#addform\">Customized<br/>Add Files</a></strong></p>\n";
foreach my $Text (@{ $ProjectMessages{Homepage}{LeftColumn} }) {
  print "<p><strong>$Text</strong></p>\n";
}
print "<p><strong><a href=\"$DocDBHome\">About DocDB</a></strong></p>\n";
print "</div>\n";  # LeftColumn3Col

print "<div id=\"MainColumn3Col\">\n";
print "<strong>Document Management: ";
print "(".FormElementTitle(-helplink => "modifytypes", -helptext => "Which option do I choose?",
                           -nobold => $TRUE, -nocolon  => $TRUE,         -nobreak  => $TRUE).")</strong>";

### New upload short form

print "<ul>\n";
print "<li>";
print "\n",$query -> start_form('POST',$DocumentAddForm),"<div>\n";
print $query -> submit (-class => "Action", -value => "Create a new");
print " document from ";
print $query -> textfield(-name => "numfile", -size => 2, -maxlength => 2);
print " file(s) on your ";
print FormElementTitle(-helplink => "uploadmethod", -helptext => "local computer",
                       -nocolon  => $TRUE,          -nobreak  => $TRUE);
print $query -> hidden(-name => 'mode',    -default => 'add');
print $query -> hidden(-name => 'upload',    -default => 'file');
print "\n</div>\n",$query -> end_form,"\n\n";
print "</li>";

### New http short form

print "<li>";
print "\n",$query -> start_form('POST',$DocumentAddForm),"<div>\n";
print $query -> submit (-class => "Action", -value => "Create a new");
print " document from ";
print $query -> textfield(-name => "numfile", -size => 2, -maxlength => 2);
print " file(s) on the ";
print FormElementTitle(-helplink => "uploadmethod", -helptext => "web",
                       -nocolon  => $TRUE,          -nobreak  => $TRUE);
print $query -> hidden(-name => 'mode',    -default => 'add');
print $query -> hidden(-name => 'upload',    -default => 'http');
print "\n</div>\n",$query -> end_form,"\n\n";
print "</li>";

### Reserve form (button)

print "<li>";
print "\n",$query -> start_form('POST',$DocumentAddForm),"<div>\n";
print $query -> submit (-class => "Action", -value => "Reserve");
print " a document number\n";
print "(if you don't yet have a draft of your document).\n";
print $query -> hidden(-name => 'mode',    -default => 'reserve');
print "\n</div>\n",$query -> end_form,"\n\n";
print "</li>";

### Update short form

print "<li>";
print "\n",$query -> start_form('POST',$DocumentAddForm),"<div>\n";
print $query -> submit (-class => "Action", -value => "Update");
print " document # ";
print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
print $query -> hidden(-name => 'mode',    -default => 'update');
print "\n</div>\n",$query -> end_form,"\n\n";
print "</li>";

### Update DB short form

print "<li>";
print "\n",$query -> start_form('POST',$DocumentAddForm),"<div>\n";
print $query -> submit (-class => "Action", -value => "Update Metadata");
print " for document # ";
print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
print $query -> hidden(-name => 'mode',    -default => 'updatedb');
print "\n</div>\n",$query -> end_form,"\n\n";
print "</li>";

### File Add short form

print "<li>";
print "\n",$query -> start_form('POST',$AddFilesForm),"<div>\n";
print $query -> submit (-class => "Action", -value => "Add");
print " ";
print $query -> textfield(-name => "numfile", -size => 3, -maxlength => 2);
print " file(s) to document # ";
print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
#print $query -> hidden(-name => 'mode',    -default => 'updatedb');
print "\n</div>\n",$query -> end_form,"\n\n";
print "</li>";

if (CanAdminister()) { # Delete Form
  print "<li>";
  print "\n",$query -> start_form('POST',$DeleteConfirm),"<div>\n";
  print $query -> submit (-class => "Action", -value => "Delete");
  print " document # ";
  print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
  print "\n</div>\n",$query -> end_form,"\n\n";
  print "</li>";
}
print "</ul>\n";

if (CanCreateMeeting()) {
  print "<strong>Event Management</strong>\n";
  print "<ul>\n";

  ### Full meeting form

  if ($Preferences{Components}{AgendaMaker}) {
    print "<li>\n";
    print $query -> start_form('POST',$MeetingModify),"<div>\n";
    print $query -> hidden(-name => 'dummy', -default => 1);
    print $query -> submit (-class => "Action", -value => "Create");
    print " a new event with multiple sessions";
    print "\n</div>\n",$query -> end_form,"\n\n";
    print "</li>\n";

    ### Reduced meeting form

    print "<li>\n";
    print $query -> start_form('POST',$SessionModify),"<div>\n";
    print $query -> hidden(-name => 'singlesession', -default => 1);
    print $query -> hidden(-name => 'mode', -default => "new");
    print $query -> submit (-class => "Action", -value => "Create");
    print " a new event with only one session";
    print "\n</div>\n",$query -> end_form,"\n\n";
    print "</li>\n";
  }

  ### No sessions form

  print "<li>\n";
  print $query -> start_form('POST',$MeetingModify),"<div>\n";
  print $query -> hidden(-name => 'nosessions',    -default => 1);
  print $query -> submit (-class => "Action", -value => "Create");
  print " an externally managed event (e. g. a conference)";
  print "\n</div>\n",$query -> end_form,"\n\n";
  print "</li>\n";

  print "<li>Modify an  <a href=\"$ListAllMeetings?mode=modify\">existing
             event</a> (choose event on next page)</li>\n";

  print "</ul>\n";
}

print "<p><strong>Database maintenance:</strong></p>\n";
print "<ul>\n";
print "<li>Add an <a href=\"$AuthorAddForm\">author</a></li>\n";
if (CanAdminister()) {
  print "<li>Perform other <a href=\"$AdministerHome\">administration tasks</a></li>\n";
}
print "</ul>\n";


print "<hr/>\n";

### Customized Add/Update form creation form

print "<a name=\"customcreate\" />\n";

print $query -> start_form('POST',$DocumentAddForm);
#print "<div>\n";
$modes{reserve}  = "Reserve document #";
$modes{add}      = "New document";
$modes{update}   = "Update existing document";
$modes{updatedb} = "Update metadata";  # See note in ProcessDocumentAdd

@modes = ("add","reserve","update","updatedb");

$uploads{http}   = "HTTP submission";
$uploads{file}   = "Local file upload";
@uploads = ("file","http");

$archives{archive}    = "Archive (.tar/.zip) upload";
$archives{single}   = "Single file";
$archives{multi}   = "Multiple files";
@archives = ("single","multi","archive");

$topicmodes{multi}  = "Multiple Topic Boxes";
$topicmodes{single} = "Single Topic List";
$topicmodes{tree}   = "Expandable Tree";
@topicmodes = ("tree","multi","single");

$authormodes{field} = "Ordered text field";
$authormodes{list}  = "Selectable list";
$authormodes{active}  = "Active search";
@authormodes = ("list","field","active");

GetPrefsCookie();

print "<table id=\"CustomCreate\" class=\"GenCustomForm\">\n";
print "<tr><th colspan=\"2\"><big>Customized Insert/Modify</big><br/>
       Use this form to produce a
       customized document creation or update form.<br/> Make a selection from each
       group.</th></tr>\n";
print "<tr><td class=\"LeftHeader\">\n";
print FormElementTitle(-helplink => "modifytypes", -helptext => "Type of modification",
                       -nobreak  => $TRUE);
print "</td>\n";

print "<td>\n";
 print "<table class=\"CustomButtons\"><tr><td>\n";
 print $query -> radio_group(-name => "mode", -labels => \%modes, -values => \@modes, -columns => 2);
 print "</td></tr>\n";
 print "<tr><td>\n";
 print "<b>Update Doc #:</b>\n";
 print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
 print "&nbsp;&nbsp;&nbsp;\n";
 print "</td></tr>\n";
 print "</table>\n";
print "</td></tr>\n";

print "<tr><td class=\"LeftHeader\">\n";
print FormElementTitle(-helplink => "uploadtype", -helptext => "Upload type",
                       -nobreak  => $TRUE);
print "</td>\n";
print "<td>\n";
 print "<table class=\"CustomButtons\"><tr><td>\n";
 print $query -> radio_group(-name => "archive", -values => \@archives, -default => $UploadTypePref, -labels
                             => \%archives, -columns => 1);
 print "</td><td>\n";
 print $query -> textfield(-name => "numfile", -default => $NumFilesPref, -size => 2, -maxlength => 2);
 print "<b># of files</b>\n";
 print "</td></tr></table>\n";
print "</td></tr>\n";

print "<tr><td class=\"LeftHeader\">\n";
print FormElementTitle(-helplink => "uploadmethod", -helptext => "Upload method",
                       -nobreak  => $TRUE);
print "</td>\n";
print "<td>\n";
print $query -> radio_group(-name => "upload", -values => \@uploads, -default => $UploadMethodPref, -labels => \%uploads);
print "</td></tr>\n";

print "<tr><td class=\"LeftHeader\">\n";
print FormElementTitle(-helplink => "topicoption", -helptext => "Topic Selection",
                       -nobreak  => $TRUE);
print "</td>\n";
print "<td>\n";
print $query -> radio_group(-name => "topicmode", -values => \@topicmodes, -default => $TopicModePref, -labels => \%topicmodes);
print "</td></tr>\n";

print "<tr><td class=\"LeftHeader\">\n";
print FormElementTitle(-helplink => "authoroption", -helptext => "Author Selection",
                       -nobreak  => $TRUE);
print "</td>\n";
print "<td>\n";
print $query -> radio_group(-name => "authormode", -values => \@authormodes, -default => $AuthorModePref, -labels => \%authormodes);
print "</td></tr>\n";

print "<tr><td class=\"LeftHeader\">\n";
print FormElementTitle(-helplink => "dateoverride", -helptext => "Override creation date",
                       -nobreak  => $TRUE);
print "</td>\n";
print "<td>\n";
print $query -> radio_group(-name => "overdate", -values => ['No','Yes'],
                            -default => $DateOverridePref);
print "</td></tr>\n";

print "<tr><th colspan=\"2\">\n";
print $query -> submit (-value => "Give me my customized form");
print "</th></tr>\n";
print "</table>\n";
print $query -> end_form;
print "\n\n";

### File addition form

$addarchives{single}   = "Single file";
$addarchives{multi}   = "Multiple files";
@addarchives = ("single","multi");

print "<a name=\"addform\" />\n";

print $query -> start_form('POST',$AddFilesForm);
print "<table id=\"CustomAdd\" class=\"GenCustomForm\">\n";

print "<tr><th colspan=\"2\">\n";
print "<big>Customized Add/Replace Files</big><br/>\n";
print "Use this form to produce a customized file addition form.<br/>Make a
       selection from each group.</th></tr>\n";
print "<tr><td class=\"LeftHeader\">\n";
print FormElementTitle(-helplink => "docnumber", -helptext => "Update Doc #",
                       -nobreak  => $TRUE);
print "</td>\n";
print "<td>\n";
print $query -> textfield(-name => "docid", -size => 6, -maxlength => 6);
print "</td></tr>\n";

print "<tr><td class=\"LeftHeader\">\n";
print FormElementTitle(-helplink => "uploadtype", -helptext => "Upload type",
                       -nobreak  => $TRUE);
print "</td>\n";
print "<td>\n";
print "<table class=\"CustomButtons\"><tr><td>\n";
print $query -> radio_group(-name => "archive", -values => \@addarchives, -labels
                            => \%addarchives, -columns => 1);
print "</td><td>\n";
print $query -> textfield(-name => "numfile", -size => 2, -maxlength => 2);
print "<b># of files</b>\n";
print "</td></tr></table>\n";
print "</td></tr>\n";

print "<tr><td class=\"LeftHeader\">\n";
print FormElementTitle(-helplink => "uploadmethod", -helptext => "Upload method",
                       -nobreak  => $TRUE);
print "</td>\n";
print "<td>\n";
print $query -> radio_group(-name => "upload", -values => \@uploads, -labels => \%uploads);
print "</td></tr>\n";

print "<tr><th colspan=\"2\">\n";
print $query -> submit (-value => "Give me my customized form");
print "</th></tr>\n";

print "</table>\n";
print $query -> end_form;
print "\n\n";

### Right column (wrapped around by middle column)

#print "<div id=\"RightColumn3Col\">\n";
#print "</div>\n";  # RightColumn3Col

print "</div>\n";  # MainColumn3Col

print "<div id=\"Footer3Col\">\n"; # Must have to keep NavBar on true bottom
print "</div>\n";  # Footer3Col
print "</div>\n";  # ModifyHomeBody

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);

