#!/usr/bin/env perl

use lib '..';
use lib '/www/mysql/Msql-Mysql-modules-1.2216/blib/lib';
use lib '/www/mysql/Msql-Mysql-modules-1.2216/blib/arch/auto/DBD/mysql';
use CGI qw/:standard :html3/;
use CGI::Carp qw/fatalsToBrowser/;
use DBI;

# some useful variables
# some useful variables - change these for your project

$project = "BTeV";
$DOC_URL = "http://www-btev.fnal.gov/btevdocs";
$dsn = "DBI:mysql:btev_documents:fnsimu1";
$user_name = "wsrvbtev";
$passwd = "numiweb";
$database = "btev_documents";
$table = "notes";
$note_prefix = "btev";
$stylesheet = "/styles/style_x11.css";
$distribution = param('distribution');
$err_mail = "$err_mail";

print header();
print start_html(-title=>"$project Notes Current Listing",
	 -style=>{-src=>$stylesheet});
print "<BODY>\n";


# Connect to the database

if(!defined($dbh = DBI->connect($dsn,$user_name,$passwd,
				{RaiseError => 0,PrintError => 0}))) {
  $error_message = $DBI::db_errstr;
  print h1("Error");
  print h3("Error: Connect failed: $error_message");
  print("Please send mail to $err_mail with the error you encountered");
  end_html;
  exit;
}

# Get the current list of entries

if ($distribution eq "RESTRICTED") {
  $sql_sel_list = "select * from $table where distribution = 'RESTRICTED' 
order by number desc";
}
else {
  $sql_sel_list = "select * from $table order by number desc";
}

if(!defined($sth = $dbh->prepare($sql_sel_list))) {
  $error_message = $dbh->errstr;
  print h3("Error: Query preparation failed: $error_message");
  print("Please send mail to $err_mail with the error you encountered");
  end_html;
  exit;
}

# Execute the query

if(!defined($sth->execute())) {
  $error_message = $sth->errstr;
  print h3("Error: Query failed: $error_message");
  print("Please send mail to $err_mail with the error you encountered");
  end_html;
  exit;
}

# Print results

$nrec = $sth->rows;
print h1("$project Notes Current Listing");
print p;
print "Notes whose number is a link are available electronically";
print br;
print "The date for notes with a link in the date posted. For those with no link it is the date requested";
print br; 
print "For Multiple File uploads only the main document is shown";
print br;
print br;
print h3("Current listing has $nrec Notes");
print br;
print "<TABLE>\n";
print "<TR ALIGN=LEFT>\n";
print "<TH>Number</th>\n";
print "<TH>Title</th>\n";
print "<TH>Authors</th>\n";
print "<TH>Date</th>";
print "</TR>";

# Fetch the rows from the query done previously

while (@row = $sth->fetchrow_array()) {

# determine if there is an electronic file posted

  if ($row[13] ne "") {
    
    $note_number = $row[0];
    if ($row[7] eq "PUBLIC")
      {
	$dist_dir = "public";
      }
    elsif ($row[7] eq "RESTRICTED")
      {
	$dist_dir = "restricted";
      }
    $doc_type = $row[8];
    $this_dir = sprintf "%s%.4d",$note_prefix,$note_number;
    if ($doc_type eq "ps") {
      $file = sprintf "%s/%s/%s/%s%.4d.%s.gz",$dist_dir,$doc_type,$this_dir,
      $note_prefix,$note_number,$doc_type;
    }
    else {
      $file = sprintf "%s/%s/%s/%s%.4d.%s",$dist_dir,$doc_type,$this_dir,
      $note_prefix,$note_number,$doc_type;
    }

    $url = "$DOC_URL/$file";
    print "<TR ALIGN=LEFT VALIGN=TOP>\n";
    print "<TD><a href=\"$url\">$row[0]</a></td>\n";
    print "<TD><b>$row[1]</b></td>\n";
    print "<TD>$row[2]</td>\n";
    print "<TD>$row[11]</td>\n";
    print "</TR>\n";

  }
else {
  print "<TR ALIGN=LEFT VALIGN=TOP>\n";
  print "<TD>$row[0]</td>\n";
  print "<TD><b>$row[1]</b></td>\n";
  print "<TD>$row[2]</td>\n";
  print "<TD>$row[10]</td>\n";
  print "</TR>\n";
}

}

print "</TABLE>\n";


print "</BODY>\n";
end_html;







