#! /usr/bin/perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#
# 
#

use CGI;                                                                                      
use DBI;

require "ResponseElements.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);
$query = new CGI;  # Global for subroutines

&GetAuthors;
&GetTopics;

%params = $query -> Vars;

print $query->header;
print $query->start_html(-title=>"BTeV Document Reservation Results");

my $document_insert = $dbh->prepare("insert into Document (DocumentID,
                                      RequesterID, RequestDate, DocumentType) 
                                      values (0,?,NOW(),?)");
my $doc_rev_insert = $dbh->prepare("insert into DocumentRevision (DocRevID,
                                      DocumentID, SubmitterID, DocumentTitle,
                                      PublicationInfo, VersionNumber, Abstract, 
                                      Private) values (0,?,?,?,?,?,?,?)");
my $rev_author_insert = $dbh->prepare("insert into RevisionAuthor (RevAuthorID,
                                      DocRevID, AuthorID) 
                                      values (0,?,?)");
my $rev_topic_insert  = $dbh->prepare("insert into RevisionTopic  (RevTopicID,
                                      DocRevID, MinorTopicID) 
                                      values (0,?,?)");

#foreach $key (keys %params) {
#  print "$key $params{$key} <p>\n";
#}

#$single_handle = $query->upload("single_upload");
#while (<$single_handle>) {
# print;
#}

@error_stack = ();

unless ($params{requestor}) {
  push @error_stack,"You must supply a requestor for this document.";
}
unless ($params{authors}) {
  push @error_stack,"You must supply at least one author for this document.";
}
unless ($params{topics}) {
  push @error_stack,"You must supply at least one topic for this document.";
}
unless ($params{title}) {
  push @error_stack,"You must supply a title for this document.";
}

unless ($params{doctype}) {
  push @error_stack,"You must supply a document type for this document.";
}

if (($#error_stack + 1)) {
  &EndPage(@error_stack);
}

@authorIDs = split ("\0",$params{authors}); #Later below dropouts
@topicIDs  = split ("\0",$params{topics});




$document_insert -> execute($params{requestor},$params{doctype});
my $documentID = $document_insert -> {insertid}; # Works with MySQL only
my $version   = 0;
$doc_rev_insert -> execute($documentID,$params{requestor},$params{title},
                           $params{pubinfo},$version,$params{abstract},
                           $params{private});
my $docRevID = $doc_rev_insert -> {insertid}; # Works with MySQL only
                           

foreach $authorID (@authorIDs) {
  $rev_author_insert -> execute($docRevID,$authorID);
}
foreach $topicID (@topicIDs) {
  $rev_topic_insert -> execute($docRevID,$topicID);
}
   
print "Your Document ID is: <b>BTeV-doc-$documentID</b><p>\n"; 

&AuthorListByID(@authorIDs);
&TopicListByID(@topicIDs);

print $query->end_html;

sub EndPage {
  @errors = @_;
  print "<b>There was an error processing your request:</b><br>\n";
  foreach $message (@errors) {
    print "<dt><b>$message </b>\n";
  }  
  exit;
}
