#! /usr/bin/perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#
# 
#

use CGI;                                                                                      
use DBI;

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:BTeVDocTest:vchipp.phy.vanderbilt.edu','docadmin','docadmin');

%params = $query -> Vars;

print $query->header;
print $query->start_html(-title=>"BTeV Document Reservation Results");

foreach $key (keys %params) {
  print "$key $params{$key} <p>\n";
}
my $document_insert = $dbh->prepare("insert into Document (DocumentID,
                                      RequesterID, RequestDate, DocumentType) 
                                      values (0,?,NOW(),?)");
my $doc_rev_insert = $dbh->prepare("insert into DocumentRevision (DocRevID,
                                      DocumentID, SubmitterID, DocumentTitle,
                                      PublicationInfo, VersionNumber, Abstract, 
                                      Private) values (0,?,?,?,?,?,?,?)");
my $rev_author_insert = $dbh->prepare("insert into RevisionAuthor (RevAuthorID,
                                      DocRevID, AuthorID) 
                                      values (0,?,?)");
my $rev_topic_insert  = $dbh->prepare("insert into RevisionTopic  (RevTopicID,
                                      DocRevID, MinorTopicID) 
                                      values (0,?,?)");

unless ($params{requestor}) {
  &EndPage("You must supply a requestor for this document");
}
unless ($params{title}) {
  &EndPage("You must supply a title for this document");
}

unless ($params{doctype}) {
  &EndPage("You must supply a document type for this document");
}


$document_insert -> execute($params{requestor},$params{doctype});
my $documentID = $document_insert -> {insertid}; # Works with MySQL only
my $version   = 0;
$doc_rev_insert -> execute($documentID,$params{requestor},$params{title},
                           $params{pubinfo},$version,$params{abstract},
                           $params{private});
my $docRevID = $doc_rev_insert -> {insertid}; # Works with MySQL only
                           
@authorIDs = split ("\0",$params{authors});
@topicIDs  = split ("\0",$params{topics});

foreach $authorID (@authorIDs) {
  $rev_author_insert -> execute($docRevID,$authorID);
}
foreach $topicID (@topicIDs) {
  $rev_topic_insert -> execute($docRevID,$topicID);
}
   
print "Your Document ID is: $documentID"; 

print $query->end_html;

sub EndPage {
  ($message) = @_;
  print "<b>There was an error processing your request:<br>\n";
  print "<dt>$message </b>\n";
  exit;
}
