#! /usr/bin/perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#
# 
#

use CGI;                                                                                      
use DBI;

require "ResponseElements.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);

&GetAuthors;
&GetTopics;

%params = $query -> Vars;
$mode = $params{mode};

print $query->header;
print $query->start_html(-title=>"BTeV Document Reservation Results");

if ($mode ne "add" && $mode ne "reserve") {
  &EndPage("<p><h3>You accessed this page without 
            specifying a required parameter. 
            Don't mess with hidden fields or 
            try to access this page directly.</h3>\n"); 
}  
if      ($mode eq "add") {
  print "<p><h3>Here are the results of your attempt to add a document
                into the BTeV document database:</h3><p>\n";
} elsif ($mode eq "reserve") {              
  print "<p><h3>Here are the results of your attempt to reserve a document
                number in the BTeV document database:</h3><p>\n";
}

my $document_insert = $dbh->prepare("
insert into Document 
       (DocumentID, RequesterID, RequestDate, DocumentType) 
values (0,          ?,           NOW(),       ?)");
            
my $doc_rev_insert = $dbh->prepare("
insert into DocumentRevision 
       (DocRevID, DocumentID, SubmitterID, DocumentTitle, PublicationInfo, 
        VersionNumber, Abstract, Security, RevisionDate) 
values (0,?,?,?,?,?,?,?,NOW())");
            
my $rev_author_insert =  $dbh->prepare("
insert into RevisionAuthor 
       (RevAuthorID, DocRevID, AuthorID) 
values (0,           ?,        ?)");
                                 
my $rev_topic_insert = $dbh->prepare("
insert into RevisionTopic  
       (RevTopicID, DocRevID, MinorTopicID) 
values (0,          ?,        ?)");

my $file_insert = $dbh->prepare("
insert into DocumentFile   
       (DocFileID, DocRevID, FileName, Date, URL, RootFile) 
values (0,         ?,        ?,        NOW(),?,   ?)");

@error_stack = ();

unless ($params{requestor}) {
  push @error_stack,"You must supply a requestor for this document.";
}
unless ($params{title}) {
  push @error_stack,"You must supply a title for this document.";
}
unless ($params{doctype}) {
  push @error_stack,"You must supply a document type for this document.";
}
if ($mode eq "add") {
  unless ($params{authors}) {
    push @error_stack,"You must supply at least one author for this document.";
  }
  unless ($params{topics}) {
    push @error_stack,"You must supply at least one topic for this document.";
  }
  unless ($params{abstract}) {
    push @error_stack,"You must supply an abstract for this document.";
  }
  unless ($params{single_upload}) {
    push @error_stack,"You must supply a file for this document.";
  }
}

if (($#error_stack + 1)) {
  &EndPage(@error_stack);
}

# OK, we've validated the inputs are all there. Now add info to database

@authorIDs  = split ("\0",$params{authors}); 
@topicIDs   = split ("\0",$params{topics});
@securities = split ("\0",$params{security});

$security_list = join ',',@securities; # Ready for MySQL

$document_insert -> execute($params{requestor},$params{doctype});
my $documentID = $document_insert -> {insertid}; # Works with MySQL only

my $version;
if      ($mode eq "reserve") {
  $version   = 0;
} elsif ($mode eq "add") {
  $version   = 1;
}

$doc_rev_insert -> execute($documentID,$params{requestor},$params{title},
                           $params{pubinfo},$version,$params{abstract},
                           $security_list);
my $docRevID = $doc_rev_insert -> {insertid}; # Works with MySQL only
                           
foreach $authorID (@authorIDs) {
  $rev_author_insert -> execute($docRevID,$authorID);
}
foreach $topicID (@topicIDs) {
  $rev_topic_insert -> execute($docRevID,$topicID);
}

# Figure out directory names and make directories

if ($mode eq "add") {
  $hun_dir = sprintf "%4.4d/",int($documentID/100);
  $sub_dir = sprintf "%6.6d/",$documentID;
  $ver_dir = sprintf "%3.3d/",$version;
  $new_dir = $file_root.$hun_dir.$sub_dir.$ver_dir;

  mkdir  $file_root.$hun_dir;
  mkdir  $file_root.$hun_dir.$sub_dir;
  mkdir  $file_root.$hun_dir.$sub_dir.$ver_dir;

# Copy file to directory

  $short_file   = $query ->  param("single_upload");
  $short_handle = $query -> upload("single_upload");

  open (OUTFILE,">$new_dir/$short_file");
  while ($bytes_read = read($short_handle,$buffer,1024)) {
    print OUTFILE $buffer
  }
  close OUTFILE;

# Insert into database
  $rootfile = 1;
  $url = $web_root.$hun_dir.$sub_dir.$ver_dir.$short_file; # Not needed?
  $file_insert -> execute($docRevID,$short_file,$url,$rootfile);
}

# Output feedback to the user

print "Your Document ID is <b>BTeV-doc-$documentID</b><br> 
       which was created with the following information.<br>
       Please make a note of the document number as you will
       need it to update your document.<p>\n"; 

&RequestorByID($params{requestor});
&AuthorListByID(@authorIDs);
&TopicListByID(@topicIDs);
&PrintAbstract($params{abstract});

print $query->end_html;

