#! /usr/bin/perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;
use DBI;

require "ResponseElements.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";
require "FSUtilities.pm";
require "Security.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);

#&GetAuthors;
&GetTopics;

%params = $query -> Vars;
$mode = $params{mode};

print $query->header;
print $query->start_html(-title=>"BTeV Document Reservation Results");

if ($mode ne "add"    && $mode ne "reserve" && 
    $mode ne "update" && $mode ne "updatedb") {
  &EndPage("<p><h3>You accessed this page without 
            specifying a required parameter. 
            Don't mess with hidden fields or 
            try to access this page directly.</h3>\n"); 
}  

if      ($mode eq "add") {
  print "<p><h3>Here are the results of your attempt to add a document
                into the BTeV document database:</h3><p>\n";
} elsif ($mode eq "reserve") {              
  print "<p><h3>Here are the results of your attempt to reserve a document
                number in the BTeV document database:</h3><p>\n";
} elsif ($mode eq "update") {              
  print "<p><h3>Here are the results of your attempt to update a document
                in the BTeV document database:</h3><p>\n";
}

my $document_insert = $dbh->prepare(
   "insert into Document ".
          "(DocumentID, RequesterID, RequestDate, DocumentType) ". 
   "values (0,          ?,           NOW(),       ?)");
            
my $doc_rev_insert = $dbh->prepare(
   "insert into DocumentRevision ".
   "(DocRevID, DocumentID, SubmitterID, DocumentTitle, PublicationInfo, ". 
   " VersionNumber, Abstract, Security, RevisionDate) ". 
   "values (0,?,?,?,?,?,?,?,NOW())");
            
my $rev_author_insert =  $dbh->prepare(
   "insert into RevisionAuthor ".
   "       (RevAuthorID, DocRevID, AuthorID) ".
   "values (0,           ?,        ?)");
                                 
my $rev_topic_insert = $dbh->prepare(
   "insert into RevisionTopic ".
   "       (RevTopicID, DocRevID, MinorTopicID) ".
   "values (0,          ?,        ?)");

my $file_insert = $dbh->prepare(
   "insert into DocumentFile ".
   "       (DocFileID, DocRevID, FileName, Date, RootFile) ".
   "values (0,         ?,        ?,        NOW(),?)");

my $file_copyinsert = $dbh->prepare(
   "insert into DocumentFile ".
   "       (DocFileID, DocRevID, FileName, Date, RootFile) ".
   "values (0,         ?,        ?,        ?,    ?)");

@error_stack = ();

unless ($params{requester}) {
  push @error_stack,"You must supply a requester for this document.";
}
unless ($params{title}) {
  push @error_stack,"You must supply a title for this document.";
}
if ($mode eq "add" || $mode eq "reserve") {
  unless ($params{doctype}) {
    push @error_stack,"You must supply a document type for this document.";
  }
}
if ($mode eq "add" || $mode eq "update") {
  unless ($params{authors}) {
    push @error_stack,"You must supply at least one author for this document.";
  }
  unless ($params{topics}) {
    push @error_stack,"You must supply at least one topic for this document.";
  }
  unless ($params{abstract}) {
    push @error_stack,"You must supply an abstract for this document.";
  }
  unless ($params{single_upload} || $params{single_http}) {
    push @error_stack,"You must supply a file for this document.";
  }
  if     ($params{single_upload} && $params{single_http}) {
    push @error_stack,"You may not specify both URL and file upload.";
  }
}

#FIXME: Check for valid URL, user, password


# OK, we've validated the inputs are all there. Now add info to database

@authorIDs  = split ("\0",$params{authors}); 
@topicIDs   = split ("\0",$params{topics});
@securities = split ("\0",$params{security});

$security_list = join ',',@securities; # Ready for MySQL
if ($security_list eq "Public") {$security_list = "";}
if (grep /Public/,$security_list) {
  push @error_stack,"You selected \"Public\" and another form of security. ".
                    "You may only select \"Public\" by itself.";
}
  
if (($#error_stack + 1)) {
  &EndPage(@error_stack);
}

my $documentID;
if ($mode eq "reserve" || $mode eq "add") {
  $document_insert -> execute($params{requester},$params{doctype});
  $documentID = $document_insert -> {mysql_insertid}; # Works with MySQL only
} else {
  $documentID = $params{docid};
}  

my $version;
if      ($mode eq "reserve") {
  $version   = 0;
} elsif ($mode eq "add") {
  $version   = 1;
} elsif ($mode eq "update") {
  &FetchDocument($documentID);
  $version   = $Documents{$documentID}{NVER} + 1;
} elsif ($mode eq "updatedb") {
  &FetchDocument($documentID);
  $version   = $Documents{$documentID}{NVER};
}

if ($mode eq "updatedb") { # New Document revision replaces old
 # Fetch old DocumentRevision
  $oldRevID = &FetchDocRevision($documentID,$version);
 # Mark it obsolete
  my $obsolete_revision = $dbh->prepare(
     "update DocumentRevision set Obsolete=1 where DocRevID=?");
  $obsolete_revision -> execute($oldRevID); 
}  

$doc_rev_insert -> execute($documentID,$params{requester},$params{title},
                           $params{pubinfo},$version,$params{abstract},
                           $security_list);
my $docRevID = $doc_rev_insert -> {mysql_insertid}; # Works with MySQL only
                           
foreach $authorID (@authorIDs) {
  $rev_author_insert -> execute($docRevID,$authorID);
}
foreach $topicID (@topicIDs) {
  $rev_topic_insert -> execute($docRevID,$topicID);
}

if ($mode eq "updatedb") { # New Document revision replaces old
  # Redo security on the directory
  &ProtectDirectory($documentID,$version,@securities);
  # Copy DocumentFile entries
  my $file_list = $dbh->prepare(
    "select FileName,Date,RootFile ".
    "from DocumentFile ".
    "where DocRevID=?");
  my $file_copyinsert = $dbh->prepare(
    "insert into DocumentFile ".
    "       (DocFileID, DocRevID, FileName, Date, RootFile) ".
    "values (0,         ?,        ?,        ?,    ?)");

  $file_list -> execute($oldRevID);
  $file_list -> bind_columns(undef, \($FileName,$Date,$RootFile));
  while ($file_list -> fetch) {
    $file_copyinsert -> execute($docRevID,$FileName,$Date,$RootFile);
  }  
}  

if ($mode eq "add" || $mode eq "update") { # We're adding a new files
  
  $new_dir = &MakeDirectory($documentID,$version);
  &ProtectDirectory($documentID,$version,@securities);

  if ($params{single_upload}) { # Copy file to directory
    $short_file   = $query ->  param("single_upload");
    $short_handle = $query -> upload("single_upload");
    if (grep /\\/,$short_file) {
      $short_file = &WindowsBaseFile($short_file);
    }  
    if (grep /\//,$short_file) {
      $short_file = &UnixBaseFile($short_file);
    }  
    
    open (OUTFILE,">$new_dir/$short_file");
    while ($bytes_read = read($short_handle,$buffer,1024)) {
      print OUTFILE $buffer
    }
    close OUTFILE;
  } elsif ($params{single_http}) {
    @url_parts = split /\//,$params{single_http};
    $short_file = pop @url_parts;
    if ($params{http_user} && $params{http_pass}) {
      $authentication = " --http-user $params{http_user} --http-pass $params{http_pass} ";
    } else {
      $authentication = "";
    }  
    $command = $Wget.$authentication.$params{single_http};
    @lines = `$command`;
    open (OUTFILE,">$new_dir/$short_file");
    print OUTFILE @lines;
    close OUTFILE;
  } 

# Insert into Files database
  $rootfile = 1;
  $file_insert -> execute($docRevID,$short_file,$rootfile);
}

# Output feedback to the user

if ($mode = "updatedb") { # Local DB not in sync, so lets clear it
  %DocRevIDs = ();
  %DocRevisions = ();
  %Documents = ();
  @DocumentIDs = ();
}


$full_docid = &FullDocumentID($documentID);

print "You were successful. Your Document ID is <b>$full_docid, version
       $version</b><br>  Please make a note of the document number as you
       will need it to update your document.<br> Your entry was created with
       the following information: <p>\n"; 

my $DocRevID   = &FetchDocRevision($documentID,$version);

unless ($DocRevID) {
  print "This document does not exist.<p>\n";
  exit;
}

&PrintRevisionInfo($DocRevID);

&OtherVersionLinks($documentID,$version);

print $query->end_html;

