#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;
use DBI;

require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "MySQLAccess.pm";
require "FSUtilities.pm";
require "HTMLUtilities.pm";
require "Security.pm";

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

@error_stack = ();
@warn_stack  = ();

$DocumentID = $params{docid};
unless ($DocumentID) {
  push @error_stack,"You are must supply a document number!";
}  
$FileName   = $params{filename};

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);
&GetSecurityGroups;
&FetchDocument($DocumentID);

if ($params{version} eq "0") { # Options are undefined, 0, and non-zero.
  $Version = 0;
} else {
  if ($params{version}) {
    $Version    = $params{version};
  } else {   
    $Version = $Documents{$DocumentID}{NVER};
  }
}

unless (&CanAccess($DocumentID,$Version)) {
  push @error_stack,"You are not authorized to view this document.";
}  

my $DocRevID   = &FetchRevisionByDocumentAndVersion($DocumentID,$Version);

unless ($DocRevID) {
  push @error_stack,"This document does not exist.";
}
  
if ($FileName) {
  $FullFile = &FullFile($DocumentID,$Version,$FileName);
  $FullURL = &GetURLDir($DocumentID,$Version).CGI::escape($FileName);
} else {
  &FetchDocFiles($DocRevID);
  my $NMains = 0;
  my $LastMain = "";
  foreach my $DocFileID (keys %DocFiles) {
    if ($DocFiles{$DocFileID}{DOCREVID} == $DocRevID &&
        $DocFiles{$DocFileID}{ROOT}) {
      ++$NMains;
      $LastMain = $DocFiles{$DocFileID}{NAME};
    } 
  }
  if ($NMains == 1) {
    $FullFile = &FullFile($DocumentID,$Version,$LastMain);
    $FullURL = &GetURLDir($DocumentID,$Version).CGI::escape($LastMain);
  } elsif ($NMains > 1) {
    push @warn_stack,"More than one file was found. Please select one below.";
  } else {
    push @warn_stack,"No files were found. Document info is below.";
  }  
}    

unless (-e $FullFile) {
  push @warn_stack,"No appropriate file was found.";
}

if ($FullURL) {
  print $query -> redirect(-location => $FullURL, -method => 'GET');
} else {
  print $query->header;
}

&BTeVHeader("File Retrieve Results"); 

if (@warn_stack) {
  &WarnPage(@warn_stack);
  @warn_stack = ();
}
if (@error_stack) {  # The user made one or more mistakes, warn and exit
  &EndPage(@error_stack);
}

&PrintRevisionInfo($DocRevID);

&DocDBNavBar;
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
