#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#


# Copyright 2001-2005 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "FormElements.pm";
require "SearchFormElements.pm";
require "Scripts.pm";
require "Sorts.pm";
require "AuthorSQL.pm";
require "TopicSQL.pm";
require "SecuritySQL.pm";
require "MiscSQL.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";
require "MeetingHTML.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetAuthors;
&GetTopics;
&GetSecurityGroups;
&GetJournals;
&GetDocTypes;

%params = $query -> Vars;

print $query->header;
  
&DocDBHeader("$Project Document Database Search","Document Database Search",
             -search => $TRUE, -scripts => ["PopUps","TopicChooser"]);

@ErrorStack = ();

if ((@ErrorStack)) {  # The user made one or more mistakes, warn and exit
  &EndPage(@ErrorStack);
}

print $query -> start_multipart_form('POST',$Search,"name=\"queryform\"");


print "<h4>Click on any of the <span class=\"Help\">highlighted headings</span> for help.</h4>\n";

print "<table id=\"SearchFormTable\" class=\"HighPaddedTable CenteredTable\">\n";
print "<tr>\n";
 print "<td colspan=\"3\" class=\"SubmitCell\">\n"; 
 print $query -> submit (-value => "Search for Documents");     
 print "&nbsp;&nbsp;&nbsp;\n";
 print $query -> reset (-value => "Reset Search Form");     
 print "</td>\n";
print "</tr>\n";

print "<tr>\n";
 print "<td colspan=\"3\" class=\"SubmitCell\">\n";
 &LogicTypeButtons; 
 print "</td>\n";
print "</tr>\n";
print "<tr>\n";
 print "<td colspan=\"3\" class=\"SubmitCell\">\n";
 &ModeSelect; 
print "</tr>\n";

print "<tr>\n";
 print "<td colspan=\"3\">\n"; 

  print "<table>\n";
   &TitleSearchBox;    
   &AbstractSearchBox;    
   &KeywordsSearchBox;    
   &RevisionNoteSearchBox;    
   &PubInfoSearchBox;    
   &FileNameSearchBox;    
   &DescriptionSearchBox;
   if ($ContentSearch) {    
     &ContentSearchBox;
   }      
  print "</table>\n";

 print "</td>\n";
#&ReferenceForm;  
print "</tr>\n";


 print "<tr>\n";
  print "<td>\n"; &RequesterSearchBox; print "</td>\n"; # FIXME: Move to AuthorScroll
  print "<td>\n"; 
   &AuthorScroll(-helplink => "author",
                 -multiple => "true");
  print "</td>\n";
  print "<td>\n"; &DocTypeMulti;       print "</td>\n";
 print "</tr>\n";
 
 print "<tr>\n";
  print "<td colspan=\"3\">\n";
  print "<dl>\n";
  print "<dt><b><a ";
  &HelpLink("beforeafterdate");
  print "Last Modified Between:</a></b><p>\n";
  print "<dd>\n";
  &DateRangePullDown;
  print "</dl>\n";
  print "</td>\n";
 print "</tr>\n";

 print "<tr>\n";
  &MajorMinorSelect;
 print "</tr>\n";

 print "<tr>\n";
 print "<td>\n";
  &EventGroupSelect(-multiple => $TRUE);
 print "</td>\n";
 print "<td colspan=\"2\">\n";
  &EventSelect(-multiple => $TRUE, -format => "full");
 print "</td>\n";
 print "</tr>\n";

 print "<tr>\n";
  print "<td colspan=\"3\" class=\"SubmitCell\">\n"; 
  print $query -> submit (-value => "Search for Documents");     
  print "&nbsp;&nbsp;&nbsp;\n";
  print $query -> reset (-value => "Reset Search Form");     
  print "</td>\n";
 print "</tr>\n";

print "</table>\n";

print $query -> end_multipart_form;

&DocDBNavBar();
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
