#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "FormElements.pm";
require "SearchFormElements.pm";
require "Scripts.pm";
require "Sorts.pm";
require "MySQLAccess.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetAuthors;
&GetTopics;
&GetSecurityGroups;
&GetJournals;
&GetDocTypes;

%params = $query -> Vars;

print $query->header;
  
&SearchHeader("BTeV Document Database Search","Document Database Search");
&HelpPopupScript;
&TopicSearchScript;

@error_stack = ();

if ((@error_stack)) {  # The user made one or more mistakes, warn and exit
  &EndPage(@error_stack);
}

print $query -> start_multipart_form('POST',$Search,"name=\"queryform\"");


print "<center><table cellpadding=10 width=80%>\n";
print "<tr>\n";
 print "<td colspan=3>\n";
 print "<center><b>Click on any of the <font color=red>red headings</font> for help.</b></center>\n"; 
 print "</td>\n";
print "</tr></table><p>\n";

print "<center><table cellpadding=10 border=5><tr><td><table cellpadding=10>\n";
print "<tr>\n";
 print "<td colspan=3 align=center>\n"; 
 print $query -> submit (-value => "Search for Documents");     
 print "&nbsp;&nbsp;&nbsp;\n";
 print $query -> reset (-value => "Reset Search Form");     
 print "</td>\n";
print "</tr>\n";

print "<tr>\n";
 print "<td colspan=3 align=center>\n";
 &LogicTypeButtons; 
 print "</td>\n";
print "</tr>\n";
print "<tr>\n";
 print "<td colspan=3 align=center>\n";
 &ModeSelect; 
print "</tr>\n";

print "<tr>\n";
 print "<td colspan=3>\n"; 

  print "<table cellpadding=2>\n";
   &TitleSearchBox;    
   &AbstractSearchBox;    
   &KeywordsSearchBox;    
   &PubInfoSearchBox;    
   &FileNameSearchBox;    
   &DescriptionSearchBox;    
  print "</table>\n";

 print "</td>\n";
#&ReferenceForm;  
print "</tr>\n";


 print "<tr valign=top>\n";
  print "<td>\n"; &RequesterSearchBox; print "</td>\n";
  print "<td>\n"; &AuthorSelect;       print "</td>\n";
  print "<td>\n"; &DocTypeMulti;       print "</td>\n";
 print "</tr>\n";
 
 print "<tr>\n";
  print "<td valign=top colspan=3>\n";
  print "<dl>\n";
  print "<dt><b><a ";
  &HelpLink("beforeafterdate");
  print "Last Modified Between:</a></b><p>\n";
  print "<dd>\n";
  &DateRangePullDown;
  print "</dl>\n";
  print "</td>\n";
 print "</tr>\n";

 print "<tr valign=bottom>\n";
  &MajorMinorSelect;
 print "</tr>\n";

 print "<tr>\n";
  print "<td colspan=3 align=center>\n"; 
  print $query -> submit (-value => "Search for Documents");     
  print "&nbsp;&nbsp;&nbsp;\n";
  print $query -> reset (-value => "Reset Search Form");     
  print "</td>\n";
 print "</tr>\n";

print "</table></td></tr></table><p>\n";

  

print "</center><p>";
print $query -> end_multipart_form;

&DocDBNavBar();
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
