#! /usr/bin/env perl

use lib ".";

#
#        Name: SearchForm
# Description: Build the input form for the "Advanced" (formerly normal) DocDB Search
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#

# Copyright 2001-2018 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CGI qw(-nosticky);
use DBI;

require "DocDBGlobals.pm";
require "FormElements.pm";
require "SearchFormElements.pm";
require "Scripts.pm";
require "Sorts.pm";
require "AuthorSQL.pm";
require "TopicSQL.pm";
require "SecuritySQL.pm";
require "MiscSQL.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";
require "MeetingHTML.pm";

$query = new CGI;  # Global for subroutines
$query -> autoEscape(0);
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

GetAuthors();
GetTopics();
GetSecurityGroups();
GetJournals();
GetDocTypes();

print $query -> header( -charset => $HTTP_ENCODING );

DocDBHeader("$Project Document Database Search","Document Database Search",
            -search => $TRUE, -scripts => ["PopUps","EventChooser"]);


print "<h4>Click on any of the <span class=\"Help\">highlighted headings</span> for help.</h4>\n";
print "<h4><a href=\"$XSearch\">Search</a> other DocDB installations</h4>\n";

# Quick search table

print $query -> start_multipart_form('POST',$Search,"name=\"simplesearch\"");
print '<table id="QuickSearchForm" class="SearchFormTable LowPaddedTable CenteredTable"><tr><td>';
print FormElementTitle(-helplink => "quicksearch", -nobreak => $TRUE,
                       -helptext => "Search for", );
print "</td><td>\n";
print $query -> textfield(-size => 40, -name => "simpletext");
print $query -> hidden(-name => "simple", -default => '1');
print "</td><td>\n";
print $query -> submit (-class => "Action", -value => "Quick Search");
print "</td></tr></table>\n";
print $query -> end_multipart_form;

print "<hr/>\n";

# Advanced search table

print $query -> start_multipart_form('POST',$Search,"name=\"queryform\"");
print "<table class=\"SearchFormTable HighPaddedTable CenteredTable\">\n";
print "<tr>\n";
 print "<td colspan=\"3\" class=\"SubmitCell\">\n";
 print '<a name="Advanced"></a>';
 print $query -> submit (-value => "Advanced Search");
 print "&nbsp;&nbsp;&nbsp;\n";
 print $query -> reset (-value => "Reset Search Form");
 print "</td>\n";
print "</tr>\n";

print "<tr>\n";
 print "<td colspan=\"3\" class=\"SubmitCell\">\n";
 LogicTypeButtons();
 print "</td>\n";
print "</tr>\n";
print "<tr>\n";
 print "<td colspan=\"3\" class=\"SubmitCell\">\n";
 ModeSelect();
print "</td></tr>\n";

print "<tr>\n";
 print "<td colspan=\"3\">\n";

  print "<table class=\"LowPaddedTable LeftHeader\">\n";
   TitleSearchBox();
   AbstractSearchBox();
   KeywordsSearchBox();
   RevisionNoteSearchBox();
   PubInfoSearchBox();
   FileNameSearchBox();
   DescriptionSearchBox();
   if ($ContentSearch) {
     ContentSearchBox();
   }
  print "</table>\n";

 print "</td>\n";
#&ReferenceForm;
print "</tr>\n";


 print "<tr>\n";

 print "<td>\n"; # Requester
 AuthorScroll(-helplink => "requestersearch", -helptext => "Last Updated By:",
              -name     => "requestersearch", -multiple => $TRUE);
 print "</td>\n";

 print "<td>\n"; # Authors
 AuthorScroll(-helplink => "authors", -multiple => $TRUE);
 print "</td>\n";

 print "<td>\n";
 AuthorTextEntry( {-helplink => "authortextsearch"} );
 print "</td>\n";

 print "</tr>\n";

 print "<tr>\n";
 print "<td>\n"; DocTypeMulti();       print "</td>\n";
  print "<td colspan=\"2\">\n";
  print "<dl>\n";
  print "<dt>";
  print FormElementTitle(-helplink => "beforeafterdate", -helptext => "Last Modified Between");
  print "</dt><dd>\n";
  DateRangePullDown();
  print "</dd></dl>\n";
  print "</td>\n";
 print "</tr>\n";

 print "<tr><td colspan=\"3\">\n";
  TopicScroll({ -multiple => $TRUE, -helplink => "searchtopic", });
 print "</br>\n";
 print $query -> checkbox(-name  => "includesubtopics", -checked => 'checked',
                          -label => "Include sub-topics");
 print "</td></tr>\n";

 print "<tr>\n";
 print "<td>\n";
  EventGroupSelect( {-multiple => $TRUE, -onchange => "selectEvent(this.form);"} );
 print "</td>\n";
 print "<td colspan=\"2\">\n";
  EventSelect( {-multiple => $TRUE, -format => "full"} );
 print "</td>\n";
 print "</tr>\n";

 print "<tr>\n";
  print "<td colspan=\"3\" class=\"SubmitCell\">\n";
  print $query -> submit (-value => "Advanced Search");
  print "&nbsp;&nbsp;&nbsp;\n";
  print $query -> reset (-value => "Reset Search Form");
  print "</td>\n";
 print "</tr>\n";
print "</table>\n";
print $query -> end_multipart_form;

DocDBNavBar();
DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
