#! /usr/bin/env perl
#
#        Author:  Eric Vaandering
#          Date:  22 May 2005
#
# Allow a user to choose to limit their membership to certain groups 
# for a period of time

use CGI;
use DBI;

use constant TRUE  => 1;
use constant FALSE => 0;

require "DocDBGlobals.pm";
require "Messages.pm";
require "HTMLUtilities.pm";
require "ResponseElements.pm";
require "SecurityHTML.pm";
require "Security.pm";

# Start page
$query  = new CGI;
%params = $query -> Vars; 
$dbh    = DBI -> connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

print $query->header;
&DocDBHeader(-nobody => $TRUE);
&EndPage(@ErrorStack);

my @RawGroupIDs = &FindUsersGroups(-ignorecookie => $TRUE);

&SecurityScroll(-multiple => $TRUE, -groupids => \@RawGroupIDs);

my @Times = ("session",1,7,30,365);
my %Labels = ("session" => "During this session", 
                      1 => "One day",
                      7 => "One week",
                     30 => "One month",
                    365 => "One year");
                    
print $query -> popup_menu (-name   => 'filecontsearchmode', 
                            -values => \@Times,
                            -labels => \%Labels);

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
