#! /usr/bin/env perl

use lib ".";

#
#        Name: $RCSfile$
# Description: Main page for selecting various user-level preferences
#
#    Revision: $Revision$
#    Modified: $Author$ on $Date$
#
#      Author: Adam Bryant

# Copyright 2001-2013 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CGI qw(-nosticky);
use DBI;

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "SecuritySQL.pm";
require "Scripts.pm";
require "ResponseElements.pm";
require "Cookies.pm";
require "FormElements.pm";
require "Sorts.pm";
require "AuthorSQL.pm";

require "AuthorHTML.pm";

# Start page

$query = new CGI;
$query -> autoEscape(0);
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);
GetAuthors();
print $query -> header( -charset => $HTTP_ENCODING );
DocDBHeader("Select Preferences","",-scripts => ["PopUps"]);

print $query -> start_multipart_form('POST',$SetPrefs);

$uploads{http}   = "HTTP submission";
$uploads{file}   = "Local file upload";
@uploads = ("file","http");

$archives{archive} = "Archive (.tar/.zip) upload";
$archives{single}  = "Single file";
$archives{multi}   = "Multiple files";
@archives = ("single","multi","archive");

$topicmodes{multi}  = "Multiple Topic Boxes";
$topicmodes{single} = "Single Topic List";
$topicmodes{tree}   = "Expandable Tree";
@topicmodes = ("tree","multi","single");

$authormodes{field} = "Ordered text field";
$authormodes{list}  = "Selectable list";
$authormodes{active}  = "Active search";
@authormodes = ("list","field","active");

GetPrefsCookie();

print qq{
 <table class="MedPaddedTable CenteredTable LeftHeader">
 <tr><td colspan="3">
 Use this form to set your personalized defaults. When you are done press submit.<br/>
 You must have your browser configured to accept cookies to use  this feature.<br/>
 You can always use the advanced options to override these choices.<br/>
 You can also <a href="$CustomListForm">change the appearance</a> of lists of documents shown by DocDB.
 </td></tr>
};

print "<tr><th>\n";
print FormElementTitle(-helplink => "namepref", -helptext => "Name");
print "</th>\n";

print "<td colspan=\"2\">\n";
AuthorScroll(-helplink => "",
             -name     => "requester",
             -default  => [$UserPreferences{AuthorID}] );
print "</td></tr>\n";

print "<tr><th>\n";
print FormElementTitle(-helplink => "uploadtype", -helptext => "Upload type");
print "</th>\n";
print "<td>\n";
print $query -> radio_group(-name => "archive", -values => \@archives, -default => $UploadTypePref, -labels
                            => \%archives, -columns => 1);
print "</td><td>\n";
print $query -> textfield(-name => "numfile", -default => $NumFilesPref, -size => 2, -maxlength => 2);
print "<b># of files</b>\n";
print "</td></tr>\n";

print "<tr><th>\n";
print FormElementTitle(-helplink => "uploadmethod", -helptext => "Upload method");
print "</th>\n";
print "<td colspan=\"2\">\n";
print $query -> radio_group(-name => "upload", -values => \@uploads, -default => $UploadMethodPref, -labels => \%uploads);
print "</td></tr>\n";

print "<tr><th>\n";
print FormElementTitle(-helplink => "topicoption", -helptext => "Topic Selection");
print "</th>\n";
print "<td colspan=\"2\">\n";
print $query -> radio_group(-name => "topicmode", -values => \@topicmodes, -default => $TopicModePref, -labels => \%topicmodes);
print "</td></tr>\n";

print "<tr><th>\n";
print FormElementTitle(-helplink => "authoroption", -helptext => "Author Selection");
print "</th>\n";
print "<td colspan=\"2\">\n";
print $query -> radio_group(-name => "authormode", -values => \@authormodes, -default => $AuthorModePref, -labels => \%authormodes);
print "</td></tr>\n";

print "<tr><th>\n";
print FormElementTitle(-helplink => "overdatepref", -helptext => "Override creation date");
print "</th>\n";
print "<td colspan=\"2\">\n";
print $query -> radio_group(-name => "overdate", -values => ['No','Yes'],
                            -default => $DateOverridePref);
print "</td></tr>\n";

print '<tr><td colspan="3" class="SubmitCell">';
print $query -> submit (-value => "Set Preferences");
print "</td></tr>\n";

print "</table>\n";

print $query -> end_form;

DocDBNavBar();
DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
