#! /usr/bin/env perl
#
# Author:  Adam Bryant
#

use CGI;
use DBI;

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "SecuritySQL.pm";
require "Scripts.pm";
require "ResponseElements.pm";
require "Cookies.pm";
require "FormElements.pm";
require "Sorts.pm";
require "AuthorSQL.pm";

# Start page

$query = new CGI;
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);
&GetAuthors;
print $query->header;
&BTeVHeader("Select Preferences");
&HelpPopupScript;

print $query -> start_multipart_form('POST',$SetPrefs);

$uploads{http}   = "HTTP submission";
$uploads{file}   = "Local file upload";
@uploads = ("file","http");

$archives{archive} = "Archive (.tar/.zip) upload";
$archives{single}  = "Single file";
$archives{multi}   = "Multiple files";
@archives = ("single","multi","archive");

$topicmodes{multi}  = "Multiple Topic Boxes";
$topicmodes{single} = "Single Topic List";
@topicmodes = ("multi","single");

$authormodes{field} = "Text field";
$authormodes{list}  = "Selectable list";
@authormodes = ("list","field");

&GetPrefsCookie;

print "<table cellpadding=5 border=5 align=center>\n";
print "<tr><td colspan=2 align=center><big>Select Preferences</big><br>
       Use this form to set your own file upload defaults.</th></tr>\n";
print "<tr><td align=right>\n";
print "<a "; &HelpLink("modifytypes"); 
print "<b>Name:</b></a>\n";

print "<td>\n";
 print "<table cellpadding=3><tr><td>\n";
 $RequesterDefault = $UserIDPref;
 &RequesterSelect;
 print "<tr><td align=right valign=bottom>\n";
 print "</table>\n";

print "<tr><td align=right>\n";
print "<a "; &HelpLink("uploadtype"); 
print "<b>Upload type:</b></a>\n";
print "<td>\n";
print "<table cellpadding=3><tr><td>\n";
print $query -> radio_group(-name => "archive", -values => \@archives, -default => $UploadTypePref, -labels
                            => \%archives, -columns => 1);
print "</td><td>\n";
print $query -> textfield(-name => "numfile", -default => $NumFilesPref, -size => 2, -maxlength => 2);
print "<b># of files</b>\n";
print "</td></tr></table>\n";

print "<tr><td align=right>\n";
print "<a "; &HelpLink("uploadmethod"); 
print "<b>Upload method:</b></a>\n";
print "<td>\n";
print $query -> radio_group(-name => "upload", -values => \@uploads, -default => $UploadMethodPref, -labels => \%uploads);

print "<tr><td align=right>\n";
print "<a "; &HelpLink("topicoption"); 
print "<b>Topic Selection:</b></a>\n";
print "<td>\n";
print $query -> radio_group(-name => "topicmode", -values => \@topicmodes, -default => $TopicModePref, -labels => \%topicmodes);
print "<tr><td align=right>\n";
print "<a "; &HelpLink("authoroption"); 
print "<b>Author Selection:</b></a>\n";
print "<td>\n";
print $query -> radio_group(-name => "authormode", -values => \@authormodes, -default => $AuthorModePref, -labels => \%authormodes);
print "<tr><td align=right>\n";
print "<a "; &HelpLink("dateoverride"); 
print "<b>Override submit date:</b></a>\n";
print "<td>\n";
print $query -> radio_group(-name => "overdate", -values => ['Yes','No'],
                            -default => $DateOverridePref);
print "<tr><td align=center colspan=2>\n";
print $query -> submit (-value => "Set Preferences");
print "</table>\n";
print $query -> endform;

&DocDBNavBar;
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
