#! /usr/bin/env perl
#
# Author:  Adam Bryant
#

# Copyright 2001-2005 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use CGI;
use DBI;

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "SecuritySQL.pm";
require "Scripts.pm";
require "ResponseElements.pm";
require "Cookies.pm";
require "FormElements.pm";
require "Sorts.pm";
require "AuthorSQL.pm";

require "AuthorHTML.pm";

# Start page

$query = new CGI;
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);
&GetAuthors;
print $query->header;
&DocDBHeader("Select Preferences");
&HelpPopupScript;

print $query -> start_multipart_form('POST',$SetPrefs);

$uploads{http}   = "HTTP submission";
$uploads{file}   = "Local file upload";
@uploads = ("file","http");

$archives{archive} = "Archive (.tar/.zip) upload";
$archives{single}  = "Single file";
$archives{multi}   = "Multiple files";
@archives = ("single","multi","archive");

$topicmodes{multi}  = "Multiple Topic Boxes";
$topicmodes{single} = "Single Topic List";
@topicmodes = ("multi","single");

$authormodes{field} = "Text field";
$authormodes{list}  = "Selectable list";
@authormodes = ("list","field");

&GetPrefsCookie;

print "<table cellpadding=5 border=5 align=center>\n";
print "<tr><td align=center><big>Select Preferences</big><br>
       Use this form to set your personalized defaults. When you are done 
       press submit.<br>
       You must have your browser configured to accept cookies to use
       this feature.<br>
       You can always use the advanced options to override these choices.</th></tr>\n";
print "<tr><td>\n";

print "<table align=center>\n";

 print "<tr><td align=right valign=top>\n";
 print "<a "; &HelpLink("namepref"); 
 print "<b>Name:</b></a>\n";
 print "</td>\n";

 print "<td>\n";
 my @RequesterDefaults = ($UserIDPref);
 &AuthorScroll(-helplink => "",
               -name     => "requester",
               -default  => \@RequesterDefaults);
 print "</td></tr>\n";

 print "<tr><td align=right>\n";
 print "<a "; &HelpLink("uploadtype"); 
 print "<b>Upload type:</b></a>\n";
 print "<td>\n";
 print "<table cellpadding=3><tr><td>\n";
 print $query -> radio_group(-name => "archive", -values => \@archives, -default => $UploadTypePref, -labels
                             => \%archives, -columns => 1);
 print "</td><td>\n";
 print $query -> textfield(-name => "numfile", -default => $NumFilesPref, -size => 2, -maxlength => 2);
 print "<b># of files</b>\n";
 print "</td></tr></table>\n";

 print "<tr><td align=right>\n";
 print "<a "; &HelpLink("uploadmethod"); 
 print "<b>Upload method:</b></a>\n";
 print "<td>\n";
 print $query -> radio_group(-name => "upload", -values => \@uploads, -default => $UploadMethodPref, -labels => \%uploads);

 print "<tr><td align=right>\n";
 print "<a "; &HelpLink("topicoption"); 
 print "<b>Topic Selection:</b></a>\n";
 print "<td>\n";
 print $query -> radio_group(-name => "topicmode", -values => \@topicmodes, -default => $TopicModePref, -labels => \%topicmodes);
 print "<tr><td align=right>\n";
 print "<a "; &HelpLink("authoroption"); 
 print "<b>Author Selection:</b></a>\n";
 print "<td>\n";
 print $query -> radio_group(-name => "authormode", -values => \@authormodes, -default => $AuthorModePref, -labels => \%authormodes);
 print "<tr><td align=right>\n";
 print "<a "; &HelpLink("overdatepref"); 
 print "<b>Override submit date:</b></a>\n";
 print "<td>\n";
 print $query -> radio_group(-name => "overdate", -values => ['No','Yes'],
                             -default => $DateOverridePref);
print "</table>\n";
print "<tr><td align=center>\n";
print $query -> submit (-value => "Set Preferences");
print "</table>\n";
print $query -> endform;

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
