#! /usr/bin/env perl
#
#        Name: SessionModify
# Description: Add talks to sessions of a meeting. Calls itself. 
# In future, might also be allowed to modify certain aspects of the session.
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

use CGI;
use DBI;

require "DocDBGlobals.pm";
require "Cookies.pm";
require "Defaults.pm";

require "HTMLUtilities.pm";
require "ResponseElements.pm";
require "Sorts.pm";
require "Scripts.pm";

require "MeetingHTML.pm";
require "TalkHTML.pm";
require "TalkSQL.pm";
require "TalkHintSQL.pm";
require "TalkHintUtilities.pm";

$query = new CGI;  # Global for subroutines

print $query -> header;
&DocDBHeader("Modify a Session");
&HelpPopupScript;

&GetPrefsCookie;
&SetAuthorMode;
%params = $query -> Vars;

my $SessionID          = $params{sessionid};
my $Mode               = $params{mode};

my @SessionOrderIDs = split /\0/,$params{sessionorderid};
my @TalkOrders      = split /\0/,$params{talkorder};
my @TalkTitles      = split /\0/,$params{talktitle};
my @TalkNotes       = split /\0/,$params{talknote};
my @TalkTimes       = split /\0/,$params{talktime};
my @TalkSeparators  = split /\0/,$params{talkseparator};
my @TalkDeletes     = split /\0/,$params{talkdelete};
my @TalkConfirms    = split /\0/,$params{talkconfirm};

# Also have params for DocID, authors, and topics in special params with 
# SessionID embedded

# Repack checkboxes into hashes

my %TalkDeleteFlags = ();
foreach my $TalkDelete (@TalkDeletes) { 
  $TalkDeleteFlags{$TalkDelete} = 1; 
}  
my %TalkSeparatorFlags = ();
foreach my $TalkSeparator (@TalkSeparators) { 
  $TalkSeparatorFlags{$TalkSeparator} = 1; 
}  
my %TalkConfirmFlags = ();
foreach my $TalkConfirm (@TalkConfirms) { 
  $TalkConfirmFlags{$TalkConfirm} = 1; 
}  
  
@ErrorStack = ();
@WarnStack  = ();

$dbh   = DBI -> connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);

unless ($dbh) {
  push @ErrorStack,$Msg_NoConnect;
}         
&EndPage(@ErrorStack);

if ($Mode eq "modify") {
  my %TalkOrders = (); # Re-sort talk orders
  {
    foreach my $TalkOrder (@TalkOrders) {
      $TalkOrders{$TalkOrder} = $TalkOrder;
    } 
    my @OrderedOrders = sort numerically @TalkOrders;

    my $NewOrder = 1;
    foreach my $TalkOrder (@OrderedOrders) {
      $TalkOrders{$TalkOrder} = $NewOrder;
      ++$NewOrder;
    } 
  }
  
# Loop over sessions and insert
  &FetchSessionOrdersBySessionID($SessionID);
 
  my $TalksUpdated    = 0;

  foreach my $TalkOrder (@TalkOrders) {
    my $TalkTime       = shift @TalkTimes       ;
    my $TalkTitle      = shift @TalkTitles      ;
    my $TalkNote       = shift @TalkNotes       ;
    my $SessionOrderID = shift @SessionOrderIDs ;
    my $TalkNewOrder   = $TalkOrders{$TalkOrder};

    my $TalkSeparatorID = 0;
    my $SessionTalkID   = 0;
    
    my $TalkConfirmed   = $TalkConfirmFlags{$SessionOrderID};
    my $TalkDocID       = $params{"talkdocid-$SessionOrderID"};
    my $NewSessionID    = $params{"newsessionid-$SessionOrderID"};
    
    if (grep /n/,$SessionOrderID) { # Key on SessionOrderID to see if insert or update.	
      if ($TalkTitle || $TalkNote || $TalkDocID) {
	++$TalksUpdated;
	if ($TalkSeparatorFlags{$SessionOrderID}) {
          my $TalkSeparatorInsert = $dbh -> prepare(
           "insert into TalkSeparator ".
           "(TalkSeparatorID, SessionID, Time, Title, Note) ". 
           "values (0,?,?,?,?)");
          $TalkSeparatorInsert -> execute($SessionID,$TalkTime,$TalkTitle,$TalkNote);
          $TalkSeparatorID = $TalkSeparatorInsert -> {mysql_insertid}; # Works with MySQL only
	} else {
          my $TalkInsert = $dbh -> prepare(
           "insert into SessionTalk ".
           "(SessionTalkID, SessionID, DocumentID, Confirmed, Time, HintTitle, Note) ". 
           "values (0,?,?,?,?,?,?)");
          $TalkInsert          -> execute($SessionID,$TalkDocID,$TalkConfirmed,$TalkTime,$TalkTitle,$TalkNote);
          $SessionTalkID = $TalkInsert -> {mysql_insertid}; # Works with MySQL only

          my @TopicHints  = split /\0/,$params{"topics-$SessionOrderID"}; 
          my @AuthorHints = split /\0/,$params{"authors-$SessionOrderID"}; 
          &InsertTopicHints($SessionTalkID,@TopicHints);
          &InsertAuthorHints($SessionTalkID,@AuthorHints);
	}
        my $SessionOrderInsert = $dbh -> prepare(
         "insert into SessionOrder ".
         "(SessionOrderID, TalkOrder, SessionTalkID, TalkSeparatorID) ". 
         "values (0,?,?,?)");
	$SessionOrderInsert -> execute($TalkNewOrder,$SessionTalkID,$TalkSeparatorID);
      }  
    } else {
      $TalkSeparatorID = $SessionOrders{$SessionOrderID}{TalkSeparatorID};
      $SessionTalkID   = $SessionOrders{$SessionOrderID}{SessionTalkID};

      if ($TalkDeleteFlags{$SessionOrderID}) { # Delete session or separator
        if ($TalkSeparatorID) {
          &DeleteTalkSeparator($TalkSeparatorID);
        } elsif ($SessionTalkID) {
          &DeleteSessionTalk($SessionTalkID);
        }
      } elsif ($TalkTitle || $TalkNote || $TalkDocID) { # We will modify existing talks
	++$TalksUpdated;
	
        if ($TalkSeparatorID) { # Modify a talk separator
          my $TalkSeparatorUpdate = $dbh -> prepare(
           "update TalkSeparator set ".
           "Time=?, Title=?, Note=? ". 
           "where TalkSeparatorID=?");
          $TalkSeparatorUpdate -> execute($TalkTime,$TalkTitle,$TalkNote,$TalkSeparatorID);
          if ($NewSessionID) { # Move to new session
            my $TalkSeparatorMove = $dbh -> prepare(
             "update TalkSeparator set SessionID=? where TalkSeparatorID=?");
            $TalkSeparatorMove -> execute($NewSessionID,$TalkSeparatorID);
          }
        } elsif ($SessionTalkID) { # Modify a talk
          my $SessionTalkUpdate = $dbh -> prepare(
           "update SessionTalk set ".
           "DocumentID=?, Confirmed=?, Time=?, HintTitle=?, Note=? ". 
           "where SessionTalkID=?");
          $SessionTalkUpdate -> execute($TalkDocID,$TalkConfirmed,$TalkTime,$TalkTitle,$TalkNote,$SessionTalkID);

          my @TopicHints  = split /\0/,$params{"topics-$SessionOrderID"};
          
          my @AuthorHints = ();
          if ($params{"authors-$SessionOrderID"}) {
            @AuthorHints = split /\0/,$params{"authors-$SessionOrderID"};
          } elsif ($params{"authortext-$SessionOrderID"}) { 
            require "AuthorSQL.pm";
            my $AuthorText = $params{"authortext-$SessionOrderID"};
            @AuthorHints = &ProcessManualAuthors($AuthorText);
          }
          &InsertTopicHints($SessionTalkID,@TopicHints);
          &InsertAuthorHints($SessionTalkID,@AuthorHints);
          if ($NewSessionID) { # Move to new session
            my $SessionTalkMove = $dbh -> prepare(
             "update SessionTalk set SessionID=? where SessionTalkID=?");
            $SessionTalkMove -> execute($NewSessionID,$SessionTalkID);
          }
        }

        my $SessionOrderUpdate = $dbh -> prepare(
         "update SessionOrder set TalkOrder=? where SessionOrderID=?");
        $SessionOrderUpdate -> execute($TalkNewOrder,$SessionOrderID);
      }  
    }  
  }
}

&EndPage(@ErrorStack);

&ReHintTalksBySessionID($SessionID); 
&ClearSessionTalks();

# Fetch all SessionTalks and TalkSeparators with this SessionID 
my @SessionTalkIDs   = &FetchSessionTalksBySessionID($SessionID);
my @TalkSeparatorIDs = &FetchTalkSeparatorsBySessionID($SessionID);
my @SessionOrderIDs  = &FetchSessionOrdersBySessionID($SessionID);

# Sort talks and separators (subroutine)

@SessionOrderIDs = sort SessionOrderIDByOrder @SessionOrderIDs;

# Display all info on all talks plus a number of blanks

require "Utilities.pm";

&PrintSessionHeader($SessionID); 

print $query -> start_multipart_form('POST',"$SessionModify");
$query -> param('sessionid',$SessionID);
print $query -> hidden(-name => 'sessionid', -default => $SessionID);
$query -> param('mode','modify');
print $query -> hidden(-name => 'mode', -default => 'modify');

print "<table cellpadding=10>\n";

print "<tr valign=top>\n";
 print "<td>\n"; 
  &TalkEntryForm(@SessionOrderIDs);   
 print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
 print "<td align=center>\n";
  print $query -> submit (-value => "Modify Session and Talks");
 print "</td>\n";
print "</tr>\n";

print "</table>\n";

my $NavBarText = "Display&nbsp;Session";
my $NavBarURL  = "$DisplayMeeting?sessionid=$SessionID";
&DocDBNavBar($NavBarText,$NavBarURL);

&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
 
exit;
