#! /usr/bin/env perl
#
#        Name: SessionModify
# Description: Add talks to sessions of a meeting. Calls itself. 
# Might also be allowed to modify certain aspects of the session? 
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

use CGI;
use DBI;

require "Debug.pm"; #FIXME: Remove 

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "ResponseElements.pm";
require "Sorts.pm";
require "Scripts.pm";

require "TalkHTML.pm";
require "TalkSQL.pm";

$query = new CGI;  # Global for subroutines

print $query -> header;
&DocDBHeader("Modify a Session");
&HelpPopupScript;

%params = $query -> Vars;

my $Mode               = $params{mode};

my $SessionID          = $params{sessionid};

#my $StartYear          = $params{startyear};
#my $StartMonth         = $params{startmonth};
#my $StartDay           = $params{startday};
#my $EndYear            = $params{endyear};
#my $EndMonth           = $params{endmonth};
#my $EndDay             = $params{endday};
#my $MeetPreamble       = $params{meetpreamble};
#my $MeetEpilogue       = $params{meetepilogue};
#my $Location           = $params{location};
#my $URL                = $params{url};

#my @SessionYears         = split /\0/,$params{sessionyear};
#my @SessionMonths        = split /\0/,$params{sessionmonth};
#my @SessionDays          = split /\0/,$params{sessionday};
#my @SessionHours         = split /\0/,$params{sessionhour};
#my @SessionOrders        = split /\0/,$params{sessionorder};
#my @RawSessionSeparators = split /\0/,$params{sessionseparator};
#my @SessionTitles        = split /\0/,$params{sessiontitle};
#my @SessionDescriptions  = split /\0/,$params{sessiondescription};
#my @MeetingOrderIDs      = split /\0/,$params{meetingorderid};
#my @SessionTypes         = split /\0/,$params{sessiontype};

#my $StartDate = "$StartYear-$ReverseAbrvMonth{$StartMonth}-$StartDay";
#my $EndDate   = "$EndYear-$ReverseAbrvMonth{$EndMonth}-$EndDay";

@ErrorStack = ();
@WarnStack  = ();

&HTMLPrintParams();

$dbh   = DBI -> connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);

unless ($dbh) {
  push @ErrorStack,$Msg_NoConnect;
}         
&EndPage(@ErrorStack);

#if ($Mode eq "create") {
#}

&EndPage(@ErrorStack);

# Read in Hints (subroutine)
# Re-hint all talks (subroutine)

# Fetch all SessionTalks and TalkSeparators with this SessionID 

my @SessionTalkIDs   = &FetchSessionTalksBySessionID($SessionID);
my @TalkSeparatorIDs = &FetchTalkSeparatorsBySessionID($SessionID);
my @SessionOrderIDs  = &FetchSessionOrdersBySessionID($SessionID);

# Sort talks and separators (subroutine)

@SessionOrderIDs = sort SessionOrderIDByOrder @SessionOrderIDs;

# Display all info on all talks plus a number of blanks

print $query -> start_multipart_form('POST',"$SessionModify");

print "<table cellpadding=10>\n";

print "<tr valign=top>\n";
 print "<td>\n"; 
  &TalkEntryForm(@SessionOrderIDs);   
 print "</td>\n";
print "</tr>\n";

print "<tr valign=top>\n";
 print "<td align=center>\n";
  print $query -> submit (-value => "Modify Session and Talks");
 print "</td>\n";
print "</tr>\n";

print "</table>\n";


&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
 
exit;
