#! /usr/bin/env perl

use lib ".";

#
#        Author:  Eric Vaandering
#          Date:  22 May 2005
#
# Allow a user to choose to limit their membership to certain groups
# for a period of time

# Copyright 2001-2013 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA


use CGI qw(-nosticky);
use CGI::Untaint;
use DBI;

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "UntaintInput.pm";
require "ResponseElements.pm";
require "Cookies.pm";

# Start page

$query = new CGI;  # Global for subroutines
$query -> autoEscape(0);
my $Untaint = CGI::Untaint -> new($query -> Vars);

my @cookies = ();

my $Duration = $Untaint -> extract(-as_safehtml => "duration") || "";
my @GroupIDs = @{ $Untaint -> extract(-as_listofint => "groups") || undef };
unless (@GroupIDs) {
  @GroupIDs = (-1);
}
my $GroupIDs = join ',',@GroupIDs;

if ($Duration eq "session") {
  push @cookies, $query -> cookie(-name  => 'groupids',
			          -value => $GroupIDs,
			          -path  => $cgi_path);
} else {
  my $Expires = "+".int($Duration)."d";
  push @cookies, $query -> cookie(-name    => 'groupids',
			          -value   => $GroupIDs,
			          -expires => $Expires,
			          -path    => $cgi_path);
}

print $query->header( -charset => $HTTP_ENCODING, -cookie=>\@cookies);

$dbh   = DBI -> connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);
unless ($dbh) {
  push @ErrorStack,$Msg_NoConnect;
}

DocDBHeader("Setting Groups","",-nobody => $TRUE);
EndPage(@ErrorStack);

print "<table class=\"LowPaddedTable\"><tr><td>\n";
print "<strong>You are limited to the groups you selected.</strong><br/>
          If your  groups havn't been properly set, make sure your web
          browser is  accepting cookies.";
print "</td></tr>";
print "<tr><td id=\"SubmitCell\">\n<form action=\"\"><div>\n";
print " <input type=\"button\" value=\"Close Window and Reload\" onclick=\"opener.location.reload(1); window.close()\" />\n";
print "</div></form>\n</td></tr></table>";

DocDBFooter($DBWebMasterEmail,$DBWebMasterName,-nobody => $TRUE);
