#! /usr/bin/env perl
#
#        Author:  Adam Bryant
#          Date:  24 March 2002
#   Modified by:  Eric Vaandering
# Last Modified:  27 March 2002
#
# Reads form parameters from SelectPrefs and stores user's selections in
# a group of cookies, one for each preference.

use CGI;

require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "ResponseElements.pm";
require "Cookies.pm";

# Start page

$query = new CGI;
%params = $query -> Vars; 

@cookies = ();

push @cookies, $query->cookie(-name=>'userid', 
			  -value=>"$params{requester}", 
			  -expires=>'+30y',
			  -path=>$cgi_path);
push @cookies, $query->cookie(-name=>'archive', 
			  -value=>"$params{archive}",
 			  -expires=>'+30y',
			  -path=>$cgi_path);
push @cookies, $query->cookie(-name=>'numfile', 
			  -value=>"$params{numfile}",
 			  -expires=>'+30y',
			  -path=>$cgi_path);
push @cookies, $query->cookie(-name=>'upload', 
			  -value=>"$params{upload}", 
			  -expires=>'+30y',
			  -path=>$cgi_path);
push @cookies, $query->cookie(-name=>'topicmode', 
			  -value=>"$params{topicmode}", 
			  -expires=>'+30y',
			  -path=>$cgi_path);
push @cookies, $query->cookie(-name=>'authormode', 
			  -value=>"$params{authormode}", 
			  -expires=>'+30y',
			  -path=>$cgi_path);
push @cookies, $query->cookie(-name=>'overdate', 
			  -value=>"$params{overdate}", 
			  -expires=>'+30y',
			  -path=>$cgi_path);
                          
print $query->header(-cookie=>\@cookies);
print "<meta http-equiv=\"Refresh\" content=\"10; URL=$MainPage\">"; ### generates improper html but works for now

&DocDBHeader("Setting Preferences");

print "<p>";
print "<b>Your preferences have been saved.</b> 
          You will be sent to the Document Database <a href=\"$MainPage\">home
          page</a> in 10 seconds.<br> 
          If your  preferences havn't been properly set, make sure your web
          browser is  accepting cookies.";
print "<p>";

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
