#! /usr/bin/perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;
use DBI;

require "ResponseElements.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";
require "FSUtilities.pm";
require "Security.pm";

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

$DocumentID = $params{docid};
$Version    = $params{version}; 

print $query->header;
print $query->start_html(-title=>"BTeV Document $DocumentID, v$Version");
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);


unless ($DocumentID) {$DocumentID = 79;}

unless (&CanAccess($DocumentID,$Version)) {
  print "You are not authorized to view this document.<p>\n";
#  exit;
}
&FetchDocument($DocumentID);
unless ($Version) {$Version = $Documents{$DocumentID}{NVER}}

my $DocRevID   = &FetchDocRevision($DocumentID,$Version);

&PrintRevisionInfo($DocRevID);

print $query->end_html; 
