#! /usr/bin/perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use Benchmark;
use CGI;
use DBI;

$StartTime = new Benchmark;

require "ResponseElements.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";
require "FSUtilities.pm";
require "HTMLUtilities.pm";
require "Security.pm";

&GetSecurityGroups;

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

$DocumentID = $params{docid};

unless ($DocumentID) {
  print $query->header;
  print "You are must supply a document number!<p>\n";
  print $query->end_html; 
  exit;
}  
  
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);
&FetchDocument($DocumentID);

if (defined $params{version}) {
  $Version    = $params{version};
} else {   
  $Version = $Documents{$DocumentID}{NVER};
}

print $query->header;
&BTeVHeader("BTeV Document $DocumentID-v$Version");

unless (&CanAccess($DocumentID,$Version)) {
  print "You are not authorized to view this document.<p>\n";
  &BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
  exit;
}  

my $DocRevID   = &FetchDocRevision($DocumentID,$Version);

unless ($DocRevID) {
  print "This document does not exist.<p>\n";
  &BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
  exit;
}
  

&PrintRevisionInfo($DocRevID);

&OtherVersionLinks($DocumentID,$Version);

$EndTime  = new Benchmark;
$TimeDiff = timediff($EndTime,$StartTime);
print "<p><b>Execution time: </b>",timestr($TimeDiff),"<p>\n";

&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
