#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2005 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use Benchmark; $StartTime = new Benchmark;
use CGI;
use DBI;
use DateTime;

require "DocDBGlobals.pm";
require "DBUtilities.pm";
require "HTMLUtilities.pm";

require "CalendarHTML.pm";
require "MeetingHTML.pm";

require "MeetingSQL.pm";

$query = new CGI;  # Global for subroutines

my %Params = $query -> Vars;

# my $Days         = $Params{days}         || 0;

&CreateConnection();

### Start HTML

print $query->header;
&DocDBHeader("Calendar for xxx");

require "Sorts.pm";

# Use last_day_of_month
my $Year = 2002;

print "<table class=\"Calendar WholeYear\">\n";
for my $Month (1 .. 12) {
  unless (($Month-1) % 4) {
    print "<tr>\n";
  }
  print "<td class=\"Month\">";   
  &PrintCalendar(-year => $Year, -month => $Month, -type => "year");
  print "</td>";   
  unless ($Month % 4) {
    print "</tr>\n";
  }
}
print "</table>\n";

# Print a single month

my $Month = 6;
&PrintCalendar(-year => $Year, -month => $Month);

$EndTime  = new Benchmark;

&DocDBNavBar();
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
