#! /usr/bin/env perl
#
#        Name: ShowTalkNote
# Description: Usually called as a pop-up, this will look up the note for a talk
#              and display it since it could get crowded in the normal table.
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 

use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "Messages.pm";

require "ResponseElements.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";
require "TalkSQL.pm";
require "TalkHintSQL.pm";

$query = new CGI;  
%params = $query -> Vars;

my $SessionTalkID = $params{sessiontalkid};   # Extract term user wants help for

@ErrorStack = ();
@WarnStack  = ();

$dbh   = DBI -> connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);

unless ($dbh) {
  push @ErrorStack,$Msg_NoConnect;
}         
&EndPage(@ErrorStack);

# Collect info

&FetchSessionTalkByID($SessionTalkID);
my $SessionID  = $SessionTalks{$SessionTalkID}{SessionID};
my $DocumentID = $SessionTalks{$SessionTalkID}{DocumentID};
my $Confirmed  = $SessionTalks{$SessionTalkID}{Confirmed} ;
my $Time       = $SessionTalks{$SessionTalkID}{Time}      ;
my $HintTitle  = $SessionTalks{$SessionTalkID}{HintTitle} ;
my $Note       = $SessionTalks{$SessionTalkID}{Note}      ;

my $DocRevID;
if ($DocumentID) {
  &FetchDocument($DocumentID);
  $DocRevID = &FetchRevisionByDocumentAndVersion($DocumentID,$Documents{$DocumentID}{NVersions});
}

my $BestTitle;
if ($Confirmed && $DocumentID) {
  $BestTitle = $DocRevisions{$DocRevID}{TITLE};
} else {
  $BestTitle = $SessionTalks{$SessionTalkID}{HintTitle};    
}
 
# Start page

print $query->header;
print $query->start_html(-title=>"Notes for $BestTitle");

# Print out info

if ($SessionID) {
  my @TopicHintIDs  = &FetchTopicHintsBySessionTalkID($SessionTalkID);
  my @AuthorHintIDs = &FetchAuthorHintsBySessionTalkID($SessionTalkID);

  print "<b><big>Notes for $BestTitle</big></b><p>\n";
  print "<b>This talk was entered with the following information:</b><p/>\n";
  print "<table>\n";
  print "<tr><th align=right>Suggested Title:</th><td>$Title</td></tr>\n";
  print "<tr><th align=right>Notes:</th><td>$Note</td></tr>\n";
  print "<tr><th align=right>Authors:</th><td>\n";
   &ShortAuthorListByID(@AuthorHintIDs);
   print "</td></tr>\n";
  print "<tr><th align=right>Topics:</th><td>\n";
   &ShortTopicListByID(@TopicHintIDs);
   print "</td></tr>\n";
  print "</table><p/>\n";
  if ($DocumentID) {
    if ($Confirmed) {
      print "<b>This talk is a confirmed match with this document:</b>\n";
    } else {
      print "<b>This talk has been matched (but not confirmed) with this document:</b>\n";
    } 
    print "<p/><center><table cellpadding=3>\n";
    &DocumentSummary(0,"meeting");
    &DocumentSummary($DocumentID,"meeting");
    print "</table></center>\n";
  } else {
    print "<b>No document in the database has been matched to this talk.</b>\n"
  }
} else {
  print "<b><big>No notes for this talk</big></b><p>\n";
}  

print $query->end_html;     # End page
