#! /usr/bin/env perl
#
# Description: Change preferences for what/when to be notified of document
#              changes in e-mail.
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

# Copyright 2001-2004 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use CGI;    
use DBI;
                                                  
require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "Scripts.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);
@ErrorStack = ();

%params = $query -> Vars;

# Collect parameters

my $Action      = $params{action};
my $EmailUserID = $params{emailuserid};
my $SignatureID = $params{signatureid};
my $Password    = $params{password-$EmailUserID};

$Password =~ s/\s+//g;

# Start the page
   
print $query->header;
&DocDBHeader("Document Signature");
&HelpPopupScript;

# Check for valid user

# Fetch mail user by ID, set username, and validate

if ($Password) { 
  $EmailUserID = &ValidateEmailUser($UserName,$Password);
}  

unless ($EmailUserID) {
  push @ErrorStack,"The password you entered is invalid. Please try again.";
}

# Standard warnings/errors on exit

&WarnPage(@WarnStack);
&EndPage(@ErrorStack);

# Sign/unsign Document

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);

