#! /usr/bin/env perl
#
#        Name: SignoffChooser
# Description: Lists the people who can sign a document and helps the user
#              build a list of signatures needed for a document.
#              Links insert the name into the form on the calling page
#
#      Author: Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2004 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use CGI;                                                                                      
use DBI;

require "DocDBGlobals.pm";

require "ProjectMessages.pm";

require "HTMLUtilities.pm";
require "NotificationSQL.pm";

require "Scripts.pm";

$query = new CGI;  # Global for subroutines
%params = $query -> Vars;

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

print $query->header;
&DocDBHeader("List of Signees","", -scripts => ["InsertSignature"]);

my @EmailUserIDs = &GetEmailUserIDs();
my $EmailUserID;

foreach $EmailUserID (@EmailUserIDs) {
  &FetchEmailUser($EmailUserID);
}

print "Click on names to insert them into keyword box on the document form.<p>\n";

print "<a name=\"list\">\n";
foreach $EmailUserID (@EmailUserIDs) {
  my $Name = $EmailUser{$EmailUserID}{Name};
  print "<a href=\"#list\" onClick=\"InsertSignature('$Name');\">$Name</a><br>";
}

print "<center><form>\n";

print " <input type=\"button\" value=\"Close Window\" onClick=\"window.close()\">\n";
print "</form></center>";

&DocDBNavBar();
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
