#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

# Copyright 2001-2006 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CGI(-nosticky);                                                                                      
use DBI;

require "FormElements.pm";
require "Scripts.pm";
require "TopicSQL.pm";
require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

GetTopics();

print $query->header;
DocDBHeader("Add Topics","",-scripts => ["PopUps"]);

print $query -> start_multipart_form('POST',"$TopicAdd");

print "<table class=\"CenteredTable MedPaddedTable\">\n";

print "<tr>\n";
print '<td colspan="3">';
print "<h4>Click on any of the headings for help.</h4>\n"; print "</td>\n";
print "</tr><tr>\n";
print "<td>\n"; MajorTopicSelect();                                    print "</td>\n";
print "<td>\n"; ShortDescriptionBox(-helptext => "Short Description"); print "</td>\n";
print "<td>\n"; LongDescriptionBox();                                  print "</td>\n";
print "</tr>\n";
print '<tr><td colspan="3" class="SubmitCell">';

print $query -> submit (-value => "Add Topic");
print "</td></tr></table>\n";
print $query -> end_multipart_form;

print "<h3>Existing Topics:</h3>\n";

TopicsTable();

DocDBNavBar();
DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
