#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)

# Copyright 2001-2005 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use CGI;
use DBI;

require "ResponseElements.pm";
require "TopicSQL.pm";
require "DocDBGlobals.pm";
require "Security.pm";
require "HTMLUtilities.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);

%params = $query -> Vars;

print $query->header;
&DocDBHeader("$Project Topic Addition Results");

print "<p><h3>Here are the results of your attempt to add a topic
                to the $Project document database:</h3><p>\n";

my $topic_insert = $dbh->prepare(
   "insert into MinorTopic ".
          "(MinorTopicID, MajorTopicID, ShortDescription, LongDescription) ". 
   "values (0,            ?,            ?,                ?)");

@ErrorStack = ();

$MajorTopicID     = $params{majortopic};
$ShortDescription = $params{short};
$LongDescription  = $params{long};

if (&MajorIsGathering($MajorTopicID)) {
  push @ErrorStack,"You cannot add conferences or meetings with this form, use the 
       <a href=\"$AdministerForm\">Administration</a> form instead.";
}       
&EndPage(@ErrorStack);

$topic_insert -> execute($MajorTopicID,$ShortDescription,$LongDescription);
my $MinorTopicID = $topic_insert -> {mysql_insertid}; # Works with MySQL only
                           
if ($MinorTopicID) {
  print "You were successful. The topic you added is number <b>$MinorTopicID</b><br>\n"; 
} else {
  print "Something went wrong. Make sure you did everything right. If the
         problem still exists, contact an administrator.\n"; 
}

&DocDBNavBar("Add&nbsp;Topic",$TopicAddForm);
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);

