#! /usr/bin/env perl
#
# Description: This script is called by AdministerForm and does administration
#              on Topics in the DB. TopicAdd is simpler and can only add
#              topics. TopicAdd is most useful in setting up a new DB, while 
#              TopicAdminister will be more useful in maintaining an existing DB. 
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

use CGI;
use DBI;

require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "Security.pm";
require "HTMLUtilities.pm";
require "TopicSQL.pm";
require "Messages.pm";

$query = new CGI;  # Global for subroutines

print $query->header;
&DocDBHeader("Modified List of Topics");

%params = $query -> Vars;

@ErrorStack = ();
@WarnStack  = ();

# Parameters to script 

$Password      = $params{password};
$Username      = $Administrator;
$Action        = $params{admaction};

$TopicID       = $params{topics};
$MajorTopicID  = $params{majortopic};
$LongName      = $params{long};
$ShortName     = $params{short};

unless (&CanAdminister) {
  push @ErrorStack,$Msg_AdminNoLogin;
}  
&EndPage(@ErrorStack);

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$Username,$Password);

unless ($dbh) {
  push @ErrorStack,$Msg_AdminNoConnect;
}         
&EndPage(@ErrorStack);

if      ($Action eq "Delete") {
  my $TopicLink   = &MinorTopicLink($TopicID);
  my @TopicDocIDs = &GetTopicDocuments($TopicID);
  
# Delete TopicID from Author, RevisionTopic tables
  
  my $TopicDelete      = $dbh -> prepare("delete from MinorTopic    where MinorTopicID=?");
  my $ConferenceDelete = $dbh -> prepare("delete from Conference    where MinorTopicID=?");
  my $RevisionDelete   = $dbh -> prepare("delete from RevisionTopic where MinorTopicID=?");
  $TopicDelete      -> execute($TopicID);
  $ConferenceDelete -> execute($TopicID);
  $RevisionDelete   -> execute($TopicID);
  
  print "$TopicLink has been removed from the database.<br>\n";
  if (@TopicDocIDs) {
    push @WarnStack,"$TopicLink was a topic on some documents. These
                     entries have been removed.";
  }  
} elsif ($Action eq "Modify") {
  unless ($TopicID) {
    push @ErrorStack,"You must select a topic to modify.";
  }
  &EndPage(@ErrorStack);

# Deal with name changes     

  if ($ShortName) { 
    print "<b>Updating short topic name.</b><br>\n";
    my $TopicUpdate = $dbh->prepare(
       "update MinorTopic set ShortDescription=? where MinorTopicID=?");
    $TopicUpdate -> execute($ShortName,$TopicID);
  }
  if ($LongName) { 
    print "<b>Updating long topic name.</b><br>\n";
    my $TopicUpdate = $dbh->prepare(
       "update MinorTopic set LongDescription=? where MinorTopicID=?");
    $TopicUpdate -> execute($LongName,$TopicID);
  }

# Deal with Major Topic changes   

  if ($MajorTopicID) { 
    print "<b>Updating Major Topic for Minor Topic.</b><br>\n";
    my $TopicUpdate = $dbh->prepare(
     "update MinorTopic set MajorTopicID=? where MinorTopicID=?");
    $TopicUpdate -> execute($MajorTopicID,$TopicID);
  }
} elsif ($Action eq "New") {
  print "<b>Adding a new topic.</b><br>\n";
  my $TopicInsert = $dbh->prepare(
   "insert into MinorTopic ".
          "(MinorTopicID, MajorTopicID, ShortDescription, LongDescription) ". 
   "values (0,            ?,            ?,                ?)");

  $TopicInsert -> execute($MajorTopicID,$ShortName,$LongName);
  $TopicID = $TopicInsert -> {mysql_insertid}; # Works with MySQL only
} else {
  push @ErrorStack,"No valid action was specified.";
}  

# For modify or new fetch author information and display.

if ($Action eq "Modify" || $Action eq "New") {
  print "<p><b>Here are the results of your modification:<br>\n";
  my $ShortLink = &MinorTopicLink($TopicID,"short");
  my $LongLink = &MinorTopicLink($TopicID,"long");
  print "Short description: $ShortLink<br>\n";
  print "Long description: $LongLink<br>\n";
  print "</b><p>\n";
}  

print "<p>\n";

&WarnPage(@WarnStack);
&EndPage(@ErrorStack);

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
 
exit;
