#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use CGI;                                                                                      
use DBI;

require "FormElements.pm";
require "Scripts.pm";
require "MySQLAccess.pm";
require "DocDBGlobals.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetTopics;

# %params = $query -> Vars;

# Removed updatedb mode, see note in ProcessDocumentAdd

print $query->header;
&BTeVStyle("Add Topics");

&HelpPopupScript;

print $query -> start_multipart_form('POST',"TopicAdd");

print "<center><table cellpadding=10>\n";

print "<tr>\n";
print "<td colspan=3>\n";
print "<h4>You are about to add a topic to the BTeV document database. This
function is restricted to administrators only.<br>
If you are not an administrator,
please stop now and ask an administrator to do this for you.<br>\n";

print "Click on any of the headings for help.</h4>\n"; print "</td>\n";
print "</tr><tr valign=top>\n";
print "<td>\n"; &MajorTopicSelect;     print "</td>\n";
print "<td>\n"; &ShortDescriptionBox;     print "</td>\n";
print "<td>\n"; &LongDescriptionBox;     print "</td>\n";
print "</tr>\n";
print "</table><p>\n";

print $query -> submit (-value => "Add Topic");
print "</center><p>\n";
print $query -> end_multipart_form;

print "<p>\n";


print "<h3>Existing Topics:</h3>\n";

&TopicsTable;

&DocDBNavBar();
&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);
