#! /usr/bin/env perl
#
# Description: Change preferences for what/when to be notified of document
#              changes in e-mail.
#
#      Author: Eric Vaandering (ewv@fnal.gov)
#    Modified: 
#

# Copyright 2001-2005 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use CGI;    
use DBI;
                                                  
require "DocDBGlobals.pm";
require "HTMLUtilities.pm";
require "ResponseElements.pm";
require "EmailSecurity.pm";
require "NotificationSQL.pm";
require "DocumentHTML.pm";

$query = new CGI;  # Global for subroutines
$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);
@ErrorStack = ();

%params = $query -> Vars;

# Collect parameters

my $DocumentID  = $params{docid};
my $UserName    = $params{username};
my $Password    = $params{password};

$UserName =~ s/\s+//g;
$Password =~ s/\s+//g;

# Start the page
   
print $query->header;
&DocDBHeader("Watching Document"); # Prob need specialized header

# Check for valid user

if ($Password) { 
  $EmailUserID = &ValidateEmailUser($UserName,$Password);
#} elsif ($Digest) {
#  $EmailUserID = &ValidateEmailUserDigest($UserName,$Digest);
} elsif ($UserValidation eq "certificate") {
  require "CertificateUtilities.pm";
  $EmailUserID = &FetchEmailUserIDByCert();
}    


# print "Mode: $Mode<br>\n";
  
if ($EmailUserID) {
  &FetchEmailUser($EmailUserID);
#  $Digest = &EmailUserDigest($EmailUserID);
} else {
  push @ErrorStack,"The username/password pair or certificate you supplied is invalid. Please try again or contact and administrator.";
}

if (@ErrorStack) {  # The user made one or more mistakes, warn and exit
  &EndPage(@ErrorStack);
}

# Everything is OK, display the page

if (@WarnStack) {  # The user made one or more mistakes, warn
  &WarnPage(@WarnStack);
}
my $DocumentLink = &NewerDocumentLink(-docid => $DocumentID, -noversion => TRUE);

print "An e-mail will be sent to $EmailUser{$EmailUserID}{EmailAddress} when $DocumentLink changes.<p/>\n";


&InsertEmailDocumentImmediate(-emailuserid => $EmailUserID, -docid => $DocumentID);

&DocDBNavBar;
&DocDBFooter($DBWebMasterEmail,$DBWebMasterName);

