#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

# Copyright 2001-2006 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CGI qw(-nosticky);                                                                                      
use DBI;

require "DocDBGlobals.pm";
require "DBUtilities.pm";
require "HTMLUtilities.pm";
require "ResponseElements.pm";
require "XSearch.pm";

$query = new CGI;  # Global for subroutines

%params = $query -> Vars;

my $SearchText       = $params{searchtext};

CreateConnection(-type => "ro");

print $query->header;
DocDBHeader("DocDB X-Search"); 

my @Projects = ("FOCUS");

my %Documents = ();

foreach my $Project (@Projects) {
  my %ProjectDocuments = XSearchURL( {-project => $Project, -text => $SearchText } );

  foreach my $Identifier (keys %ProjectDocuments) {
    $Documents{$Identifier} = $ProjectDocuments{$Identifier} ;
    push @DebugStack,keys %{$ProjectDocuments{$Identifier}}
  }
}

# sort

# Print document table 

my @Documents = keys %Documents;
if (@Documents) {
  print '<table class="Alternating DocumentList">';
  print '<tr><th>Document</th><th>Title</th><th>Author(s)</th><th>Last Updated</th>';
  foreach my $Identifier (@Documents) {
    print '<tr>';
    print "<td><a href=\"$URL\">$Identifier</a></td>\n";
    print "<td><a href=\"$URL\">$Documents{$Identifier}{Title}</a></td>\n";
    
    print "<td><a href=\"$URL\">$Documents{$Identifier}{Author}</a>";
    if ($Documents{$Identifier}{Author}) {
      print " <emph>et. al.</emph>";
    }  
    print "</td>\n";
    
    print "<td>",EuroDate($Documents{$Identifier}{Date}),"</td>\n";
    
    print "</tr>\n";
  }
  print "</table>\n";
}  

DocDBNavBar();
DocDBFooter($DBWebMasterEmail,$DBWebMasterName);
