#! /usr/bin/perl

use XML::Twig;

require "CopySetup.pm"; # Passwords

# Download XML file from source DocDB

my $OriginalURL = $SourceURL."ShowDocument?docid=904;outformat=xml";
my @Command = ("wget","-O","/tmp/DocDB.xml","--no-check-certificate");
if ($SourceUser) {
  push @Command,"--http-user=$SourceUser","--http-password=$SourcePassword"
}
push @Command,$OriginalURL;
unlink "/tmp/DocDB.xml";
system @Command;

# Read and parse input file

my $Twig = XML::Twig -> new();
open SOURCE,"/tmp/DocDB.xml";
my @Lines = <SOURCE>;
close SOURCE;
my $XMLText = join "\n",@Lines;
$Twig -> safe_parse($XMLText);

# Modify XML

$XML = $Twig -> root();

my $Document = $XML -> first_child("document");
my $DocID     = $Document -> {'att'} -> {'id'};

my $Revision  = $Document -> first_child("docrevision");

# Remove ID numbers from submitter and authors (lookup will handle this)

my $Submitter = $Revision -> first_child("submitter");
$Submitter -> del_att('id');

my @Authors = $Revision -> children("author");
foreach $Author (@Authors) {
  $Author -> del_att('id');
}



print "Fetched DocumentID $DocID\n";

open DEST,">/tmp/NewDocDB.xml";
print DEST ($XML -> sprint()),"\n";
close DEST;

my $SubmitURL   = $DestURL."XMLUpload";
my @Upload = ("curl","-F","outformat=xml","-F","XMLFile=@/tmp/NewDocDB.xml","-u","$DestUser:$DestPassword",$SubmitURL);
system @Upload;

