#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#
# This script did a search on the temple2002 keyword and made sure
# that the "review" user (#5) had access to all such revisions.
#
# The script is now disabled

exit;


use DBI;
require "CGIInclude.pm";

require "DocDBGlobals.pm";
require "TopicSQL.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";
require "MailNotification.pm";
require "Sorts.pm";
require "SecuritySQL.pm";

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);
&GetSecurityGroups;

my $RevisionList = $dbh -> prepare("select DocRevID from DocumentRevision where
Obsolete=0 and Keywords like \"%temple2002%\" ");

my $SecurityList = $dbh -> prepare("select RevSecurityID from RevisionSecurity where GroupID=5 and DocRevID=?");
my $ReviewSecure = $dbh -> prepare("insert into RevisionSecurity
(RevSecurityID,GroupID,DocRevID) values (0,5,?)");

$RevisionList -> execute();
$RevisionList -> bind_columns(undef, \($DocRevID));
while ($RevisionList -> fetch) {
  $SecurityList -> execute($DocRevID);
  ($RevSecurityID) = $SecurityList -> fetchrow_array;
  if ($RevSecurityID) {
    print "Revision $DocRevID already protected.\n";
  } else {
    print "Revision $DocRevID needs protection.\n";
    $ReviewSecure -> execute($DocRevID);
    
  }
}  
