#! /usr/bin/env perl

use lib ".";

#
# Author Eric Vaandering (ewv@fnal.gov)
#

# Copyright 2001-2009 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

use CPAN;
use Getopt::Long;
GetOptions("a=s" => \$Action);

my @Modules = (
               "Benchmark",
               "CGI",
               "CGI::Untaint",
               "Cwd",
               "DateTime",
               "Digest::SHA",
               "DBI",
               "File::Find",
               "File::MimeInfo",
               "Getopt::Std",
               "Mail::Send",
               "Mail::Mailer",
               "Time::Local",
               "XML::Grove::AsCanonXML",
               "XML::Grove::AsString",
               "XML::Parser::PerlSAX",
               "XML::PatAct::MatchName",
               "XML::PatAct::ToObjects",
               "XML::Twig",
               "LWP::UserAgent",
               "HTML::TreeBuilder",
               "Data::ICal",
               "Data::ICal::Entry::Event",
               "DateTime::Format::ICal",
              );

foreach $mod (@Modules) {
  my $obj = CPAN::Shell -> expand('Module',$mod);

  my $Latest    = $obj -> cpan_version();
  my $UpToDate  = $obj -> uptodate();
  my $Installed = $obj -> inst_version();

  if ($UpToDate) {
    print "Up to date:            $mod version $Installed\n";
  } elsif ($Installed) {
    print "New version available: $mod version $Installed installed, $Latest available\n";
#        if ($Action eq "Update") {
#          $obj -> install();
#        }
  } else {
    print "Not installed:         $mod, $Latest available\n";
#        if ($Action eq "Update" || $Action eq "Install") {
#          $obj -> install();
#        }
  }
}

print "\nIf any modules were missing, you need to install them.\n
Type
  \$ setenv LANG en_US
  \$ perl -MCPAN -e shell
on the command line and type
  install File::MimeInfo (for instance)
on the CPAN prompt. Be sure to answer [yes] to install dependencies.

Re-run this script when you are finished to make sure you are
not missing anything.

There is probably no need to update out of date modules, this is for
your information only.  \n";
