#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

# Usage: DeleteDocument -d Doc# -u admin_user -p admin_password
# Replaced by a cgi script, use at your own risk

# Copyright 2001-2006 Eric Vaandering, Lynn Garren, Adam Bryant

#    This file is part of DocDB.

#    DocDB is free software; you can redistribute it and/or modify
#    it under the terms of version 2 of the GNU General Public License 
#    as published by the Free Software Foundation.

#    DocDB is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with DocDB; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
exit;

use Benchmark;
use DBI;
use Getopt::Long;

require "CGIInclude.pm";

require "DocDBGlobals.pm";
require "SecuritySQL.pm";
require "FSUtilities.pm";
require "Sorts.pm";

&GetOptions("d=i" =>  \$DocumentID,
            "u=s" => \$Username,
            "p=s" => \$Password);

unless ($DocumentID) {
  print "Document $DocumentID is invalid\n";
  exit;
}  

# Get directory and pull of version number

$Directory = &GetDirectory($DocumentID);
chop $Directory;chop $Directory;chop $Directory;chop $Directory;

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$Username,$Password);

my $revision_list   = $dbh -> prepare("select DocRevID from DocumentRevision where DocumentID=?");
my $document_delete = $dbh -> prepare("delete from Document         where DocumentID=?");
my $revision_delete = $dbh -> prepare("delete from DocumentRevision where DocumentID=?");
my $author_delete   = $dbh -> prepare("delete from RevisionAuthor   where DocRevID=?");
my $topic_delete    = $dbh -> prepare("delete from RevisionTopic    where DocRevID=?");
my $file_delete     = $dbh -> prepare("delete from DocumentFile     where DocRevID=?");
my $security_delete = $dbh -> prepare("delete from RevisionSecurity where DocRevID=?");

# Find all revisions associated with document

$revision_list -> execute($DocumentID);
$revision_list -> bind_columns(undef, \($DocRevID));
while ($revision_list -> fetch) {
  $Revision{$DocRevID}{DocRevID}      = $DocRevID;
}

my @Revisions = keys %Revision;
unless (@Revisions) {
  print "Document $DocumentID does not exist.\n";
  exit;
}  
  
# Delete stuff from files and linking tables  
  
foreach $RevisionID (@Revisions) {
  $author_delete   -> execute($RevisionID);
  $topic_delete    -> execute($RevisionID);
  $file_delete     -> execute($RevisionID);
  $security_delete -> execute($RevisionID);
}

# Delete revisions and document

$document_delete -> execute($DocumentID);
$revision_delete -> execute($DocumentID);
 
# Delete stuff from file system

$command = "rm -rf $Directory/*";
print "Executing $command\n";
system ($command);
 
exit;
