#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

use Benchmark;
use DBI;

$StartTime = new Benchmark;

require "CGIInclude.pm";

require "DocDBGlobals.pm";
require "Security.pm";
require "MySQLAccess.pm";
require "ResponseElements.pm";
require "HTMLUtilities.pm";

$remote_user = "btev";

&BTeVHeader("BTeV Document List","Document List");

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rouser,$db_ropass);

&GetAllDocuments;
&GetAuthors;
&GetSecurityGroups;

print "<center><table cellpadding=3>\n";
&DocumentSummary(0);

foreach $document (@DocumentIDs) {
  unless (&CanAccess($document,$Documents{$document}{NVER})) {next;}
  &DocumentSummary($document);
}
print "</table></center>\n";
print "<p>\n";

print "Return to the <a href=DocumentDatabase>main page</a>.\n";
print "<p>\n";

$EndTime  = new Benchmark;
$TimeDiff = timediff($EndTime,$StartTime);
print "<p><b>Execution time: </b>",timestr($TimeDiff),"<p>\n";

&BTeVFooter($DBWebMasterEmail,$DBWebMasterName);



