#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

# Usage: MigrateV4 --u=username --p=password --a=init|migrate|delete

use DBI;
use Getopt::Long;

require "CGIInclude.pm";

require "DocDBGlobals.pm";

&GetOptions("a=s" => \$Action,"u=s" => \$User,"p=s" => \$Password);

unless ($Action eq "init" or $Action eq "delete" or $Action eq "migrate") {
  print "Usage: MigrateV5 --u=username --p=password --a=init|migrate|delete\n\n";
  print "This script is used to migrate from a version 4 to version 5 DB structure. \n";
  print "Run this script in \"init\" mode.  \n\n";
  print "At this point you can update the CGI code. Running it in the migrate or delete modes is not needed.  \n";
#  print "Run this script in \"init\" mode first, then in \"migrate\" mode.  \n\n";
#  print "At this point you can update the CGI code and when you are comfortable  \n";
#  print "everything is OK, run in \"delete\" mode to erase old columns and/or tables.  \n";
 exit;
}  

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$User,$Password);

if ($Action eq "init") { # Modify existing tables and add new tables in preparation for migration 

### Edit the first line if you have a different admin account

# Meeting expansion

  my $SessionAdd     = $dbh -> prepare("alter table Session add ShowAllTalks Integer"); 

  # Planned signoff expansion
  
#  my $KeywordGroupCreate = $dbh -> prepare("create table KeywordGroup ".
#                   "(KeywordGroupID integer auto_increment primary key,".
#                   " ShortDescription varchar(32), LongDescription text, TimeStamp timestamp)"); 
  
#  my $KeywordCreate = $dbh -> prepare("create table Keyword ".
#                   "(KeywordID integer auto_increment primary key,".
#                   " KeywordGroupID integer,". 
#                   " ShortDescription varchar(32), LongDescription text, TimeStamp timestamp,". 
#                   " index(KeywordGroupID))"); 
  
#  my $KeywordGroupingCreate = $dbh -> prepare("create table KeywordGrouping ".
#                   "(KeywordGroupingID integer auto_increment primary key,".
#                   " KeywordGroupID integer, KeywordID integer, TimeStamp timestamp,".
#                   " index(KeywordID), index(KeywordGroupID))"); 
  
  $SessionAdd            -> execute();
}

if ($Action eq "migrate") {
  print "No migration necessary.\n";
}

if ($Action eq "delete") { 
  print "No deletions necessary.\n";
}

exit;
