#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

# Usage: MigrateV3

use DBI;
use Getopt::Long;

require "CGIInclude.pm";

require "DocDBGlobals.pm";

&GetOptions("a=s" => \$Action,"u=s" => \$User,"p=s" => \$Password);

unless ($Action eq "init" or $Action eq "delete" or $Action eq "migrate") {
  print "Usage: MigrateV3 --u=username --p=password --a=init|migrate|delete\n\n";
  print "This script is used to migrate from a version 2 to version 3 DB structure. \n";
  print "It adds the administer field to the DB and new tables for multiple journal \n";
  print "references and the (optional) enhanced security model. \n\n";
  print "If you have named your primary administration account anything other than\n";
  print "\"docdbadm\"  you must edit this file first. \n\n";
  print "Run this script in \"init\" mode first, then in \"migrate\" mode.  \n\n";
  print "At this point you can update the CGI code and when you are comfortable  \n";
  print "everything is OK, run in \"delete\" mode to erase old columns and/or tables.  \n";
 exit;
}  

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$User,$Password);

if ($Action eq "init") { # Modify existing tables and add new tables in preparation for migration 

### Edit the first line if you have a different admin account

  my $AdminSet     = $dbh -> prepare("update SecurityGroup set CanAdminister=1 where lower(Name) like \"docdbadm\""); 
  my $AdminAdd     = $dbh -> prepare("alter table SecurityGroup add CanAdminister integer default 0"); 

  my $ModifyCreate = $dbh -> prepare("create table RevisionModify ".
                   "(RevModifyID integer auto_increment primary key,".
                   " GroupID integer, DocRevID integer, TimeStamp timestamp,".
                   " index(GroupID),index(DocRevID))"); 
  my $RefCreate    = $dbh -> prepare("create table RevisionReference ".
                   "(ReferenceID integer auto_increment primary key,".
                   " JournalID integer, Volume integer, Page integer, TimeStamp timestamp,".
                   " index(JournalID))"); 
                   
  $AdminAdd     -> execute();
  $AdminSet     -> execute();
  $ModifyCreate -> execute();               
  $RefCreate    -> execute(); 
}

if ($Action eq "delete") { # Drop useless columns 
  my $JournalDel = $dbh -> prepare("alter table DocumentRevision drop Journal"); 
  my $VolumeDel  = $dbh -> prepare("alter table DocumentRevision drop Volume"); 
  my $PageDel    = $dbh -> prepare("alter table DocumentRevision drop Page"); 
  
  die "This part is not ready yet!\n";
  
  print "Should not see this.\n"
  $JournalDel -> execute();
  $VolumeDel  -> execute();
  $PageDel    -> execute();
}

exit;
