#! /usr/bin/env perl
#
# Author Eric Vaandering (ewv@fnal.gov)
#

# Usage: NotifyDigest -t Weekly|Daily

use DBI;
use Getopt::Long;

require Mail::Mailer;
require Mail::Send;

require "CGIInclude.pm";

require "DocDBGlobals.pm";
require "TopicSQL.pm";
require "DocumentSQL.pm";
require "RevisionSQL.pm";
require "MailNotification.pm";
require "Sorts.pm";

&GetOptions("t=s" => \$Set);

unless ($Set eq "Weekly" or $Set eq "Daily") {
  print "Usage: NotifyDigest -t Weekly|Daily\n";
  exit;
}  

my $Table = "EmailTopic$Set";
my $Days;
if ($Set eq "Weekly") {
  $Days  = 7;
} elsif ($Set eq "Daily") {
  $Days = 1;
}

$dbh   = DBI->connect('DBI:mysql:'.$db_name.':'.$db_host,$db_rwuser,$db_rwpass);

&GetTopics;

my $EmailUserID;
my @EmailUserIDs;

# Find every individual who has a notification set for this time period

my $EmailIDQuery = $dbh -> prepare("select DISTINCT(EmailUserID) from $Table");
$EmailIDQuery -> execute();
$EmailIDQuery -> bind_columns(undef,\($EmailUserID));
while ($EmailIDQuery -> fetch) {
  push @EmailUserIDs,$EmailUserID;
}

# Get the complete list of modified document revisions

my @AllDocRevIDs    = ();
my $RevisionList = $dbh -> prepare("select DocRevID from DocumentRevision where TO_DAYS(NOW())-TO_DAYS(Timestamp)<=?"); 
$RevisionList -> execute($Days);
$RevisionList -> bind_columns(undef, \($DocRevID));
while ($RevisionList -> fetch) {
  push @AllDocRevIDs,$DocRevID;

# Get the topics for each modified revision
  my @MinorRevTopics = &GetRevisionTopics($DocRevID);
  my %MajorRevTopics = ();
  foreach $MinorRevTopic (@MinorRevTopics) {
    $MajorRevTopics{$MinorTopics{$MinorRevTopicID}{MAJOR}} = 1;
  } 
  $AllMinorTopics{$DocRevID} = [@MinorRevTopics];
  $AllMajorTopics{$DocRevID} = [keys %MajorRevTopics];
}

print "Modified Revisions: ",join ' ',@AllDocRevIDs,"\n";

# Build a personal E-mail for each user

foreach $EmailUserID (@EmailUserIDs) {
  &FetchEmailUser($EmailUserID);
  print "Checking user $EmailUserID\n";

  my @UserMinorTopics = ();
  my @UserMajorTopics = ();

# What Minor topics is this user interested in
  
  my $MinorID;
  my $MinorFetch   = $dbh -> prepare(
    "select MinorTopicID from $Table where MinorTopicID!=0 and EmailUserID=?");
  $MinorFetch -> execute($EmailUserID);
  $MinorFetch -> bind_columns(undef, \($MinorID));
  while ($MinorFetch -> fetch) {
    push @UserMinorTopics,$MinorID;
  }
  
# What Major topics is this user interested in
  
  my $MajorID;
  my $MajorFetch   = $dbh -> prepare(
    "select MajorTopicID from $Table where MajorTopicID!=0 and EmailUserID=?");
  $MajorFetch -> execute($EmailUserID);
  $MajorFetch -> bind_columns(undef, \($MajorID));
  while ($MajorFetch -> fetch) {
    push @UserMajorTopics,$MajorID;
  }
  
  print "User $EmailUserID wants minor topics ",join ' ',@UserMinorTopics,"\n";
  print "User $EmailUserID wants major topics ",join ' ',@UserMajorTopics,"\n";
  
# Do they want them all
  
  my $AllFetch   = $dbh -> prepare(
    "select COUNT(EmailUserID) from $Table where MinorTopicID=0 and MajorTopicID=0 and EmailUserID=?");
  $AllFetch -> execute($EmailUserID);
  my ($NotifyAll) = $AllFetch -> fetchrow_array;

  if ($NotifyAll) {
    print "User $EmailUserID wants all topics\n";
  }    

  my %SelectDocRevIDs = ();
  foreach $DocRevID (@AllDocRevIDs) {
    if ($NotifyAll) {
      $SelectDocRevIDs{$DocRevID} = 1; # They want them all
      print "All: flagging revision $DocRevID for user $EmailUserID \n";
      next;
    }
    foreach my $RevMinorTopic (@{$AllMinorTopics{$DocRevID}}) {
      foreach my $UserMinorTopic (@UserMinorTopics) {
        if ($RevMinorTopic == $UserMinorTopic) {
          $SelectDocRevIDs{$DocRevID} = 1; # They want this minor topic
        }
      }    
    }
    foreach my $RevMajorTopic (@{$AllMajorTopics{$DocRevID}}) {
      foreach my $UserMajorTopic (@UserMajorTopics) {
        if ($RevMajorTopic == $UserMajorTopic) {
          $SelectDocRevIDs{$DocRevID} = 1; # They want this major topic
        }
      }    
    }
  }

# We now have all the DocRevIDs, convert to Documents  

  my @SelectDocRevIDs = keys %SelectDocRevIDs;

  print "User $EmailUserID will receive mails on revisions ",join ' ',@SelectDocRevIDs,"\n";
  
  my %DocumentIDs     = ();
  my $DocumentList = $dbh -> prepare(
   "select DocumentID from DocumentRevision where DocRevID=?"); 
  foreach my $DocRevID (@SelectDocRevIDs) {
    $DocumentList -> execute($DocRevID); 
    ($DocumentID) = $DocumentList -> fetchrow_array;
    $DocumentIDs{$DocumentID} = 1; # Hash removes duplicates
  }
  
  my @DocumentIDs = sort numerically keys %DocumentIDs;
  if (@DocumentIDs) {
    print "User $EmailUserID will receive mails on documents ",join ' ',@DocumentIDs,"\n";

# Write the mail
  
    $Mailer = new Mail::Mailer 'smtp', Server => $MailServer;
#    $Mailer = new Mail::Mailer 'test', Server => $MailServer;

    $Headers{To} = $EmailUser{$EmailUserID}{EmailAddress};
    $Headers{From} = "BTeV Document Database <$DBWebMasterEmail>";
    $Headers{Subject} = "$Set changes to BTeV DocDB";
    $Mailer -> open(\%Headers);    # Start mail with headers
    print $Mailer "The following documents were added to the BTeV Document Database ";
    if ($Set eq "Daily") {
      print $Mailer "yesterday:\n\n";
    } elsif ($Set eq "Weekly") {
      print $Mailer "in the last week:\n\n";
    }
    foreach my $DocumentID (@DocumentIDs) {
      &FetchDocument($DocumentID);
      my $DocRevID = &FetchDocRevision($DocumentID,$Documents{$DocumentID}{NVER});


      &RevisionMailBody($DocRevID);       # Write the body
      print $Mailer "\n","-" x 72,"\n\n";  # Write a divider
    } 
    print "Closing, server: $MailServer\n";
    $Mailer -> close;              # Complete the message and send it
  }
}
 
exit;
